<?php
$this->layout()->setTemplate('layout-pre-vista/layout');
$cupon = $this->cupon;
?>
<style type="text/css">
    .left-info-c span {
        width: auto;
        margin-right: 10px;
    }
</style>
<div class="fluid-list cnt-cupon">
    <div class="row primary-info">
        <div class="col-md-8">
            <?php
            $imgCupon = $this->imgCupon;
            $count = count($imgCupon);
            if ($count == 1) :
                foreach ($imgCupon as $img) :
                    ?>
                    <div class="fluid-list img-cupon">
                        <figure>
                            <img src="<?php
                            $trozos = explode(".", $img->ImagenOferta);
                            $ext = end($trozos);
                            $img->ImagenOferta = str_replace('.' . $ext, '', $img->ImagenOferta) . '-large.' . $ext;
                            echo $this->rofertas . $img->ImagenOferta
                            ?>"/>
                            <div class="puntos-ico"></div>
                        </figure>
                    </div>
                <?php endforeach;
            else :
                ?>
                <div class="fluid-list slider-home box-sombra">
                    <div class="fluid-list sombra-interna">
                        <div class="slider slider-promocion box-sombra-caja">
                            <?php foreach ($imgCupon as $img): ?>
                                <div class="info-cupon">
                                    <a href="javascript:;">
                                        <img src="<?php
                                        $partes = explode(".", $img->ImagenOferta);
                                        $ext = end($partes);
                                        $img->ImagenOferta = str_replace('.' . $ext, '', $img->ImagenOferta) . '-large.' . $ext;
                                        echo $this->rofertas . $img->ImagenOferta
                                        ?>"/>
                                        <div class="puntos-ico"></div>
                                    </a>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <div class="col-md-4">
            <div class="fluid-list info-cupon">
                <?php if ($this->identity()['flagcheckboxLogo']) { ?>
                <figure>
                    <img src="<?= $this->rlogos . $cupon->LogoEmpresa ?>"/>
                </figure>
                <?php }?>
                <h1>
                    <?php if ($cupon->PrecioVentaPublico) { ?>
                        <b>S/. <?= $cupon->PrecioVentaPublico ?> por</b>
                    <?php } ?>
                    <?= $cupon->Titulo ?>
                </h1>
                <?php if ($cupon->Estado == 'Publicado' and $cupon->CaducadoTiempo >= 1) : ?>
                    <?php if ($cupon->TipoPrecio == 'Split') : ?>
                        <a href="javascript:;" class="btn btn-cupon">
                            <span>Elegir Cupón</span>
                        </a>
                    <?php else : ?>
                        <a href="javascript:;" class="btn btn-cupon">
                                <span>
                                    <?php if ($cupon->TipoPrecio == 'Split') { ?>
                                        Elegir Cupón
                                    <?php } else { ?>
                                        Descargar Cupón
                                    <?php } ?>
                                </span>
                        </a>
                    <?php endif; ?>
                <?php else : ?>
                    <a class="btn btn-cupon btn-full" style="cursor: default;background: #609EE8">
                        <span>Beneficio Caducado</span></a>
                <?php endif; ?>

                <?php if ($cupon->TipoPrecio != 'Split') :
                    $date = new DateTime($cupon->FechaVigencia);
                    $mes = $date->format('m');
                    ?>
                    <em>Cupón válido hasta
                        el <?php echo ' ' . $date->format('d') . ' de ' . $this->meses[$mes - 1] ?></em>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="fluid-list cnt-condiciones-info title-info-c">
                <h2>Condiciones de Uso</h2>
                <?php echo $cupon->CondicionesUso; ?>
            </div>
        </div>
        <div class="col-md-6">
            <div class="fluid-list cnt-empresa-info title-info-c">
                <h2>Sobre la empresa</h2>
                <p><?php echo $cupon->DescripcionEmpresa; ?></p>
                <div class="row">
                    <div class="col-md-12">
                        <div class="fluid-list left-info-c">
                            <ul>
                                <?php if ($cupon->Direccion != null) : ?>
                                    <li>
                                        <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                                        <div class="cnt-info-list">
                                            <h4>Dirección: </h4>
                                            <em><?= $cupon->Direccion ?></em>
                                        </div>
                                    </li>
                                <?php endif; ?>
                                <?php if ($cupon->Telefono != null) : ?>
                                    <li>
                                        <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
                                        <div class="cnt-info-list">
                                            <h4>Teléfonos: </h4>
                                            <em><?= $cupon->Telefono ?></em>
                                        </div>
                                    </li>
                                <?php endif; ?>
                                <?php if ($cupon->WebEmpresa != null) : ?>
                                    <li>
                                        <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>

                                        <div class="cnt-info-list">
                                            <h4>Sitio Web: </h4>
                                            <em><?= $cupon->WebEmpresa ?></em>
                                        </div>
                                    </li>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-12">
            <div class="fluid-list cnt-terminos">
                <h3>Legal</h3>
                <p><?= $this->conf['termcondiciones'] ?></p>
            </div>
        </div>
    </div>
    <div class="fluid-list btn-cnt">
        <?php if ($cupon->Estado == 'Publicado' and $cupon->CaducadoTiempo >= 1) : ?>
            <?php if ($cupon->TipoPrecio == 'Split') : ?>
                <a href="#" class="btn btn-cupon" data-toggle="modal"
                   data-target="#elegirOpcion">
                    <span>Elegir Cupón</span>
                </a>
            <?php else : ?>
                <a href="#" class="btn btn-cupon" data-toggle="modal"
                   data-target="#enviarPuntos">
                    <span>Descargar Cupón</span>
                </a>
            <?php endif; ?>
        <?php else : ?>
            <a class="btn btn-cupon btn-full" style="cursor: default;background: #609EE8">
                <span>Beneficio Caducado</span></a>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("a.puntos-nav").addClass('active');
    });
</script>