<section class="content-header ">
    <br><br><br>
    <h1 class="box-title">Reporte 01</h1>
    <br>

    <div style="clear:both;"></div>
    <?php if ($this->flashMessenger()->hasMessages()) {
        echo '<div class="callout alert alert-success"><button class="close" data-dismiss="alert" type="button">×</button>';
        $messages = $this->flashMessenger()->getMessages();
        foreach ($messages as $message) {
            echo $message;
        }
        echo '</div>';
    } ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form->setAttribute('action', $this->url('reportes', array('action' => 'exportReporte')));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));

                        ?>
                        <div class="row">
                            <fieldset>
                                <legend>Periodo:</legend>
                                <div class="form-group">
                                    <label class="col-md-2">Desde :</label>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                    <i class="fa fa-calendar"></i>
                                                </div>
                                                <?= $this->formRow($form->get('FechaInicio')); ?>
                                            </div>
                                        </div>
                                    </div>
                                    <label class="col-md-2">Hasta :</label>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                    <i class="fa fa-calendar"></i>
                                                </div>
                                                <?= $this->formRow($form->get('FechaFin')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <br><br>

                                <div class="form-group">
                                    <div class="col-md-offset-6 col-md-6 text-right">
                                        <?= $this->formSubmit($form->get('submit')); ?>
                                    </div>
                                </div>

                            </fieldset>
                            <hr>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php
echo $this->headScript()->prependFile($this->basePath('js/paquete/Paquete.js?' . $this->configItem('version_script')));
?>
