<?php
/**
 * Created by PhpStorm.
 * User: marlo
 * Date: 08/01/16
 * Time: 10:00 AM
 */
?>
<section class="content-header ">
    <br><br><br>
    <h1 class="box-title">Reporte 03</h1>
    <br>

    <div style="clear:both;"></div>
    <?php
    if ($this->flashMessenger()->setNamespace('success')->hasMessages()) {
       echo '<div class="callout alert alert-success"><button class="close" data-dismiss="alert" type="button">×</button>';
       $messages = $this->flashMessenger()->getMessages();
       foreach ($messages as $message) {
           echo $message;
       }
       echo '</div>';
   } elseif ($this->flashMessenger()->setNamespace('error')->hasMessages()) {
        echo '<div class="callout alert alert-error"><button class="close" data-dismiss="alert" type="button">×</button>';
        $messages = $this->flashMessenger()->getMessages();
        foreach ($messages as $message) {
            echo $message;
        }
        echo '</div>';
    }
    ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form->setAttribute('action', $this->url('reportes', array('action' => 'exportTres')));
                        $form->setAttribute('id', 'form-reporte2');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));

                        ?>
                        <div class="row">
                            <fieldset>
                                <div class="col-md-12">
                                    <div class="col-md-2"><label>Empresa :</label></div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <?= $this->formRow($form->get('empresa')); ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <label class="col-md-2">Desde :</label>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                    <i class="fa fa-calendar"></i>
                                                </div>
                                                <?= $this->formRow($form->get('FechaInicio2')); ?>
                                            </div>
                                        </div>
                                    </div>
                                    <label class="col-md-2">Hasta :</label>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                    <i class="fa fa-calendar"></i>
                                                </div>
                                                <?= $this->formRow($form->get('FechaFin2')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 <?=$this->formElementErrors($form->get('Emails')) ? 'has-error' : ''?>">
                                    <label class="col-md-2">Emails :</label>

                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <?= $this->formRow($form->get('Emails')); ?>
                                        </div>
                                    </div>
                                </div>
                                <br><br>
                                <div class="form-group">
                                    <div class="col-md-offset-6 col-md-6 text-right">
                                        <?= $this->formSubmit($form->get('submit')); ?>
                                    </div>
                                </div>
                            </fieldset>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php
echo $this->headScript()->prependFile($this->basePath('js/reportes/reporte_2.js?' . $this->configItem('version_script')));
?>

