<section class="content-header ">
    <br><br><br>
    <h1 class="box-title">Lista de Rubros</h1>
    <div class="clearfix"></div>
    <?php if ($this->flashMessenger()->hasMessages()) {
        echo '<div class="callout alert alert-success"><button class="close" data-dismiss="alert" type="button">×</button>';
        $messages = $this->flashMessenger()->getMessages();
        foreach ($messages as $message) {
            echo $message;
        }
        echo '</div>';
    } ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form->setAttribute('action', $this->url('rubro', array('action' => 'index')));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));

                        ?>
                        <div class="row">
                            <fieldset>
                                <legend>Buscar por:</legend>
                                <div class="form-group">
                                    <label class="col-md-offset-1 col-md-1">Nombre: </label>

                                    <div
                                        class="<?= $this->formElementErrors($form->get('Nombre')) ? 'has-error' : '' ?>">
                                        <div class="col-md-5">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding">
                                                    <?= $this->formRow($form->get('Nombre')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div style="clear:both;"></div>
                                <br>
                                <div class="col-md-12 text-right">
                                    <?= $this->formSubmit($form->get('submit')); ?>
                                </div>
                            </fieldset>
                        </div>
                        <hr>
                        <?= $this->form()->closeTag(); ?>
                    </div>

                    <div class="dataTables_wrapper form-inline dt-bootstrap" id="example1_wrapper">
                        <div class="row-fluid">
                            <div class="col-md-12 text-right">
                                <div id="example1_length" class="dataTables_length">
                                    <a href="<?php echo $this->url('rubro', array('action' => 'export')); ?>"
                                       class="btn btn-primary">Exportar</a>
                                </div>
                            </div>
                        </div>
                        <div style="clear:both;"></div>
                        <br>

                        <div class="row-fluid">
                            <div class="col-sm-12">
                                <table aria-describedby="example1_info" role="grid" id="example1"
                                       class="table table-bordered table-striped dataTable">
                                    <thead>
                                    <tr role="row">
                                        <th>
                                            <?php if ($order_by == 'Nombre'): ?>
                                                <a href="<?= $this->url('rubro', array('order_by' => 'Nombre', 'order' => $order, 'page' => $p, 'q1' => $q1)); ?>">Nombres</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('rubro', array('order_by' => 'Nombre', 'order' => 'asc', 'page' => $p, 'q1' => $q1)); ?>">Nombre</a>
                                            <?php endif; ?>
                                        </th>
                                        <th>
                                            <?php if ($order_by == 'Descripcion'): ?>
                                                <a href="<?= $this->url('rubro', array('order_by' => 'Descripcion', 'order' => $order, 'page' => $p, 'q1' => $q1)); ?>">Descripción</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('rubro', array('order_by' => 'Descripcion', 'order' => 'asc', 'page' => $p, 'q1' => $q1)); ?>">Descripción</a>
                                            <?php endif; ?>
                                        </th>
                                        <th><a>Editar</a></th>
                                        <th>
                                            <?php if ($order_by == 'Activo'): ?>
                                                <a href="<?= $this->url('rubro', array('order_by' => 'Eliminado', 'order' => $order, 'page' => $p, 'q1' => $q1)); ?>">Activo</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('rubro', array('order_by' => 'Eliminado', 'order' => 'asc', 'page' => $p, 'q1' => $q1)); ?>">Activo</a>
                                            <?php endif; ?>
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    if (count($datos)):
                                        foreach ($datos as $dato) : ?>
                                            <tr data-id="<?php echo $dato->id ?>">
                                                <td><?php echo $this->escapeHtml($dato->Nombre); ?></td>
                                                <td><?php echo $this->escapeHtml($dato->Descripcion); ?></td>
                                                <td>
                                                    <a href="<?php echo $this->url('rubro', array('action' => 'edit',
                                                        'id' => $dato->id)); ?>">
                                                        <i class="btn btn-warning fa fa-pencil-square-o"></i></a></td>
                                                </td>
                                                <td>
                                                    <?php if ($dato->Eliminado == 1): ?>
                                                        <input id="elim<?php echo $dato->id ?>"
                                                               name="<?php echo $dato->Eliminado ?>"
                                                               class="elim" type="checkbox">
                                                    <?php else: ?>
                                                        <input id="elim<?php echo $dato->id ?>"
                                                               name="<?php echo $dato->Eliminado ?>"
                                                               class="elim" type="checkbox" checked>
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach;
                                    else: ?>
                                        <tr>
                                            <td colspan="8">No hay Rubros Registrados</td>
                                        </tr>
                                    <?php endif; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div><!-- /.box-body -->
                <div class="col-md-4"><br>

                    <p>
                        <?= (($datos->getCurrentPageNumber() * $datos->getItemCountPerPage()) -
                            ($datos->getItemCountPerPage() - 1)); ?>
                        -
                        <?= ($datos->getCurrentPageNumber() * $datos->getItemCountPerPage() <
                            $datos->getTotalItemCount())
                            ? $datos->getCurrentPageNumber() * $datos->getItemCountPerPage()
                            : $datos->getTotalItemCount() ?> de
                        <?= $datos->getTotalItemCount(); ?> Registros
                    </p>
                </div>
                <?php
                if (isset($datos)) {
                    echo $this->paginationControl(
                        $datos,
                        'Sliding',
                        'paginator-rubro',
                        array(
                            'order_by' => $order_by,
                            'order' => ($order == "desc") ? 'asc' : 'desc',
                            'q1' => $q1,
                        )
                    );
                } ?>
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section>
<?= $this->headScript()->prependFile($this->basePath('js/rubro/rubro_index.js?' . $this->configItem('version_script'))); ?>
