<section class="content-header ">
    <br><br><br>
    <h1 class="box-title">Reporte de Ofertas Publicadas</h1>
    <br>

    <div style="clear:both;"></div>
    <div class="callout alert alert-info">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <h4>
            <i class="icon fa fa-info"></i>
            No hay Ofertas Publicadas
        </h4>
    </div>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12 text-right">
            <a href="/reporte-ofertas" class="btn btn-primary">Generar Reporte</a>
        </div>
    </div>
</section>
