<div class="modal fade" id="modalReferido" tabindex="-1" role="dialog" aria-labelledby="modalReferidoLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title">Referido por</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-12">
                            <h4>Numero de Documento: </h4>
                            <p id="referido-documento"></p>
                        </div>
                        <div class="col-md-12">
                            <h4>Nombres y Apellidos: </h4>
                            <p id="referido-nombre"></p>
                        </div>
                        <div class="col-md-12">
                            <h4>Email: </h4>
                            <p id="referido-email"></p>
                        </div>
                        <div class="col-md-12">
                            <h4>Telefono: </h4>
                            <p id="referido-telefono"></p>
                        </div>
                        <div class="col-md-12">
                            <h4>Nombre del Especialista: </h4>
                            <p id="referido-especialista"></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
