<?php if ($this->pageCount): ?>
    <div class="box-footer clearfix">
        <ul class="pagination pagination-sm no-margin pull-right">
            <li class="<?= !isset($this->previous) ? 'disabled' : ''; ?>">
                <a href="<?= $this->url('ordenamiento', array('action' => 'banner', 'page' => $this->first,
                    'order_by' => $order_by, 'order' => $order)); ?>">«</a>
            </li>
            <?php foreach ($this->pagesInRange as $page): ?>
                <li class="<?= $page == $this->current ? 'active' : ''; ?>">
                    <a href="<?= $this->url('ordenamiento', array('action' => 'banner', 'page' => $page,
                        'order_by' => $order_by, 'order' => $order)); ?>"><?= $page; ?></a>
                </li>
            <?php endforeach; ?>
            <li class="<?= !isset($this->next) ? 'disabled' : ''; ?>">
                <a href="<?= $this->url('ordenamiento', array('action' => 'banner', 'page' => $this->last,
                    'order_by' => $order_by, 'order' => $order)); ?>">»</a>
            </li>
        </ul>
    </div>
<?php endif; ?>