<!-- Modal Tebca-->
<div class="modal fade modal-vcenter modal-tebca" id="modalTebca" tabindex="-1" role="dialog" aria-labelledby="modalTebca">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><img src="<?=$this->basepath('img/login.png')?>"/></h4>
            </div>
            <div class="modal-body">
                <img src="<?=$this->basepath('img/LightBox_Tebca.png')?>" alt="" style="width: 100%">
            </div>
        </div>
    </div>
</div>
<!--Find el modal Tebca-->