<section>
    <div class="container">
        <div class="fluid-list bread">
            <ul>
                <li><a href="/home">Inicio</a></li>
                <li><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></li>
                <li>Tiendas</li>
            </ul>
        </div>
        <div class="fluid-list cnt-tienda-h">
            <h2>Tiendas afiliadas</h2>
            <?php
            $cont = 0;
            foreach ($data as $imagen) {
                if ($cont == 0) { ?>
                    <div class="row m-40">
                <?php }
                if ($cont <= 4) {
                    $cont++; ?>
                    <div class="col-md-3 center-img-h" style="overflow-y: hidden; height: 100px;">
                        <a href="/company/<?= $imagen['slug'] ?>">
                            <img src="<?= $rlogos . $imagen['logo'] ?>"/>
                        </a>
                    </div>
                <?php }
                if ($cont == 4) {
                    $cont = 0; ?>
                    </div>
                <?php }
            }
            ?>
        </div>
    </div>
</section>