<section class="content-header ">
    <br><br><br>
    <h1 class="box-title">Lista de Usuarios Finales</h1>
    <br><br>
    <?php if ($this->flashMessenger()->hasMessages()) {
        echo '<div class="callout alert alert-success"><button class="close" data-dismiss="alert" type="button">×</button>';
        $messages = $this->flashMessenger()->getMessages();
        foreach ($messages as $message) {
            echo $message;
        }
        echo '</div>';
    } ?>
</section>
<?php
function getAge($birthdate)
{
    $adjust = (date("md") >= date("md", strtotime($birthdate))) ? 0 : -1; // Si aún no hemos llegado al día y mes en este año restamos 1
    $years = date("Y") - date("Y", strtotime($birthdate)); // Calculamos el número de años
    return $years + $adjust; // Sumamos la diferencia de años más el ajuste
}

?>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form->setAttribute('action', $this->url('cliente', array('action' => 'index')))->prepare();
                        $form->setAttribute('id', 'searchform');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));
                        ?>
                        <div class="row">
                            <fieldset>
                                <legend>Buscar por:</legend>
                                <div class="form-group">
                                    <label class="col-md-2">Nombre o Apellidos o Número de documento: </label>
                                    <div class="col-md-3">
                                        <?= $this->formRow($form->get('cliente')); ?>
                                    </div>
                                    <div class="col-md-2"><label>Nombre Comercial o Razón Social o RUC: </label></div>
                                    <div class="col-md-5">
                                        <?= $this->formRow($form->get('empresa')); ?>
                                        <p><?= $nombre_empresa; ?></p>
                                    </div>
                                </div>
                                <div style="clear:both;"></div>
                                <br>
                                <div class="col-md-12 text-right">
                                    <?= $this->formSubmit($form->get('submit')); ?>
                                </div>
                            </fieldset>
                        </div>
                        <hr>
                        <?= $this->form()->closeTag(); ?>
                    </div>


                    <div class="dataTables_wrapper form-inline dt-bootstrap" id="example1_wrapper">
                        <div class="row-fluid">
                            <div class="col-md-12 text-right">
                                <div id="example1_length" class="dataTables_length"><br>
                                    <a href="<?= $this->url('cliente-load', array('action' => 'load')); ?>"
                                       class="btn btn-primary">Carga</a>
                                    <a href="<?= $this->url('cliente', array('action' => 'export', 'empresa' => $this->searchCompany)); ?>"
                                       class="btn btn-primary">Exportar</a>
                                </div>
                            </div>
                        </div>
                        <div style="clear:both;"></div>
                        <br>

                        <div class="row-fluid">
                            <div class="col-sm-12">
                                <table aria-describedby="example1_info" role="grid" id="example1"
                                       class="table table-bordered table-striped dataTable">
                                    <thead>
                                    <tr>
                                        <th>
                                            <a href="<?= $this->url(
                                                'cliente',
                                                array(
                                                    'order_by' => 'Nombre',
                                                    'order' => ($order_by == 'Nombre') ? $order : 'asc',
                                                    'cliente' => $client,
                                                    'empresa' => $searchCompany
                                                )
                                            ); ?>">Nombre</a>
                                        </th>
                                        <th>
                                            <a href="<?= $this->url(
                                                'cliente',
                                                array(
                                                    'order_by' => 'Apellido',
                                                    'order' => ($order_by == 'Apellido') ? $order : 'asc',
                                                    'cliente' => $client,
                                                    'empresa' => $searchCompany
                                                )
                                            ); ?>">Apellido</a>
                                        </th>
                                        <th>
                                            <a href="<?= $this->url(
                                                'cliente',
                                                array(
                                                    'order_by' => 'Genero',
                                                    'order' => ($order_by == 'Genero') ? $order : 'asc',
                                                    'cliente' => $client,
                                                    'empresa' => $searchCompany
                                                )
                                            ); ?>">Género</a>
                                        </th>
                                        <th>
                                            <a href="<?= $this->url(
                                                'cliente',
                                                array(
                                                    'order_by' => 'NumeroDocumento',
                                                    'order' => ($order_by == 'NumeroDocumento') ? $order : 'asc',
                                                    'cliente' => $client,
                                                    'empresa' => $searchCompany
                                                )
                                            ); ?>">Documento</a>
                                        </th>
                                        <th>
                                            <?php if ($this->identity()->BNF_TipoUsuario_id != 7) { ?>
                                                <a href="<?= $this->url(
                                                    'cliente',
                                                    array(
                                                        'order_by' => 'NombreComercial',
                                                        'order' => ($order_by == 'NombreComercial') ? $order : 'asc',
                                                        'cliente' => $client,
                                                        'empresa' => $searchCompany
                                                    )
                                                ); ?>">Empresa</a>
                                            <?php } else {
                                                echo "<a>Empresa</a>";
                                            } ?>
                                        </th>
                                        <th>
                                            <a href="<?= $this->url(
                                                'cliente',
                                                array(
                                                    'order_by' => 'NombreSegmento',
                                                    'order' => ($order_by == 'NombreSegmento') ? $order : 'asc',
                                                    'cliente' => $client,
                                                    'empresa' => $searchCompany
                                                )
                                            ); ?>">Segmento</a>
                                        </th>
                                        <th>
                                            <a href="<?= $this->url(
                                                'cliente',
                                                array(
                                                    'order_by' => 'NombreSubgrupo',
                                                    'order' => ($order_by == 'NombreSubgrupo') ? $order : 'asc',
                                                    'cliente' => $client,
                                                    'empresa' => $searchCompany
                                                )
                                            ); ?>">Subgrupo</a>
                                        </th>
                                        <th>Editar</th>
                                        <th>Activo</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php if (count($lista_clientes) > 0) { ?>
                                        <?php foreach ($lista_clientes as $cliente) { ?>
                                            <tr data-id="<?php echo $cliente["id"] ?>" role="row">
                                                <td><?= $this->escapeHtml($cliente["Nombre"]); ?></td>
                                                <td><?= $this->escapeHtml($cliente["Apellido"]); ?></td>
                                                <td>
                                                    <?php if ($cliente["Genero"] == 'H') {
                                                        echo "Masculino";
                                                    } elseif ($cliente["Genero"] == 'M') {
                                                        echo "Femenino";
                                                    } ?>
                                                </td>
                                                <td><?= $this->escapeHtml($cliente["NumeroDocumento"]); ?></td>
                                                <td><?= $this->escapeHtml($cliente["NombreComercial"]); ?></td>
                                                <td><?= $this->escapeHtml($cliente["NombreSegmento"]); ?></td>
                                                <td><?= $this->escapeHtml($cliente["NombreSubgrupo"]); ?></td>
                                                <td>
                                                    <a href="<?= $this->url('cliente', array('action' => 'edit', 'id' => $cliente["id"])); ?>"><i
                                                                class="btn btn-warning fa fa-pencil-square-o"></i></a>
                                                </td>
                                                <td>
                                                    <?php if ($cliente["Estado"] == 'Inactivo') { ?>
                                                        <input id="elim<?= $cliente["id"] ?>"
                                                               name="<?= $this->escapeHtml($cliente["Activo"]); ?>"
                                                               class="elim" type="checkbox" rel="<?= $cliente["id"] ?>"
                                                               company="<?= $cliente["idEmpresa"] ?>"/>
                                                    <?php } else { ?>
                                                        <input id="elim<?= $cliente["id"] ?>"
                                                               name="<?= $this->escapeHtml($cliente["Activo"]); ?>"
                                                               class="elim" type="checkbox" rel="<?= $cliente["id"] ?>"
                                                               company="<?= $cliente["idEmpresa"] ?>" checked/>
                                                    <?php } ?>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } else { ?>
                                        <tr>
                                            <td colspan="10">No hay clientes que mostrar</td>
                                        </tr>
                                    <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div><!-- /.box-body -->
                <div class="col-md-4"><br>
                    <?php if (!is_array($clientes)) { ?>
                        <?php if ($clientes->getTotalItemCount() == 0) { ?>
                            0 - 0 de 0 Registros
                        <?php } else { ?>
                            <p>
                                <?= (($clientes->getCurrentPageNumber() * $clientes->getItemCountPerPage()) -
                                    ($clientes->getItemCountPerPage() - 1)); ?>
                                -
                                <?= ($clientes->getCurrentPageNumber() * $clientes->getItemCountPerPage() <
                                    $clientes->getTotalItemCount())
                                    ? $clientes->getCurrentPageNumber() * $clientes->getItemCountPerPage()
                                    : $clientes->getTotalItemCount() ?> de
                                <?= $clientes->getTotalItemCount(); ?> Registros
                            </p>
                        <?php }
                    } ?>
                </div>
                <?php if (!is_array($clientes)) {
                    echo $this->paginationControl(
                        $clientes,
                        'Sliding',
                        'paginator-slide',
                        array(
                            'order_by' => $order_by,
                            'order' => ($order == "desc") ? 'asc' : 'desc',
                            'e' => $searchCompany,
                            'c' => $client
                        )
                    );
                } ?>
            </div>
        </div>
    </div>
</section>
<?php echo $this->headScript()
    ->prependFile($this->basePath('js/cliente/deleteclient.js?' . $this->configItem('version_script')));
?>
