<section class="content-header">
    <br><br><br>

    <h1 class="box-title">Cargar Codigos</h1>
    <br><br>
    <?php if (isset($mensaje) && $mensaje != null) {
        echo '<div class="callout alert alert-' . $type .
            '"><button class="close" data-dismiss="alert" type="button">×</button>';
        foreach ($mensaje as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</div>';
    }
    ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body">
                    <?php
                    $form->setAttribute('class', 'form-horizontal');
                    echo $this->form()->openTag($form);
                    echo $this->formElement($form->get('csrf'));
                    ?>
                    <div class="form-group">
                        <div class="col-md-2"><label>Plantilla de Carga de Codigos</label></div>
                        <div class="col-md-8">
                            <div class="row-fluid campo">
                                <div class="col-md-11 null-padding input-2">
                                    <a href="/files/CargarCodigos.xlsx" class="btn btn-primary">Descargar
                                        Plantilla</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="<?= $this->formElementErrors($form->get('Oferta')) ? 'has-error' : '' ?>">
                            <div class="col-md-2"><label>Ofertas:</label></div>
                            <div class="col-md-6">
                                <div class="row-fluid campo">
                                    <div class="col-md-11 null-padding">
                                        <?= $this->formRow($form->get('Oferta')); ?>
                                    </div>
                                    <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-2"><label>Archivo: *</label></div>
                        <div class="col-md-8">
                            <div class="row-fluid campo">
                                <div class="col-md-11 null-padding input-2">
                                    <?= $this->formRow($form->get('file_csv')); ?>
                                    <p class="help-block">Archivo de 2MB máx. formato xls o xlsx</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer line">
                        <?= $this->formSubmit($form->get('submit')); ?>
                        <a href="<?= $this->url('cliente'); ?>" class="btn btn-default">Cancelar</a>
                    </div>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</section>
<?php $this->inlineScript()->prependFile($this->basePath('js/oferta/oferta_lead.js'));