<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <style>
        html {
            font-family: sans-serif;
        }

        table {
            width: 100%;
        }

        body {
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            font-size: 14px;
            line-height: 1.42857143;
            color: #333
        }

        h1, h2, h3, h4, h5, h6 {
            font-family: inherit;
            font-weight: 500;
            line-height: 1.1;
            color: inherit
        }

        .table > thead > tr > th {
            vertical-align: bottom;
            border-bottom: 2px solid #ddd
        }

        .table > caption + thead > tr:first-child > td, .table > caption + thead > tr:first-child > th, .table > colgroup + thead > tr:first-child > td, .table > colgroup + thead > tr:first-child > th, .table > thead:first-child > tr:first-child > td, .table > thead:first-child > tr:first-child > th {
            border-top: 0
        }

        .table > tbody + tbody {
            border-top: 2px solid #ddd
        }

        .table .table {
            background-color: #fff
        }

        .table-striped > tbody > tr:nth-of-type(odd) {
            background-color: #f9f9f9
        }

        .table-hover > tbody > tr:hover, .table > tbody > tr.active > td, .table > tbody > tr.active > th, .table > tbody > tr > td.active, .table > tbody > tr > th.active, .table > tfoot > tr.active > td, .table > tfoot > tr.active > th, .table > tfoot > tr > td.active, .table > tfoot > tr > th.active, .table > thead > tr.active > td, .table > thead > tr.active > th, .table > thead > tr > td.active, .table > thead > tr > th.active {
            background-color: #f5f5f5
        }

        .table-hover > tbody > tr.active:hover > td, .table-hover > tbody > tr.active:hover > th, .table-hover > tbody > tr:hover > .active, .table-hover > tbody > tr > td.active:hover, .table-hover > tbody > tr > th.active:hover {
            background-color: #e8e8e8
        }

        .table > tbody > tr.success > td, .table > tbody > tr.success > th, .table > tbody > tr > td.success, .table > tbody > tr > th.success, .table > tfoot > tr.success > td, .table > tfoot > tr.success > th, .table > tfoot > tr > td.success, .table > tfoot > tr > th.success, .table > thead > tr.success > td, .table > thead > tr.success > th, .table > thead > tr > td.success, .table > thead > tr > th.success {
            background-color: #dff0d8
        }

        .table-hover > tbody > tr.success:hover > td, .table-hover > tbody > tr.success:hover > th, .table-hover > tbody > tr:hover > .success, .table-hover > tbody > tr > td.success:hover, .table-hover > tbody > tr > th.success:hover {
            background-color: #d0e9c6
        }

        .table > tbody > tr.info > td, .table > tbody > tr.info > th, .table > tbody > tr > td.info, .table > tbody > tr > th.info, .table > tfoot > tr.info > td, .table > tfoot > tr.info > th, .table > tfoot > tr > td.info, .table > tfoot > tr > th.info, .table > thead > tr.info > td, .table > thead > tr.info > th, .table > thead > tr > td.info, .table > thead > tr > th.info {
            background-color: #d9edf7
        }

        .table-hover > tbody > tr.info:hover > td, .table-hover > tbody > tr.info:hover > th, .table-hover > tbody > tr:hover > .info, .table-hover > tbody > tr > td.info:hover, .table-hover > tbody > tr > th.info:hover {
            background-color: #c4e3f3
        }

        .table > tbody > tr.warning > td, .table > tbody > tr.warning > th, .table > tbody > tr > td.warning, .table > tbody > tr > th.warning, .table > tfoot > tr.warning > td, .table > tfoot > tr.warning > th, .table > tfoot > tr > td.warning, .table > tfoot > tr > th.warning, .table > thead > tr.warning > td, .table > thead > tr.warning > th, .table > thead > tr > td.warning, .table > thead > tr > th.warning {
            background-color: #fcf8e3
        }

        .table-hover > tbody > tr.warning:hover > td, .table-hover > tbody > tr.warning:hover > th, .table-hover > tbody > tr:hover > .warning, .table-hover > tbody > tr > td.warning:hover, .table-hover > tbody > tr > th.warning:hover {
            background-color: #faf2cc
        }

        .table > tbody > tr.danger > td, .table > tbody > tr.danger > th, .table > tbody > tr > td.danger, .table > tbody > tr > th.danger, .table > tfoot > tr.danger > td, .table > tfoot > tr.danger > th, .table > tfoot > tr > td.danger, .table > tfoot > tr > th.danger, .table > thead > tr.danger > td, .table > thead > tr.danger > th, .table > thead > tr > td.danger, .table > thead > tr > th.danger {
            background-color: #f2dede
        }

        .table-hover > tbody > tr.danger:hover > td, .table-hover > tbody > tr.danger:hover > th, .table-hover > tbody > tr:hover > .danger, .table-hover > tbody > tr > td.danger:hover, .table-hover > tbody > tr > th.danger:hover {
            background-color: #ebcccc
        }


    </style>
    <style>
        .fluid-list {
            display: inline-block;
            width: 100%
        }

        .right {
            float: right
        }

        .left {
            float: left
        }

        #flyout h4, #flyout p, .menu-user-d.menu-city .dropdown-menu li a {
            color: #0a0d12
        }

        .cnt-num-puntos li {
            width: 100%;
            display: inline-block;
            vertical-align: top;
            margin-top: 8px
        }

        .cnt-num-puntos li:first-child {
            margin-top: 0
        }

        .cnt-num-puntos .label-p {
            font-size: 20px;
            color: #0a0d12
        }

        .cnt-num-puntos .num-p {
            font-size: 22px;
            color: #0a0d12
        }

        .cnt-num-puntos .num-p input {
            width: 130px;
            text-align: right;
            font-size: 22px
        }

        .total-puntos-u .label-p {
            font-family: centurygothicbold, arial;
            font-size: 22px
        }

        .total-puntos-u .num-p {
            font-family: centurygothicbold, arial;
            font-size: 24px
        }

        .cnt-content-user {
            margin: 20px 0 50px
        }

        .cnt-content-user h3 {
            font-size: 24px;
            color: #0a0d12;
            margin-top: 0;
            margin-bottom: 30px
        }

        .cnt-content-user h3 span {
            font-family: centurygothicbold, arial
        }

        .color: #000

        }

        .cnt-mis-datos label {
            text-align: left !important;
            font-size: 20px;
            color: #0a0d12;
            padding-top: 0 !important
        }

        .cnt-mis-datos .btn-user-m {
            height: 50px;
            background: #3db123;
            border-bottom: 3px solid #12330a;
            text-shadow: 0 0 0;
            color: #fff;
            font-size: 20px;
            padding: 0 35px
        }

        .puntos-u ul li em, .puntos-u ul li span {
            font-size: 16px;
            color: #0a0d12
        }

        .puntos-u {
            background: #eee;
            margin-bottom: 20px
        }

        .puntos-u ul {
            list-style: none;
            padding-left: 0;
            margin-bottom: 0
        }

        .puntos-u ul li {
            width: 100%;
            padding: 2px 0
        }

        .puntos-u ul li em {
            font-family: centurygothicbold, arial;
            font-style: normal
        }

        .puntos-u ul li.p-dispo em, .puntos-u ul li.p-dispo span {
            font-size: 20px
        }

        .cnt-puntos-o p a {
            color: #0a0d12;
            font-size: 12px;
            font-family: centurygothicbold, arial
        }

        .p-vig a, .pagination-t ul li a {
            font-family: centurygothicbold, arial;
            text-decoration: underline;
            display: block
        }

        .cnt-table-user {
            font-size: 16px;
            color: #0a0d12
        }

        .text-left-u {
            text-align: right
        }

        .p-asig {
            color: #3db123;
            font-family: centurygothicbold, arial
        }

        .p-usados {
            font-family: centurygothicbold, arial;
            color: #fe0000
        }

        .p-saldo {
            font-family: centurygothicbold, arial;
            color: #000
        }

        .cnt-table-user .table > tbody > tr > td {
            border-top: 0
        }

        .footer-t {
            border-top: 1px solid #ddd;
            font-size: 20px;
            padding: 12px 0
        }

        .footer-t em {
            font-style: normal;
            font-family: centurygothicbold, arial;
            color: #0a0d12
        }

    </style>
</head>
<body class="main-puntos">
<div id="main-container" class="wrapper">
    <section>
        <div class="container">
            <div class="fluid-list cnt-content-user">
                <div class="row">
                    <div class="col-md-12">
                        <div class="fluid-list cnt-mis-datos">
                            <h3>Cupones Vigentes</h3>
                            <div class="fluid-list cnt-table-user cnt-user-descargado">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Descripción</th>
                                        <th>Fecha de Descarga</th>
                                        <th>Fecha de Expiración</th>
                                        <th>Puntos Usados</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($this->data as $value) { ?>
                                        <tr>
                                            <td class="p-vig">
                                                <?php if ($value->PrecioVentaPublico) { ?>
                                                    <b>S/. <?= $value->PrecioVentaPublico ?> por </b>
                                                <?php } ?>
                                                <?= $value->TituloCorto ?>
                                            </td>
                                            <td><?= date('d/m/Y', strtotime($value->FechaGenerado)) ?></td>
                                            <td><?= date('d/m/Y', strtotime($value->FechaVigencia)) ?></td>
                                            <td class="p-saldo"><?= $value->PuntosUtilizados ?></td>
                                        </tr>
                                    <?php } ?>
                                    </tbody>
                                </table>
                                <?php
                                if (isset($this->vigentes)) {
                                    echo $this->paginationControl(
                                        $this->vigentes,
                                        'Sliding',
                                        'paginator-vigentes'
                                    );
                                } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
</body>
</html>