<section class="wrapper-main">
    <script type="text/css">
        .left-info-c ul li {
            text-align: center;
        }

        a {
            text-decoration: underline;
        }
    </script>
    <div class="fluid-list cnt-content-user">
        <h3>Bienvenid@ <span><?= $this->identity()["Nombre"] . ' ' . $this->identity()["Apellido"] ?></span></h3>
        <div class="fluid-list cnt-mis-datos">
            <h3>Cupones Vigentes</h3>
            <div class="fluid-list cnt-puntos-o">
                <p><a href="<?= $this->url('perfil-puntos', array('action' => 'pdfVigentes')); ?>">
                        <span></span> Descargar Listado de Cupones Vigentes (PDF)</a></p>
            </div>
            <div class="fluid-list list-table-user">
                <div class="fluid-list list-items">
                    <?php foreach ($this->vigentes as $value) { ?>
                        <h4>
                            <a style="color: black"
                               href="<?= $this->basePath('elements/' . $value->CodigoCupon . '.pdf') ?>"
                               download="<?= 'beneficios_' . $value->Empresa . '_' . $value->id . '.pdf' ?>">
                                <?php if ($value->PrecioVentaPublico) { ?>
                                    <b>S/. <?= $value->PrecioVentaPublico ?> por </b>
                                <?php } ?>
                                <?= $value->TituloCorto ?>
                            </a>
                        </h4>
                        <ul class="item-name-i">
                            <li>
                                <ul>
                                    <li>
                                        <span class="left">
                                            Descargado el: <?= date('d/m/Y', strtotime($value->FechaGenerado)) ?>
                                        </span>
                                    </li>
                                    <li>
                                        <span class="left">
                                            Vigencia hasta el: <?= date('d/m/Y', strtotime($value->FechaVigencia)) ?>
                                        </span>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <ul>
                                    <li>
                                        <span class="left">Puntos utilizados:</span>
                                        <em class="right"><?= $value->PuntosUtilizados ?></em>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    <?php } ?>
                </div>
                <?php
                if (isset($this->vigentes)) {
                    echo $this->paginationControl(
                        $this->vigentes,
                        'Sliding',
                        'paginator-vigentes',
                        array('mobile' => $this->mobile)
                    );
                } ?>
            </div>
        </div>
    </div>
</section>