<!-- Modal Fin De proceso-->
<div class="modal fade modal-vcenter modal-error" id="modalErrorPremios" tabindex="-1" role="dialog" aria-labelledby="modalErrorPremios">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><img src="http://beneficios.pe/img/login.png" /></h4>
            </div>
            <div class="modal-body">
                <div class="fluid-list header-modal-c header-feli">
                    <h3>LO SENTIMOS</h3>
                    <p>Superó la descargas permitidas del día</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Find el modal Fin de Proceso-->