<!-- Modal Felicitaciones-->
<div class="modal fade modal-vcenter modal-felicitaciones" id="modalFelicitacionesPremios" tabindex="-1" role="dialog" aria-labelledby="modalFelicitacionesPremios">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><img src="http://beneficios.pe/img/login.png"/></h4>
            </div>
            <div class="modal-body">
                <div class="fluid-list header-modal-c header-feli">
                    <h3>FELICITACIONES</h3>
                    <p><?= $this->conf['mensajeproceso'] ?></p>
                </div>
                <div class="fluid-list body-cnt-c questions">
                    <h4>¡Ayudanos a mejorar tu experiencia!</h4>
                    <h5></h5>
                    <form action="" class="form-login form-modal-c" id="formRespuesta" novalidate="novalidate">
                        <input type="hidden" id="question_number" value="">
                        <div class="form-group cnt-form-error preguntas"></div>
                        <div class="form-group">
                            <ul>
                                <li class="first-btn">
                                    <button type="submit" class="btn btn-primary btn-block text-center">
                                        <span>Enviar respuesta</span>
                                    </button>
                                </li>
                                <li class="second-btn">
                                    <a href="#" class="btn btn-primary btn-block text-center btn-no"
                                       data-dismiss="modal" aria-label="Close"><span>No, Gracias</span></a>
                                </li>
                            </ul>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Find el modal Felicitaciones-->