<!-- Modal Fin De proceso-->
<div class="modal fade modal-vcenter modal-gracias" id="modalGracias" tabindex="-1" role="dialog" aria-labelledby="modalGracias">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><img src="<?=$this->basepath('img/login.png')?>"/></h4>
            </div>
            <div class="modal-body">
                <div class="fluid-list header-modal-c header-feli">
                    <h3>FELICITACIONES</h3>
                    <p>Con estos datos trabajaremos para que disfrutes de una mejor experiencia.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Find el modal Fin de Proceso-->