<section class="content-header ">
    <br><br><br>

    <h1 class="box-title">Lista de Empresas</h1>
    <br><br>
    <?php if ($this->flashMessenger()->hasMessages()) {
        echo '<div class="callout alert alert-success"><button class="close" data-dismiss="alert" type="button">×</button>';
        $messages = $this->flashMessenger()->getMessages();
        foreach ($messages as $message) {
            echo $message;
        }
        echo '</div>';
    } ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form->setAttribute('action', $this->url('empresa', array('action' => 'index')));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));

                        ?>
                        <div class="row">
                            <fieldset>
                                <legend>Buscar por:</legend>
                                <div class="form-group">
                                    <label class="col-md-2">Nombre Comercial o Razón Social</label>

                                    <div class="col-md-5">
                                        <?php
                                        echo $this->formRow($form->get('RazonSocial'));
                                        ?>
                                    </div>
                                    <div class="col-md-1"><label>RUC:</label></div>
                                    <div class="col-md-4">
                                        <?php
                                        echo $this->formRow($form->get('Ruc'));
                                        ?>
                                    </div>
                                </div>
                                <div style="clear:both;"></div>
                                <br>

                                <div class="col-md-12 text-right">
                                    <?php
                                    echo $this->formSubmit($form->get('submit'));
                                    ?>
                                </div>
                            </fieldset>
                        </div>
                        <hr>
                        <?php
                        echo $this->form()->closeTag();
                        ?>
                    </div>

                    <div class="dataTables_wrapper form-inline dt-bootstrap" id="example1_wrapper">
                        <div class="row-fluid">
                            <div class="col-md-12 text-right">
                                <div id="example1_length" class="dataTables_length"><br>
                                    <a href="<?php echo $this->url('empresa', array('action' => 'export')); ?>"
                                       class="btn btn-primary">Exportar</a>
                                </div>
                            </div>
                        </div>
                        <div style="clear:both;"></div>
                        <br>

                        <div class="row-fluid">
                            <div class="col-sm-12">
                                <table aria-describedby="example1_info" role="grid" id="example1"
                                       class="table table-bordered table-striped dataTable">
                                    <thead>
                                    <tr>
                                        <th>
                                            <?php if ($order_by == 'Tipo'): ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'Tipo', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Tipo
                                                    de Empresa</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'Tipo', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Tipo
                                                    de Empresa</a>
                                            <?php endif; ?>
                                        </th>
                                        <th class="nomcemp">
                                            <?php if ($order_by == 'NComercial'): ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'NComercial', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Nombre
                                                    Comercial</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'NComercial', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Nombre
                                                    Comercial</a>
                                            <?php endif; ?>
                                        </th>
                                        <th class="razemp">
                                            <?php if ($order_by == 'Razon'): ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'Razon', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Razón
                                                    Social</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'Razon', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Razón
                                                    Social</a>
                                            <?php endif; ?>
                                        </th>
                                        <th class="peremp">
                                            <?php if ($order_by == 'APaterno'): ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'APaterno', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Ape
                                                    Paterno</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'APaterno', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Ape
                                                    Paterno</a>
                                            <?php endif; ?>
                                        </th>
                                        <th class="peremp">
                                            <?php if ($order_by == 'AMaterno'): ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'AMaterno', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Ape
                                                    Materno</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'AMaterno', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Ape
                                                    Materno</a>
                                            <?php endif; ?>
                                        </th>
                                        <th class="peremp">
                                            <?php if ($order_by == 'Empresa'): ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'Empresa', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Nombre</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'Empresa', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Nombre</a>
                                            <?php endif; ?>
                                        </th>
                                        <th>
                                            <?php if ($order_by == 'Ruc'): ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'Ruc', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Ruc</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'Ruc', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Ruc</a>
                                            <?php endif; ?>
                                        </th>
                                        <th>
                                            <?php if ($order_by == 'Clase'): ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'Clase', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Clase</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'Clase', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Clase</a>
                                            <?php endif; ?>
                                        </th>
                                        <th><a>Editar</a></th>
                                        <th>
                                            <?php if ($order_by == 'Activo'): ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'Activo', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Activo</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('empresa', array('order_by' => 'Activo', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Activo</a>
                                            <?php endif; ?>
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php if (count($empresas) > 0) {
                                        foreach ($empresas as $dato) : ?>
                                            <tr data-id="<?php echo $dato->id ?>"
                                                data-tipo="<?php echo $dato->NombreTipoEmpresa ?>">
                                                <td><?php echo $this->escapeHtml($dato->NombreTipoEmpresa); ?></td>
                                                <td class="nomcemp"><?php echo $this->escapeHtml($dato->NombreComercial); ?></td>
                                                <td class="razemp"><?php echo $this->escapeHtml($dato->RazonSocial); ?></td>
                                                <td class="peremp"><?php echo $this->escapeHtml($dato->ApellidoPaterno); ?></td>
                                                <td class="peremp"><?php echo $this->escapeHtml($dato->ApellidoMaterno); ?></td>
                                                <td class="peremp"><?php echo $this->escapeHtml($dato->Nombre); ?></td>
                                                <td><?php echo $this->escapeHtml($dato->Ruc); ?></td>
                                                <?php if ($dato->NombreTipoEmpresa == "Cliente"): ?>
                                                    <td><?php echo $this->escapeHtml($dato->ClaseEmpresaCliente); ?></td>
                                                <?php else: ?>
                                                    <td></td>
                                                <?php endif; ?>

                                                <td>
                                                    <a href="<?php echo $this->url('empresa', array('action' => 'edit', 'id' => $dato->id)); ?>">
                                                        <i class="btn btn-warning fa fa-pencil-square-o"></i></a>
                                                </td>
                                                <td>
                                                    <?php if ($dato->TEliminado == 1): ?>
                                                        <input
                                                            id="elim<?php echo $dato->id . $dato->NombreTipoEmpresa ?>"
                                                            name="<?php echo (int)$dato->TEliminado ?>"
                                                            class="elim" type="checkbox">
                                                    <?php else: ?>
                                                        <input
                                                            id="elim<?php echo $dato->id . $dato->NombreTipoEmpresa ?>"
                                                            name="<?php echo (int)$dato->TEliminado ?>"
                                                            class="elim" type="checkbox" checked>
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach;
                                    } else {
                                        echo '<tr><td colspan="10">No hay Empresas Registradas</td></tr>';
                                    } ?>
                                    </tbody>
                                </table>
                                <div class="col-md-4"><br>

                                    <p>
                                        <?php if (count($empresas) > 0): ?>
                                            <?= (($empresas->getCurrentPageNumber() * $empresas->getItemCountPerPage()) -
                                                ($empresas->getItemCountPerPage() - 1)); ?>
                                            -
                                            <?= ($empresas->getCurrentPageNumber() * $empresas->getItemCountPerPage() <
                                                $empresas->getTotalItemCount())
                                                ? $empresas->getCurrentPageNumber() * $empresas->getItemCountPerPage()
                                                : $empresas->getTotalItemCount() ?> de
                                            <?= $empresas->getTotalItemCount(); ?> Registros
                                        <?php endif; ?>
                                    </p>
                                </div>
                                <?php
                                if (isset($empresas)):
                                    echo $this->paginationControl($empresas, 'Sliding', 'paginator-empresa', array('order_by' => $order_by, 'order' => ($order == 'asc') ? $order = 'desc' : 'asc', 'q1' => $q1, 'q2' => $q2));
                                endif;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
echo $this->inlineScript()->appendFile(
    $this->basePath('js/empresa/empresa.js?' . $this->configItem('version_script'))
);