<section class="content-header ">
    <br><br><br>

    <h1 class="box-title">Asignación de Ordenamiento</h1>
    <br><br>
    <?php if (isset($msg)) {
        echo '<div class="callout alert alert-' . $this->alert .
            '"><button class="close" data-dismiss="alert" type="button">×</button>';
        foreach ($msg as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</div>';
    } ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form = $this->form;
                        $form->setAttribute('action', $this->url('ordenamiento', array('action' => 'assign')));
                        $form->setAttribute('class', 'form-horizontal');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));
                        ?>
                        <div class="row">
                            <div class="col-md-12">
                                <fieldset>
                                    <div class="form-group">
                                        <div class="col-md-2"><label>Nombre Comercial o Razón Social o RUC: </label>
                                        </div>
                                        <div class="col-md-5">
                                            <?= $this->formRow($form->get('empresa')); ?>
                                            <p><?= $this->nombre_empresa; ?></p>
                                        </div>
                                    </div>
                                    <legend>Plantillas</legend>
                                    <div class="form-group campo">
                                        <div class="col-md-2">
                                            <label><input name="type" value="categoria" id="radio-categoria"
                                                          checked="checked" type="radio">Categoría</label>
                                        </div>
                                        <div class="col-md-2">
                                            <div class="<?= (isset($errors['repeatc'])) ? $errors['repeatc'] : ''; ?>
                                            <?= $this->formElementErrors($form->get('BNF_Categoria_id'))
                                                ? 'has-error' : '' ?>">
                                                <div class="col-md-11 null-padding input">
                                                    <?php
                                                    echo $this->formHidden($form->get('id'));
                                                    echo $this->formRow($form->get('BNF_Categoria_id'));
                                                    ?>
                                                    <?= (isset($errors['repeat'])) ? '<ul><li>' .
                                                        $errors['repeat'] . '</li></ul>' : ''; ?>
                                                </div>
                                                <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                            </div>
                                        </div>
                                        <div class="col-md-2">
                                            <label><input name="type" value="campania" id="radio-campania"
                                                          type="radio">Campaña</label>
                                        </div>
                                        <div class="col-md-2">
                                            <div class="<?= (isset($errors['repeatc'])) ? $errors['repeatc'] : ''; ?>
                                            <?= $this->formElementErrors($form->get('BNF_Campanias_id'))
                                                ? 'has-error' : '' ?>">
                                                <div class="col-md-11 null-padding input">
                                                    <?php
                                                    echo $this->formRow($form->get('BNF_Campanias_id'));
                                                    ?>
                                                    <?= (isset($errors['repeat'])) ? '<ul><li>' .
                                                        $errors['repeat'] . '</li></ul>' : ''; ?>
                                                </div>
                                                <div class="col-md-1 null-padding text-center p">
                                                    <p>*</p></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group campo">
                                        <div class="col-md-2">
                                            <label><input name="type" value="tienda" id="radio-tienda" type="radio">Tienda</label>
                                        </div>
                                        <div class="col-md-2">
                                            <label><input name="type" value="puntos" id="radio-puntos" type="radio">Puntos</label>
                                        </div>
                                        <div class="col-md-2">
                                            <label><input name="type" value="premios" id="radio-premios" type="radio">Premios</label>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-4">
                                <fieldset>
                                    <legend>Ordenamiento</legend>
                                </fieldset>
                            </div>
                            <div class="col-md-8">
                                <fieldset>
                                    <legend>Posicionamiento de Ofertas</legend>
                                </fieldset>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <div class="<?= (isset($errors['repeatc'])) ? $errors['repeatc'] : ''; ?>
                                    <?= $this->formElementErrors($form->get('Fila_1')) ? 'has-error' : '' ?>">
                                        <div class="col-md-4"><label>Fila 1:</label></div>
                                        <div class="col-md-8">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <?php echo $this->formRow($form->get('Fila_1')); ?>
                                                    <?= (isset($errors['repeat'])) ? '<ul><li>' .
                                                        $errors['repeat'] . '</li></ul>' : ''; ?>
                                                </div>
                                                <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group div-pos-offer pos-offer-1">
                                    <div class="col-md-4"><?php echo $this->formRow($form->get('Fila_1_1')); ?></div>
                                    <div class="col-md-4"><?php echo $this->formRow($form->get('Fila_1_2')); ?></div>
                                    <div class="col-md-4"><?php echo $this->formRow($form->get('Fila_1_3')); ?></div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <div class="<?= (isset($errors['repeatc'])) ? $errors['repeatc'] : ''; ?>
                                    <?= $this->formElementErrors($form->get('Fila_2')) ? 'has-error' : '' ?>">
                                        <div class="col-md-4"><label>Fila 2:</label></div>
                                        <div class="col-md-8">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <?php echo $this->formRow($form->get('Fila_2')); ?>
                                                    <?= (isset($errors['repeat'])) ? '<ul><li>' .
                                                        $errors['repeat'] . '</li></ul>' : ''; ?>
                                                </div>
                                                <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group div-pos-offer pos-offer-2">
                                    <div class="col-md-4"><?php echo $this->formRow($form->get('Fila_2_1')); ?></div>
                                    <div class="col-md-4"><?php echo $this->formRow($form->get('Fila_2_2')); ?></div>
                                    <div class="col-md-4"><?php echo $this->formRow($form->get('Fila_2_3')); ?></div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <div class="<?= (isset($errors['repeatc'])) ? $errors['repeatc'] : ''; ?>
                                <?= $this->formElementErrors($form->get('Fila_3')) ? 'has-error' : '' ?>">
                                        <div class="col-md-4"><label>Fila 3:</label></div>
                                        <div class="col-md-8">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <?php echo $this->formRow($form->get('Fila_3')); ?>
                                                    <?= (isset($errors['repeat'])) ? '<ul><li>' .
                                                        $errors['repeat'] . '</li></ul>' : ''; ?>
                                                </div>
                                                <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group div-pos-offer pos-offer-3">
                                    <div class="col-md-4"><?php echo $this->formRow($form->get('Fila_3_1')); ?></div>
                                    <div class="col-md-4"><?php echo $this->formRow($form->get('Fila_3_2')); ?></div>
                                    <div class="col-md-4"><?php echo $this->formRow($form->get('Fila_3_3')); ?></div>
                                </div>
                            </div>
                        </div>
                        <div class="alert alert-warning alert-dismissable" style="display: none">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <h4><i class="icon fa fa-warning"></i> Alerta!</h4>
                            La Oferta ya esta Seleccionada.
                        </div>
                        <br>
                        <div class="form-group">
                            <div class="col-md-offset-10 col-md-2">
                                <p>(*) Campos Obligatorios</p>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="col-md-10">
                                <?php echo $this->formSubmit($form->get('submit')); ?>
                                <a href="/ordenamiento" class="btn btn-default">Cancelar</a>
                            </div>
                        </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
echo $this->render('_script_assign.php');
$this->inlineScript()
    ->prependFile($this->basePath('js/ordenamiento/ordenamiento_add.js?' . $this->configItem('version_script')));
$opcion = !empty($this->opcion) ? $this->opcion : "";
$ofertas = $this->ofertas;
?>
<script>
    $(function () {
        var listaOfertas = [];
        <?php if ($opcion != null) : ?>
            <?php foreach ($ofertas as $index => $data) : ?>
                listaOfertas['<?= $index;?>'] = [];
                <?php foreach ($data as $key => $dato) : ?>
                    listaOfertas['<?= $index;?>']['<?= $key;?>'] = '<?= $dato;?>';
                <?php endforeach; ?>
            <?php endforeach; ?>
            llenarData('<?= $opcion;?>', listaOfertas);
        <?php else : ?>
            init();
        <?php endif; ?>
    });
</script>

