<section class="content-header ">
    <br><br><br>

    <h1 class="box-title">Asignación de Ordenamiento</h1>
    <br><br>
    <?php if (isset($msg)) {
        echo '<div class="callout alert alert-' . $alert . '"><button class="close" data-dismiss="alert" type="button">×</button>';
        foreach ($msg as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</div>';
    } ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form->setAttribute('action', $this->url('ordenamiento', array('action' => 'assign')));
                        $form->setAttribute('class', 'form-horizontal');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));

                        ?>
                        <div class="form-group">
                            <div class="col-md-2 col-md-offset-2 col-xs-2 radio-lista">
                                <?= $this->formRow($form->get('type')); ?>
                            </div>
                            <div class="col-md-4 col-xs-4">
                                <div class="row-fluid campo">
                                    <!-- -->
                                    <dic
                                        class="<?= (isset($errors['repeatc'])) ? $errors['repeatc'] : ''; ?> <?= $this->formElementErrors($form->get('BNF_Categoria_id')) ? 'has-error' : '' ?>">
                                        <div
                                            class="col-md-11 null-padding input">
                                            <?php
                                            echo $this->formHidden($form->get('id'));
                                            echo $this->formRow($form->get('BNF_Categoria_id'));
                                            ?>
                                            <?= (isset($errors['repeat'])) ? '<ul><li>' . $errors['repeat'] . '</li></ul>' : ''; ?>
                                        </div>
                                        <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                    </dic>
                                    <!-- -->

                                    <div class="row-fluid" style="position: absolute; margin-top: 75px; width:93%">
                                        <div
                                            class="<?= (isset($errors['repeatc'])) ? $errors['repeatc'] : ''; ?> <?= $this->formElementErrors($form->get('BNF_Campanias_id')) ? 'has-error' : '' ?>">
                                            <div class="col-md-11 null-padding input">
                                                <?php
                                                echo $this->formRow($form->get('BNF_Campanias_id'));
                                                ?>
                                                <?= (isset($errors['repeat'])) ? '<ul><li>' . $errors['repeat'] . '</li></ul>' : ''; ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p">
                                                <p>*</p></div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 col-md-offset-5">
                                <h2>Plantillas</h2>
                            </div>
                        </div>
                        <div class="form-group">
                            <div
                                class="<?= (isset($errors['repeatc'])) ? $errors['repeatc'] : ''; ?> <?= $this->formElementErrors($form->get('Fila_1')) ? 'has-error' : '' ?>">
                                <div class="col-md-2 col-md-offset-2"><label>Fila 1:</label></div>
                                <div class="col-md-4">
                                    <div class="row-fluid campo">
                                        <div class="col-md-11 null-padding input">
                                            <?php
                                            echo $this->formRow($form->get('Fila_1'));
                                            ?>
                                            <?= (isset($errors['repeat'])) ? '<ul><li>' . $errors['repeat'] . '</li></ul>' : ''; ?>
                                        </div>
                                        <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div
                                class="<?= (isset($errors['repeatc'])) ? $errors['repeatc'] : ''; ?> <?= $this->formElementErrors($form->get('Fila_2')) ? 'has-error' : '' ?>">
                                <div class="col-md-2 col-md-offset-2"><label>Fila 2:</label></div>
                                <div class="col-md-4">
                                    <div class="row-fluid campo">
                                        <div class="col-md-11 null-padding input">
                                            <?php
                                            echo $this->formRow($form->get('Fila_2'));
                                            ?>
                                            <?= (isset($errors['repeat'])) ? '<ul><li>' . $errors['repeat'] . '</li></ul>' : ''; ?>
                                        </div>
                                        <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div
                                class="<?= (isset($errors['repeatc'])) ? $errors['repeatc'] : ''; ?> <?= $this->formElementErrors($form->get('Fila_3')) ? 'has-error' : '' ?>">
                                <div class="col-md-2 col-md-offset-2"><label>Fila 3:</label></div>
                                <div class="col-md-4">
                                    <div class="row-fluid campo">
                                        <div class="col-md-11 null-padding input">
                                            <?php
                                            echo $this->formRow($form->get('Fila_3'));
                                            ?>
                                            <?= (isset($errors['repeat'])) ? '<ul><li>' . $errors['repeat'] . '</li></ul>' : ''; ?>
                                        </div>
                                        <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-10 col-md-2">
                                <p>(*) Campos Obligatorios</p>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="col-md-10">
                                <?php echo $this->formSubmit($form->get('submit')); ?>
                                <a href="/ordenamiento" class="btn btn-default">Cancelar</a>
                            </div>
                        </div>
                        <hr>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script type="text/javascript"
        src="<?= $this->basePath('js/ordenamiento/ordenamiento_add.js?' . $this->configItem('version_script')); ?>"></script>
<?php include('_script_assign.php'); ?>