<?php use Application\Service\MobileDetect;

$category = $this->category;
$total = $this->total;
$tamaño = $this->tamaño;
?>
    <div class="fluid-list destacados-cnt title-bloques">
        <?php
        if (false/*count($this->ofertas_premiun) != 0*/) { ?>
            <h3 class="hidden-xs">Beneficios Destacados</h3>
            <?php
        }
        foreach ($this->ofertas_premiun as $fila) { ?>
            <!-- row 1 -->
            <?php if ($fila['tipo'] == 1) { ?>
                <?php if (!empty($fila['ofertas'])) : ?>
                    <div class="fluid-list margin-b two-primary">
                        <?php foreach ($fila['ofertas'] as $oferta) { ?>
                            <div class="row">
                                <div class="col-md-6 cupon-img cupon-two">
                                    <figure>
                                        <a href="/<?= $category ?>/coupon-puntos/<?= $oferta->Slug ?>">
                                            <img src="<?php
                                            $partes = explode(".", $oferta->ImagenOferta);
                                            $ext = end($partes);
                                            $imgOferta = str_replace('.' . $ext, '', $oferta->ImagenOferta) . '-medium.' . $ext;
                                            echo $this->rofertas . $imgOferta
                                            ?>" title="" style="display: inline"/>
                                            <div class="puntos-ico"></div>
                                        </a>
                                    </figure>
                                </div>
                                <div class="col-md-6">
                                    <div class="fluid-list cupon-info">
                                        <div class="fluid-list top-info">
                        <?php if ($this->identity()['flagcheckboxLogo']) { ?>
                                            <figure class="left">
                                                <a>
                                                    <img src="<?php
                                                    $partes = explode(".", $oferta->LogoEmpresa);
                                                    $ext = end($partes);
                                                    $logoempresa = str_replace('.' . $ext, '', $oferta->LogoEmpresa) . '-large.' . $ext;
                                                    echo $this->rlogos . $logoempresa;
                                                    ?>"/>
                                                </a>
                                            </figure>
                            <?php }?>
                                            <div class="left info-dest-c">
                                                <h2>
                                                    <a href="/<?= $category ?>/coupon-puntos/<?= $oferta->Slug ?>">
                                                        <?php if ($oferta->PrecioVentaPublico) {

                                                            if ($flagcheckboxMoney) {
                                                                ?>
                                                                <b><?= $oferta->PrecioVentaPublico ?> puntos por </b>
                                                            <?php } else { ?>
                                                                <b> S/. <?= $oferta->PrecioVentaPublico ?> por </b>
                                                            <?php }
                                                        } ?>
                                                        <?= $oferta->TituloCorto ?>
                                                    </a>
                                                </h2>
                                            </div>
                                        </div>
                                        <div class="fluid-list buttom-info">
                                            <hr>
                                            <?php if ($oferta->TipoPrecio != 'Split') {
                                                $date = new DateTime($oferta->FechaVigencia);
                                                $mes = $date->format('m'); ?>
                                                <span>Descarga este beneficio hasta el <span><?= ' ' . $date->format('d')
                                                        . ' de ' . $this->meses[$mes - 1] ?></span></span>
                                            <?php } ?>
                                            <a href="/<?= $category ?>/coupon-puntos/<?= $oferta->Slug ?>"
                                               class="right btn-cupon-d ver-b">VER CUPÓN</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                <?php endif; ?>
            <?php } ?>
            <!-- row 2 -->
            <?php if ($fila['tipo'] == 2) { ?>
                <?php if (!empty($fila['ofertas'])) : ?>
                    <div class="row margin-b">
                        <?php foreach ($fila['ofertas'] as $oferta) { ?>
                            <div class="col-md-6 margin-bottom-movil">
                                <div class="fluid-list cupon-two">
                                    <a href="/<?= $category ?>/coupon-puntos/<?= $oferta->Slug ?>">
                                        <figure>
                                            <img src="<?php
                                            $partes = explode(".", $oferta->ImagenOferta);
                                            $ext = end($partes);
                                            $imgOferta = str_replace('.' . $ext, '', $oferta->ImagenOferta) . '-medium.' . $ext;
                                            echo $this->rofertas . $imgOferta
                                            ?>" title=""/>
                                            <div class="puntos-ico"></div>
                                        </figure>
                                    </a>

                                    <div class="info-cupon-l">
                        <?php if ($this->identity()['flagcheckboxLogo']) { ?>
                                        <figure class="left">
                                            <a>
                                                <img src="<?php
                                                $partes = explode(".", $oferta->LogoEmpresa);
                                                $ext = end($partes);
                                                $logoempresa = str_replace('.' . $ext, '', $oferta->LogoEmpresa) . '-medium.' . $ext;
                                                echo $this->rlogos . $logoempresa;
                                                ?>"/>
                                            </a>
                                        </figure>
                            <?php }?>
                                        <div class="info-interna left">
                                            <h2>
                                                <a href="/<?= $category ?>/coupon-puntos/<?= $oferta->Slug ?>"
                                                   class="title-short-destacados">
                                                    <?php
                                                    $ismovil = new MobileDetect();
                                                    if ($ismovil->isMobile() == 2) {
                                                        $tamaño = 55;
                                                    } elseif ($ismovil->isMobile() == 0) {
                                                        $tamaño = 70;
                                                    }

                                                    if ($ismovil->isMobile() == 2) {
                                                        $tamaño = 75;
                                                    } elseif ($ismovil->isMobile() == 0) {
                                                        $tamaño = 90;
                                                    }

                                                    if (strlen($oferta->TituloCorto) >= $tamaño) {
                                                        if ($oferta->PrecioVentaPublico){
                                                            if ($flagcheckboxMoney) {
                                                                echo '<b>'.$oferta->PrecioVentaPublico.' puntos por </b>';
                                                             } else {
                                                                echo '<b> S/'.$oferta->PrecioVentaPublico.' por </b>';
                                                            }

                                                        }
                                                        echo substr($oferta->TituloCorto, 0, $tamaño) . "...";
                                                    } else {
                                                        if ($oferta->PrecioVentaPublico){
                                                            if ($flagcheckboxMoney) {
                                                                echo '<b>'.$oferta->PrecioVentaPublico.' puntos por </b>';
                                                            } else {
                                                                echo '<b> S/'.$oferta->PrecioVentaPublico.' por </b>';
                                                            }

                                                        }
                                                        echo $oferta->TituloCorto;
                                                    }
                                                    ?>
                                                </a>
                                            </h2>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                <?php endif; ?>
            <?php } ?>
            <!-- row 3 -->
            <?php if ($fila['tipo'] == 3) { ?>
                <?php if (!empty($fila['ofertas'])) : ?>
                    <div class="fluid-list flujo-cupones title-bloques">
                        <div class="row margin-b">

                            <?php foreach ($fila['ofertas'] as $oferta) { ?>

                                <div class="col-md-4 margin-bottom-movil">
                                    <div class="fluid-list cupon-two">
                                        <a href="/<?= $category ?>/coupon-puntos/<?= $oferta->Slug ?>">
                                            <figure>
                                                <img src="<?php echo $this->rofertas . $oferta->ImagenOferta ?>"
                                                     title=""/>
                                                <div class="puntos-ico"></div>
                                            </figure>
                                        </a>

                                        <div class="info-cupon-l">
                        <?php if ($this->identity()['flagcheckboxLogo']) { ?>
                                            <figure class="left">
                                                <a>
                                                    <img src="<?php
                                                    $partes = explode(".", $oferta->LogoEmpresa);
                                                    $ext = end($partes);
                                                    $oferta->LogoEmpresa = str_replace('.' . $ext, '', $oferta->LogoEmpresa) . '-small.' . $ext;
                                                    echo $this->rlogos . $oferta->LogoEmpresa;
                                                    ?>"/>
                                                </a>
                                            </figure>
                            <?php  }?>
                                            <div class="info-interna left">
                                                <h2>
                                                    <a href="/<?= $category ?>/coupon-puntos/<?= $oferta->Slug ?>"
                                                       class="title-short">
                                                        <?php
                                                        $ismovil = new MobileDetect();
                                                        if ($ismovil->isMobile() == 2) {
                                                            $tamaño = 43;
                                                        } elseif ($ismovil->isMobile() == 0) {
                                                            $tamaño = 55;
                                                        }

                                                        if ($ismovil->isMobile() == 2) {
                                                            $tamaño = 62;
                                                        } elseif ($ismovil->isMobile() == 0) {
                                                            $tamaño = 75;
                                                        }

                                                        if (strlen($oferta->TituloCorto) >= $tamaño) {


                                                            if ($flagcheckboxMoney) {
                                                                if ($oferta->checkboxMoney) {
                                                                    echo '<b>' . $oferta->PrecioVentaPublico . ' puntos por </b>';
                                                                } else {
                                                                    echo '<b> S/' . $oferta->PrecioVentaPublico . ' por </b>';
                                                                }
                                                        }

                                                            echo substr($oferta->TituloCorto, 0, $tamaño) . "...";
                                                        } else {
                                                            if ($oferta->PrecioVentaPublico){
                                                                if ($flagcheckboxMoney) {
                                                                    echo '<b>' . $oferta->PrecioVentaPublico . ' puntos por </b>';
                                                                } else {
                                                                    echo '<b> S/' . $oferta->PrecioVentaPublico . ' por </b>';
                                                                }
                                                            }
                                                            echo $oferta->TituloCorto;
                                                        }
                                                        ?>
                                                    </a>
                                                </h2>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                <?php endif; ?>
            <?php } ?>
        <?php } ?>
    </div>

    <!-- Banner -->
<?php if (!empty($banners[3])): ?>
    <div class="fluid-list anuncio-banner margin-r ">
        <?php
        $link = "";
        if (isset($banners[3]['link'])) {
            $banners[3]['link'] = str_replace("[NumeroDocumento]", $this->identity()["NumeroDocumento"], $banners[3]['link']);
            $banners[3]['link'] = str_replace("[Nombre]", $this->identity()["Nombre"], $banners[3]['link']);
            $banners[3]['link'] = str_replace("[Apellido]", $this->identity()["Apellido"], $banners[3]['link']);
            $banners[3]['link'] = str_replace("[email]", $this->identity()["email"], $banners[3]['link']);
            $banners[3]['link'] = str_replace("[flagsupervisor]", $this->identity()["flagsupervisor"], $banners[3]['link']);
            $link = 'href="' . $banners[3]['link'] . '" target="_blank"';
        } else {
            $link = '';
        }
        ?>
        <a <?= $link ?>>
            <img class="img-responsive" src="<?= $rbanners . $banners[3]['image'] ?>" title=""/>
        </a>
    </div>
<?php endif; ?>