<!-- Modal Fin De proceso-->
<div class="modal fade modal-vcenter custon-modal modal-error" id="modalErrorPuntos" tabindex="-1" role="dialog" aria-labelledby="modalErrorPuntos">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <button type="button" class="close col-xs-1" data-dismiss="modal" aria-label="Close">
                <span class="glyphicon glyphicon-remove star-ico" aria-hidden="true"></span>
            </button>
            <div class="modal-body">
                <div class="fluid-list header-modal-c header-feli">
                    <h3>LO SENTIMOS</h3>
                    <p>Superó la descargas permitidas del día</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Find el modal Fin de Proceso-->