<section class="content-header ">
    <br><br><br>

    <h1 class="box-title">Agregar Campañas</h1>
    <br><br>
    <?php if (isset($confirm) && $confirm != null) {
        echo '<div class="callout alert alert-' . $this->type . '">' .
            '<button class="close" data-dismiss="alert" type="button">×</button>';
        foreach ($confirm as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</div>';
    }
    ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form->setAttribute('action', $this->url('campanias-premios', array('action' => 'add')));
                        $form->setAttribute('class', 'form-horizontal');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));
                        ?>
                        <fieldset>
                            <legend>Datos Generales</legend>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('NombreCampania')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Campaña:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('NombreCampania')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('Empresa')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Nombre Comercial o Razón Social o RUC:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input-2">
                                                <?= $this->formRow($form->get('Empresa')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('FechaCampania')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Fecha de Creación:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid">
                                            <div class="row-fluid campo">
                                                <div class="col-md-1 null-padding"><i class="fa fa-calendar"></i></div>
                                                <div class="col-md-10 null-padding">
                                                    <?php echo $this->formRow($form->get('FechaCampania')); ?>
                                                </div>
                                                <div class="col-md-1 null-padding text-center asterisco"><p>*</p></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('VigenciaInicio')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Periodo de Vigencia:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid">
                                            <div class="row-fluid campo">
                                                <div class="col-md-1 null-padding"><i class="fa fa-calendar"></i></div>
                                                <div class="col-md-10 null-padding">
                                                    <?php echo $this->formRow($form->get('VigenciaInicio')); ?>
                                                </div>
                                                <div class="col-md-1 null-padding text-center asterisco"><p>*</p></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div
                                    class="<?= $this->formElementErrors($form->get('VigenciaFin')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Hasta:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid">
                                            <div class="row-fluid campo">
                                                <div class="col-md-1 null-padding"><i class="fa fa-calendar"></i></div>
                                                <div class="col-md-10 null-padding">
                                                    <?php echo $this->formRow($form->get('VigenciaFin')); ?>
                                                </div>
                                                <div class="col-md-1 null-padding text-center asterisco"><p>*</p></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('PresupuestoNegociado')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Premios negociados:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('PresupuestoNegociado')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('PresupuestoAsignado')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Premios asignados:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('PresupuestoAsignado')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('ParametroAlerta')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Parametro de alerta:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('ParametroAlerta')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('Comentario'))
                                        ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Comentarios:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <div class="box">
                                                    <div class="box-body pad">
                                                        <?= $this->formRow($form->get('Comentario')); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('Relacionado')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Campaña relacionada:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('Relacionado')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('TipoSegmento')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Tipo Segmento:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input-2">
                                                <?= $this->formRow($form->get('TipoSegmento')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('EstadoCampania')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Estado:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('EstadoCampania')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <?php echo $this->render('_segmentos.phtml'); ?>
                        <div class="form-group">
                            <div class="col-md-offset-10 col-md-2">
                                <p>(*) Campos Obligatorios</p>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="col-md-10">
                                <?= $this->formSubmit($form->get('submit')); ?>
                                <a id="cancelSave" href="/campanias-premios" class="btn btn-default">Cancelar</a>
                            </div>
                        </div>
                        <br>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php echo $this->partial('_scripts.phtml');
