<section class="content-header ">
    <br><br><br>

    <h1 class="box-title">Editar Campañas</h1>
    <br><br>
    <?php if ($this->flashMessenger()->hasMessages()) {
        echo '<div class="callout alert alert-success">' .
            '<button class="close" data-dismiss="alert" type="button">×</button>';
        $messages = $this->flashMessenger()->getMessages();
        foreach ($messages as $message) {
            echo $message;
        }
        echo '</div>';
    } ?>
    <?php if (isset($confirm) && $confirm != null) {
        echo '<div class="callout alert alert-' . $this->type . '">' .
            '<button class="close" data-dismiss="alert" type="button">×</button>';
        foreach ($confirm as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</div>';
    }
    ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form = $this->form;
                        $form->setAttribute('action', $this->url('campanias-premios', array('action' => 'edit', 'id' => $this->id)));
                        $form->setAttribute('class', 'form-horizontal');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));
                        echo $this->formHidden($form->get('id'));
                        ?>
                        <fieldset>
                            <legend>Datos Generales</legend>
                            <div class="form-group">
                                <div>
                                    <div class="col-md-2"><label>ID:</label></div>
                                    <div class="col-md-2">
                                        <input type="text" class="form-control" title="id"
                                               value="<?= $this->id ?>" disabled="disabled">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('NombreCampania')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Campaña:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('NombreCampania')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('Empresa')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Nombre Comercial o Razón Social o RUC:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input-2">
                                                <?= $this->formRow($form->get('Empresa')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('FechaCampania')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Fecha de Creación:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid">
                                            <div class="row-fluid campo">
                                                <div class="col-md-1 null-padding"><i class="fa fa-calendar"></i></div>
                                                <div class="col-md-10 null-padding">
                                                    <?php echo $this->formRow($form->get('FechaCampania')); ?>
                                                </div>
                                                <div class="col-md-1 null-padding text-center asterisco"><p>*</p></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('VigenciaInicio')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Periodo de Vigencia:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid">
                                            <div class="row-fluid campo">
                                                <div class="col-md-1 null-padding"><i class="fa fa-calendar"></i></div>
                                                <div class="col-md-10 null-padding">
                                                    <?php echo $this->formRow($form->get('VigenciaInicio')); ?>
                                                </div>
                                                <div class="col-md-1 null-padding text-center asterisco"><p>*</p></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div
                                    class="<?= $this->formElementErrors($form->get('VigenciaFin')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Hasta:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid">
                                            <div class="row-fluid campo">
                                                <div class="col-md-1 null-padding"><i class="fa fa-calendar"></i></div>
                                                <div class="col-md-10 null-padding">
                                                    <?php echo $this->formRow($form->get('VigenciaFin')); ?>
                                                </div>
                                                <div class="col-md-1 null-padding text-center asterisco"><p>*</p></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('PresupuestoNegociado')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Premios negociados:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('PresupuestoNegociado')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('PresupuestoAsignado')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Premios asignados:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('PresupuestoAsignado')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('ParametroAlerta')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Parametro de alerta:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('ParametroAlerta')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('Comentario'))
                                        ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Comentarios:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <div class="box">
                                                    <div class="box-body pad">
                                                        <?= $this->formRow($form->get('Comentario')); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('Relacionado')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Campaña relacionada:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('Relacionado')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('TipoSegmento')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Tipo Segmento:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input-2">
                                                <?= $this->formRow($form->get('TipoSegmento')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>

                                    </div>
                                </div>
                                <div>
                                    <div class="col-md-2"></div>
                                    <div class="col-md-10">
                                        <div class="TipoSegmento error"><?= $this->dataTipoSegmentoMessage ?></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('EstadoCampania')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Estado:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('EstadoCampania')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div>
                                    <div class="col-md-2"><label>Razón Eliminado:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <textarea rows="4" cols="100" disabled="disabled"
                                                      title="Razon Eliminado"><?= $this->razon ?></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <?php if ($this->typeSeg == 'Clasico') : ?>
                            <fieldset class="table-responsive">
                                <legend>Detalle de los segmentos</legend>
                                <table class="table table-bordered table-condensed">
                                    <thead>
                                    <tr>
                                        <th rowspan="2" class="center-cell">Nombre del Segmento</th>
                                        <th rowspan="2" class="center-cell">Premios por Usuario</th>
                                        <th rowspan="2" class="center-cell">Usuarios Max.</th>
                                        <th rowspan="2" class="center-cell">Presupuesto Segmento</th>
                                        <th class="center-cell">Premios Asignado Activo</th>
                                        <th class="center-cell">Premios Asignado Cancelado</th>
                                        <th class="center-cell">Premios No Asignado</th>
                                        <th colspan="4" class="center-cell">Premios Aplicado</th>
                                        <th class="center-cell">Premios por Aplicar</th>
                                        <th rowspan="2" class="center-cell">Estado</th>
                                        <th rowspan="2" class="center-cell">Editar</th>
                                    </tr>
                                    <tr>
                                        <th class="center-cell">Premios Asignados Activos</th>
                                        <th class="center-cell">Premios dispXAsignar (devuelto a la bolsa)</th>
                                        <th class="center-cell">Premios dispXAsignar</th>
                                        <th class="center-cell">Premios Aplicados Activos</th>
                                        <th class="center-cell">Premios Aplicados No activos</th>
                                        <th class="center-cell">Premios Redimidos Activos</th>
                                        <th class="center-cell">Premios Redimidos No activos</th>
                                        <th class="center-cell">Premios dispXAplicar</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($this->segmentosCampania as $value): ?>
                                        <tr data-id="<?= (int)$value->Eliminado ?>" <?= ((int)$value->Eliminado == 0) ? '' : 'style="color: grey"' ?>>
                                            <td><?= $value->NombreSegmento ?></td>
                                            <td class="center-cell"><?= (int)$value->CantidadPremios ?></td>
                                            <td class="center-cell"><?= (int)$value->CantidadPersonas ?></td>
                                            <td class="center-cell"><?= (int)$value->Subtotal ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? (int)$value->AsignadoActivo : ' - ' ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? $value->AsignadoEliminado : ' - ' ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? $value->Subtotal - $value->AsignadoActivo - $value->AsignadoEliminado - $value->AplicadoInactivo : ' - ' ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? $value->AplicadoActivo : ' - ' ?></td>
                                            <td class="center-cell"><?= (int)$value->AplicadoInactivo ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? $value->RedimidoActivo : ' - ' ?></td>
                                            <td class="center-cell"><?= (int)$value->RedimidoInactivo ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? $value->AsignadoActivo - $value->AplicadoActivo : ' - ' ?></td>
                                            <td><?= ((int)$value->Eliminado == 0) ? "Activo" : "Eliminado" ?></td>
                                            <td>
                                                <a href="<?= $this->url('campanias-premios', array('action' => 'editSegmento', 'id' => $value->id)); ?>">
                                                    <i class="btn btn-warning fa fa-pencil-square-o"></i></a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </fieldset>
                        <?php elseif ($this->typeSeg == 'Personalizado') : ?>
                            <fieldset>
                                <legend>Detalle de los segmentos</legend>
                                <table class="table table-bordered table-condensed">
                                    <thead>
                                    <tr>
                                        <th rowspan="2" class="center-cell">Nombre del Segmento</th>
                                        <th colspan="2" class="center-cell">Premios Asignado Activo</th>
                                        <th class="center-cell">Premios Asignado Cancelado</th>
                                        <th class="center-cell">Premios No Asignado</th>
                                        <th colspan="4" class="center-cell">Premios Aplicado</th>
                                        <th class="center-cell">Premios por Aplicar</th>
                                    </tr>
                                    <tr>
                                        <th class="center-cell">Usuarios Asignados Activos</th>
                                        <th class="center-cell">Premios Asignados Activos</th>
                                        <th class="center-cell">Premios dispXAsignar (devuelto a la bolsa)</th>
                                        <th class="center-cell">Premios dispXAsignar</th>
                                        <th class="center-cell">Premios Aplicados Activos</th>
                                        <th class="center-cell">Premios Aplicados No activos</th>
                                        <th class="center-cell">Premios Redimidos Activos</th>
                                        <th class="center-cell">Premios Redimidos No activos</th>
                                        <th class="center-cell">Premios dispXAplicar</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($this->segmentosCampania as $value): ?>
                                        <tr data-id="<?= (int)$value->Eliminado ?>" <?= ((int)$value->Eliminado == 0) ? '' : 'style="color: grey"' ?>>
                                            <td><?= $value->NombreSegmento ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? (int)$value->UsuariosAsignados : ' - ' ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? (int)$value->AsignadoActivo : ' - ' ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? $value->AsignadoEliminado : ' - ' ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? $value->Subtotal - $value->AsignadoActivo - $value->AsignadoEliminado - $value->AplicadoInactivo : ' - ' ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? $value->AplicadoActivo : ' - ' ?></td>
                                            <td class="center-cell"><?= (int)$value->AplicadoInactivo ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? $value->RedimidoActivo : ' - ' ?></td>
                                            <td class="center-cell"><?= (int)$value->RedimidoInactivo ?></td>
                                            <td class="center-cell"><?= ((int)$value->Eliminado == 0) ? $value->AsignadoActivo - $value->AplicadoActivo : ' - ' ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </fieldset>
                        <?php endif; ?>
                        <?php echo $this->render('_segmentos.phtml'); ?>
                        <div class="form-group">
                            <div class="col-md-offset-10 col-md-2">
                                <p>(*) Campos Obligatorios</p>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="col-md-12" style="text-align: center;">
                                <?php if ($this->opcion) : ?>
                                    <button class="btn btn-info" type="button" id="addSegment">Agregar Segmento</button>
                                    <?= $this->formSubmit($form->get('submit')); ?>
                                    <button class="btn btn-danger" type="button" data-toggle="modal"
                                            data-target="#modalEliminar">
                                        Eliminar
                                    </button>
                                <?php endif; ?>
                                <a href="<?= $this->url('campanias-premios', array('action' => 'index')); ?>"
                                   class="btn btn-default">Cancelar</a>
                            </div>
                        </div>
                        <br>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
if ($this->opcion) {
    echo $this->partial('_modals_campania.phtml');
}
echo $this->partial('_scripts.phtml');