<section class="content-header ">
    <br><br><br>

    <h1 class="box-title">Lista de Campañas</h1>
    <br><br>
    <?php if ($this->flashMessenger()->hasMessages()) {
        echo '<div class="callout alert alert-success">' .
            '<button class="close" data-dismiss="alert" type="button">×</button>';
        $messages = $this->flashMessenger()->getMessages();
        foreach ($messages as $message) {
            echo $message;
        }
        echo '</div>';
    } ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form = $this->form;
                        $p = $this->p;
                        $q1 = $this->q1;
                        $q2 = $this->q2;
                        $order_by = $this->order_by;
                        $order = $this->order;

                        $form->setAttribute('action', $this->url('campanias-premios', array('action' => 'index')));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));

                        ?>
                        <div class="row">
                            <fieldset>
                                <legend>Buscar por:</legend>
                                <div class="form-group">
                                    <div class="col-md-2"><label>Empresa Cliente:</label></div>
                                    <div class="col-md-4">
                                        <?= $this->formRow($form->get('Empresas')); ?>
                                    </div>
                                    <div class="col-md-2"><label>Fecha Creación:</label></div>
                                    <div class="col-md-3">
                                        <?= $this->formRow($form->get('FechaCampania')); ?>
                                    </div>
                                    <div class="col-md-1">
                                        <?= $this->formSubmit($form->get('submit')); ?>
                                    </div>
                                </div>
                                <div style="clear:both;"></div>
                            </fieldset>
                        </div>
                        <hr>
                        <?= $this->form()->closeTag(); ?>
                    </div>
                    <div class="dataTables_wrapper form-inline dt-bootstrap" id="example1_wrapper">
                        <div class="row-fluid">
                            <div class="col-md-12 text-right">
                                <div id="example1_length" class="dataTables_length"><br>
                                    <a href="<?php echo $this->url(
                                        'campanias-premios',
                                        array(
                                            'action' => 'export',
                                            'id' => $q1,
                                            'val' => $q2
                                        )
                                    ); ?>"
                                       class="btn btn-primary">Exportar</a>
                                </div>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="col-sm-12">
                                <table aria-describedby="example1_info" role="grid" id="example1"
                                       class="table table-bordered table-striped dataTable">
                                    <thead>
                                    <tr role="row">
                                        <th>
                                            <a href="<?= $this->url(
                                                'campanias-premios',
                                                array(
                                                    'order_by' => 'Empresa',
                                                    'order' => ($order_by == 'Empresa') ? $order : 'asc',
                                                    'page' => $p,
                                                    'q1' => $q1,
                                                    'q2' => $q2
                                                )
                                            ); ?>">Empresa Cliente</a>
                                        </th>
                                        <th>
                                            <a href="<?= $this->url(
                                                'campanias-premios',
                                                array(
                                                    'order_by' => 'Campania',
                                                    'order' => ($order_by == 'Campania') ? $order : 'asc',
                                                    'page' => $p,
                                                    'q1' => $q1,
                                                    'q2' => $q2
                                                )
                                            ); ?>">Campaña</a>
                                        </th>
                                        <th>
                                            <a href="<?= $this->url(
                                                'campanias-premios',
                                                array(
                                                    'order_by' => 'Presupuesto',
                                                    'order' => ($order_by == 'Presupuesto') ? $order : 'asc',
                                                    'page' => $p,
                                                    'q1' => $q1,
                                                    'q2' => $q2
                                                )
                                            ); ?>">Presupuesto (Cantidad Premios)</a>
                                        </th>
                                        <th>
                                            <a href="<?= $this->url(
                                                'campanias-premios',
                                                array(
                                                    'order_by' => 'Inicio',
                                                    'order' => ($order_by == 'Inicio') ? $order : 'asc',
                                                    'page' => $p,
                                                    'q1' => $q1,
                                                    'q2' => $q2
                                                )
                                            ); ?>">Inicio</a>
                                        </th>
                                        <th>
                                            <a href="<?= $this->url(
                                                'campanias-premios',
                                                array(
                                                    'order_by' => 'Fin',
                                                    'order' => ($order_by == 'Fin') ? $order : 'asc',
                                                    'page' => $p,
                                                    'q1' => $q1,
                                                    'q2' => $q2
                                                )
                                            ); ?>">Fin</a>
                                        </th>
                                        <th>
                                            <a href="<?= $this->url(
                                                'campanias-premios',
                                                array(
                                                    'order_by' => 'TipoSegmento',
                                                    'order' => ($order_by == 'TipoSegmento') ? $order : 'asc',
                                                    'page' => $p,
                                                    'q1' => $q1,
                                                    'q2' => $q2
                                                )
                                            ); ?>">Tipo</a>
                                        </th>
                                        <th>
                                            <a href="<?= $this->url(
                                                'campanias-premios',
                                                array(
                                                    'order_by' => 'Estado',
                                                    'order' => ($order_by == 'Estado') ? $order : 'asc',
                                                    'page' => $p,
                                                    'q1' => $q1,
                                                    'q2' => $q2
                                                )
                                            ); ?>">Estado</a>
                                        <th>
                                            <a>Editar</a>
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php $campanias = $this->campanias;
                                    if (count($this->campanias) > 0) {
                                        foreach ($campanias as $dato) : ?>
                                            <tr data-id="<?php echo $dato->id ?>">
                                                <td style="width: 150px"><?= $this->escapeHtml($dato->Empresa); ?></td>
                                                <td style="width: 150px"><?= $this->escapeHtml($dato->NombreCampania); ?></td>
                                                <td style="width: 150px"><?= (int)$this->escapeHtml($dato->Presupuesto); ?></td>
                                                <td style="width: 150px"><?= $this->escapeHtml($dato->VigenciaInicio); ?></td>
                                                <td style="width: 150px"><?= $this->escapeHtml($dato->VigenciaFin); ?></td>
                                                <td style="width: 150px"><?= $this->escapeHtml($dato->TipoSegmento); ?></td>
                                                <td style="width: 150px"><?= $this->escapeHtml($dato->EstadoCampania); ?></td>
                                                <td>
                                                    <a href="<?= $this->url('campanias-premios', array('action' => 'edit', 'id' => $dato->id)); ?>">
                                                        <i class="btn btn-warning fa fa-pencil-square-o"></i></a>
                                                </td>
                                            </tr>
                                            <?php
                                        endforeach;
                                    } else {
                                        echo '<tr><td colspan="10">No hay Campañas Registradas</td></tr>';
                                    } ?>
                                    </tbody>
                                </table>
                                <div class="col-md-4"><br>
                                    <p>
                                        <?php if (count($campanias) > 0) { ?>
                                            <?= (($campanias->getCurrentPageNumber() * $campanias->getItemCountPerPage()) -
                                                ($campanias->getItemCountPerPage() - 1)); ?>
                                            -
                                            <?= ($campanias->getCurrentPageNumber() * $campanias->getItemCountPerPage() <
                                                $campanias->getTotalItemCount())
                                                ? $campanias->getCurrentPageNumber() * $campanias->getItemCountPerPage()
                                                : $campanias->getTotalItemCount() ?> de
                                            <?= $campanias->getTotalItemCount(); ?> Registros
                                            <?php
                                        }
                                        ?>
                                    </p>
                                </div>
                                <?php
                                if (isset($campanias)) {
                                    echo $this->paginationControl(
                                        $campanias,
                                        'Sliding',
                                        'paginator-campanias-premios',
                                        array(
                                            'order_by' => $order_by,
                                            'order' => ($order == "desc") ? 'asc' : 'desc',
                                            'q1' => $q1,
                                            'q2' => $q2,
                                        )
                                    );
                                } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
$this->inlineScript()->appendFile($this->basePath('js/premios/campanias.js'));
