<section class="content-header ">
    <br><br><br>

    <h1 class="box-title">Mantenimiento de Banners</h1>
    <br><br>
    <?php if (isset($msg)) {
        echo '<div class="callout alert alert-' . $this->alert .
            '"><button class="close" data-dismiss="alert" type="button">×</button>';
        foreach ($msg as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</div>';
    } ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form = $this->form;
                        $form->setAttribute('action', $this->url('banners', array('action' => 'banner')));
                        $form->setAttribute('class', 'form-horizontal');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));

                        ?>
                        <fieldset>
                            <legend>Banners</legend>
                            <div class="form-group">
                                <div class="col-md-2"><label>Nombre Comercial o Razón Social o RUC: </label></div>
                                <div class="col-md-5">
                                    <?= $this->formRow($form->get('empresa')); ?>
                                    <p><?= $this->nombre_empresa; ?></p>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4">
                                    <div class="col-md-4">
                                        <label>
                                            <input id="r_cat" class="tipo" type="radio" name="tipo" value="0" checked="checked">Categoria
                                        </label>
                                    </div>
                                    <div class="col-md-8">
                                        <?= $this->formRow($form->get('BNF_Categoria_id')); ?>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="col-md-4">
                                        <label>
                                            <input class="tipo" type="radio" name="tipo" value="1">Campaña
                                        </label>
                                    </div>
                                    <div class="col-md-8">
                                        <?= $this->formRow($form->get('BNF_Campanias_id')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-3">
                                    <label>
                                        <input class="tipo" type="radio" name="tipo" value="2">Tiendas
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label>
                                        <input class="tipo punto" type="radio" name="tipo" value="3">Puntos
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label>
                                        <input class="tipo premios" type="radio" name="tipo" value="4">Premios
                                    </label>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <div class="form-group">
                                <div>
                                    <div class="col-md-2"></div>
                                    <div class="col-md-8"></div>
                                </div>
                            </div>
                            <div class="form-group principal">
                                <?= $this->formElementErrors($form->get('Banner05')) ? 'has-error' : '' ?>
                                <div class="col-md-2"><label>Banner Principal:</label></div>
                                <div class="col-md-4"><?= $this->formRow($form->get('Banner05')); ?></div>
                                <div class="col-md-1"><label>Link:</label></div>
                                <div class="col-md-3"><?= $this->formRow($form->get('Banner05Url')); ?></div>
                            </div>
                            <div class="form-group secundario">
                                <?= $this->formElementErrors($form->get('Banner01')) ? 'has-error' : '' ?>
                                <div class="col-md-2"><label>Imagen 01:</label></div>
                                <div class="col-md-4"><?= $this->formRow($form->get('Banner01')); ?></div>
                                <div class="col-md-1"><label>Link:</label></div>
                                <div class="col-md-3"><?= $this->formRow($form->get('Banner01Url')); ?></div>
                            </div>
                            <div class="form-group">
                                <?= $this->formElementErrors($form->get('Banner02')) ? 'has-error' : '' ?>
                                <div class="col-md-2"><label>Banner 01:</label></div>
                                <div class="col-md-4"><?= $this->formRow($form->get('Banner02')); ?></div>
                                <div class="col-md-1"><label>Link:</label></div>
                                <div class="col-md-3"><?= $this->formRow($form->get('Banner02Url')); ?></div>
                            </div>
                            <div class="form-group">
                                <?= $this->formElementErrors($form->get('Banner03')) ? 'has-error' : '' ?>
                                <div class="col-md-2"><label>Banner 02:</label></div>
                                <div class="col-md-4"><?= $this->formRow($form->get('Banner03')); ?></div>
                                <div class="col-md-1"><label>Link:</label></div>
                                <div class="col-md-3"><?= $this->formRow($form->get('Banner03Url')); ?></div>
                            </div>
                            <div class="form-group">
                                <?= $this->formElementErrors($form->get('Banner04')) ? 'has-error' : '' ?>
                                <div class="col-md-2"><label>Banner 03:</label></div>
                                <div class="col-md-4"><?= $this->formRow($form->get('Banner04')); ?></div>
                                <div class="col-md-1"><label>Link:</label></div>
                                <div class="col-md-3"><?= $this->formRow($form->get('Banner04Url')); ?></div>
                            </div>
                            <div class="form-group puntos" style="display: none">
                                <?= $this->formElementErrors($form->get('Banner06')) ? 'has-error' : '' ?>
                                <div class="col-md-2"><label>Banner Oferta:</label></div>
                                <div class="col-md-4"><?= $this->formRow($form->get('Banner06')); ?></div>
                                <div class="col-md-1"><label>Link:</label></div>
                                <div class="col-md-3"><?= $this->formRow($form->get('Banner06Url')); ?></div>
                            </div>
                        </fieldset>
                        <div class="box-footer">
                            <div class="col-md-10">
                                <?php echo $this->formSubmit($form->get('submit')); ?>
                                <a href="/ordenamiento" class="btn btn-default">Cancelar</a>
                            </div>
                        </div>
                        <hr>
                        <?php echo $this->form()->closeTag(); ?>
                        <div class="bannerspri" style="display: none;">
                            <fieldset>
                                <legend>Banners Registrados</legend>
                                <div class="row-fluid">
                                    <div class="col-sm-12">
                                        <table role="grid" id="bannerstable"
                                               class="table table-bordered table-striped dataTable">
                                            <thead>
                                            <tr role="row">
                                                <th style="width: 300px"><a>Nombre de la Imagen</a></th>
                                                <th style="width: 50px"><a>Link</a></th>
                                                <th style="width: 50px"><a>Activo</a></th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </fieldset>
                        </div>

                        <div id="galeriapri" style="display: none;">
                            <?php
                            $formgalery = $this->formgalery;
                            $formgalery->setAttribute('action', $this->url('banners', array('action' => 'addgalery')));
                            $formgalery->setAttribute('class', 'form-horizontal');
                            $formgalery->setAttribute('id', 'galeryform');
                            $formgalery->prepare();
                            echo $this->form()->openTag($formgalery);
                            ?>
                            <fieldset>
                                <legend>Galeria Principal</legend>
                                <div class="form-group">
                                    <div class="col-md-1"><label>Imagen:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($formgalery->get('Galeria')); ?>
                                                <?= $this->formRow($formgalery->get('empresa_g')); ?>
                                            </div>
                                            <label for="galeria" class="error" id="imagenError"></label>
                                        </div>
                                    </div>
                                    <div class="col-md-1"><label>Link:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($formgalery->get('GaleriaUrl')); ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <?php echo $this->formSubmit($formgalery->get('submit')); ?>
                                        <img id="loading-img" src="<?= $this->basePath('img/ajax_clock_small.gif')?>">
                                    </div>
                                </div>

                                <div class="row-fluid">
                                    <div class="col-sm-12">
                                        <table role="grid" id="galerytable"
                                               class="table table-bordered table-striped dataTable">
                                            <thead>
                                            <tr role="row">
                                                <th style="width: 100px"><a>Imagen</a></th>
                                                <th style="width: 300px"><a>Nombre de la Imagen</a></th>
                                                <th style="width: 50px"><a>Link</a></th>
                                                <th style="width: 50px"><a>Eliminar</a></th>
                                            </tr>
                                            </thead>
                                            <tbody>

                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </fieldset>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
$this->inlineScript()->prependFile($this->basePath('js/ordenamiento/banner_index.js?'.$this->configItem('version_script')));
