<?php $this->headStyle()->captureStart() ?>

<?php
$color = ($this->identity()['Color_hover'] != null) ?$this->identity()['Color_hover'] :"#0a0d12"; //($this->identity()->Color != null) ?$this->identity()->Color :"#0a0d12";
?>
.ui-widget-content {
border: 1px solid #dddddd;
background: #fff;
color: #333333;
}
.ui-state-focus{
border: 0px solid #fbcb09;
background: #FECC24;
font-weight: normal;
color: #fff;
}
.ui-menu .ui-state-focus, .ui-menu .ui-state-active {
margin: 0px !important;
background-image: none !important;
color: #FFF;
border: 0;
background-color: <?= $color?> !important;
}
.ui-menu-item{
padding: 10px !important;
text-transform: capitalize;
}
<?php $this->headStyle()->captureEnd() ?>

