<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="fluid-list bloque-f">
                    <h4>EMPRESAS</h4>
                    <ul class="reset-ul">
                        <li><a href="http://www.weeare.pe">Servicio</a></li>
                        <li><a href="https://medium.com/weeare">Políticas de privacidad</a></li>
                        <li><a href="https://medium.com/weeare">Blog</a></li>
                    </ul>
                </div>    
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="fluid-list bloque-f">
                    <h4><a href="http://www.weeare.pe">CONTACTO</a></h4>
                    <ul class="reset-ul">
                        <li>(01) 2217330</li>
                    </ul>
                </div>    
            </div>
        </div>
    </div>
</footer>