<!-- Modal Tebca-->
<div class="modal fade modal-vcenter custon-modal modal-tebca" id="modalTebca" tabindex="-1" role="dialog" aria-labelledby="modalTebca">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <button type="button" class="close col-xs-1" data-dismiss="modal" aria-label="Close">
                <span class="glyphicon glyphicon-remove star-ico" aria-hidden="true"></span>
            </button>
            <div class="modal-body">
                <img src="<?=$this->basepath('img/LightBox_Tebca.png')?>" alt="" style="width: 100%">
            </div>
        </div>
    </div>
</div>
<!--Find el modal Tebca-->