<div class="fluid-list flujo-cupones title-bloques">
    <?php
    use Application\Service\MobileDetect;

    $nfilades = 0;
    $cantodes = 0;
    $cant_odes = count($this->ofertas_descubre);
    if (false/*$cant_odes != 0*/) { ?>
        <h3 class="hidden-xs">Descubre más Beneficios</h3>
    <?php }
    foreach ($this->ofertas_descubre as $oferta) { ?>
        <?php if ($nfilades == 0) { ?>
            <div class="row margin-b">
        <?php } ?>
        <div class="col-md-4 margin-bottom-movil">
            <article class="item-product">
                <h2><a href="/<?= $category ?>/coupon/<?= $oferta->SlugOferta ?>" title="<?=$oferta->nombreEmpresa ?>"><?=$oferta->nombreEmpresa ?></a></h2>
                <p><?php if ($oferta->datoBeneficio != null) { ?>

                                                        <?php if ($oferta->idTipoBeneficio == 1) { ?>
                                                            <strong>-<?= $oferta->datoBeneficio ?>% Descuento</strong>
                                                        <?php } elseif ($oferta->idTipoBeneficio == 2) { ?>
                                                            <strong>-S/.<?= $oferta->datoBeneficio ?> Descuento</strong>
                                                        <?php } elseif ($oferta->idTipoBeneficio == 3) { ?>
                                                            <strong><?= $oferta->datoBeneficio ?> en</strong>
                                                        <?php } else { ?>
                                                            <strong><?= $oferta->datoBeneficio ?></strong>
                                                        <?php } ?>

                                                    <?php } ?> 
						    <?=$oferta->TituloCortoOferta ?>
		</p>
                <div class="fluid-list b-prec">
                    <!--<em>De <span class="p-bef">S/299</span> a <span>S/59</span></em>-->
                    <a href="/<?= $category ?>/coupon/<?= $oferta->SlugOferta ?>" class="btn-belcorp right">Detalle</a>
                </div>
                <figure>
                    <a href="/<?= $category ?>/coupon/<?= $oferta->SlugOferta ?>" title="">
                        <img src="<?php echo $this->rofertas . $oferta->imagenOferta ?>" alt="">
                    </a>
                </figure>
            </article>
        </div>
        <?php $cantodes++;
        $nfilades++; ?>
        <?php if ($nfilades == 3 || $cant_odes == $cantodes) { ?>
            </div>
            <?php $nfilades = 0;
        }
    } ?>
</div>
<!-- Banner -->
<?php if (!empty($banners[4])) { ?>
    <div class="fluid-list anuncio-banner margin-r text-center">
        <?php
        $link = "";
        if (isset($banners[4]['link'])) {
            $banners[4]['link'] = str_replace("[NumeroDocumento]", $this->identity()["NumeroDocumento"], $banners[4]['link']);
            $banners[4]['link'] = str_replace("[Nombre]", $this->identity()["Nombre"], $banners[4]['link']);
            $banners[4]['link'] = str_replace("[Apellido]", $this->identity()["Apellido"], $banners[4]['link']);
            $banners[4]['link'] = str_replace("[email]", $this->identity()["email"], $banners[4]['link']);
            $banners[4]['link'] = str_replace("[flagsupervisor]", $this->identity()["flagsupervisor"], $banners[4]['link']);
            $link = 'href="' . $banners[4]['link'] . '" target="_blank"';
        } else {
            $link = '';
        }
        ?>
        <a <?= $link ?>>
            <img class="img-responsive" src="<?= $rbanners . $banners[4]['image']; ?>" title=""/>
        </a>
    </div>
<?php } ?>
<!-- End Banner -->
<div class="fluid-list flujo-cupones title-bloques content-load">
    <?php
    $nfilares = 0;
    $cantores = 0;
    $cant_ores = count($this->ofertas_restantes);
    ?>
    <?php foreach ($this->ofertas_restantes as $oferta) { ?>
        <?php if ($nfilares == 0) { ?>
            <div class="row margin-b restantes">
        <?php } ?>
        <div class="col-md-4 margin-bottom-movil restantes-items">
            <article class="item-product">
                <h2><a href="/<?= $category ?>/coupon/<?= $oferta->SlugOferta ?>" title=""><?=$oferta->nombreEmpresa ?></a></h2>
                <p><?php if ($oferta->datoBeneficio != null) { ?>

                                                        <?php if ($oferta->idTipoBeneficio == 1) { ?>
                                                            <strong>-<?= $oferta->datoBeneficio ?>% Descuento</strong>
                                                        <?php } elseif ($oferta->idTipoBeneficio == 2) { ?>
                                                            <strong>-S/.<?= $oferta->datoBeneficio ?> Descuento</strong>
                                                        <?php } elseif ($oferta->idTipoBeneficio == 3) { ?>
                                                            <strong><?= $oferta->datoBeneficio ?> en</strong>
                                                        <?php } else { ?>
                                                            <strong><?= $oferta->datoBeneficio ?></strong>
                                                        <?php } ?>

                                                    <?php } ?> 
						    <?=$oferta->TituloCortoOferta ?>
		        </p>
                <div class="fluid-list b-prec">
                    <!--<em>De <span class="p-bef">S/299</span> a <span>S/59</span></em><!--Mostrar los dos precios-->
                    <a href="/<?= $category ?>/coupon/<?= $oferta->SlugOferta ?>" class="btn-belcorp right">Detalle</a>
                </div>
                <figure>
                    <a href="/<?= $category ?>/coupon/<?= $oferta->SlugOferta ?>" title="">
                        <img src="<?php echo $this->rofertas . $oferta->imagenOferta ?>" alt="">
                    </a>
                </figure>
            </article>
        </div>
        <?php $cantores++;
        $nfilares++; ?>
        <?php if ($nfilares == 3 || $cant_ores == $cantores) { ?>
            </div>
            <?php $nfilares = 0;
        }
    } ?>
</div>
<div class="text-center" id="loading">
    <p>
        <img style="display: inline" class="img-responsive" src="/img/loading.gif" width="50px"/>
    </p>
</div>
<div class="offset" style="display:none" data-offset="<?php echo ($this->offset != null) ? $this->offset : 0; ?>"></div>
<div class="notin" style="display:none" data-notin="<?= implode(',', $this->notin) ?>"></div>
<div class="ubigeo" style="display:none"
     data-ubigeo="<?php echo ($this->ubigeo_id != null) ? $this->ubigeo_id : null; ?>"></div>
<div class="categoria" style="display:none"
     data-categoria="<?php echo ($this->categoria_id != null) ? $this->categoria_id : null; ?>"></div>
<div class="campaign" style="display:none"
     data-campaign="<?php echo ($this->campania_id != null) ? $this->campania_id : null; ?>"></div>
<div class="companya" style="display:none"
     data-companya="<?php echo ($this->company_id != null) ? $this->company_id : null; ?>"></div>
<div class="rofertas" style="display:none" data-rofertas="<?php echo $this->rofertas ?>"></div>
<div class="rlogos" style="display:none" data-rlogos="<?php echo $this->rlogos ?>"></div>
<div class="categories" style="display:none" data-categories="<?= $category ?>"></div>

<?php $this->headScript()->captureStart() ?>
var totalJS = <?php echo json_encode($total); ?>;
<?php $this->headScript()->captureEnd() ?>
