<div class="login-box">
    <?php if (isset($msg)) {
        echo '<div class="callout alert alert-danger"><button class="close" data-dismiss="alert" type="button">×</button>';
        foreach ($msg as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</div>';
    } ?>
    <div class="login-logo">
        <b>BENEFICIOS</b>
    </div><!-- /.login-logo -->
    <div class="login-box-body">
        <?php
        // within a view script

        $form->setAttribute('action', $this->url('login' ));
        $form->prepare();
        ?>
        <?php echo $this->form()->openTag($form);// Render the opening tag ?>
        <div>
            <div class="form-group has-feedback <?= $this->formElementErrors($form->get('Correo')) ? 'has-error' : '' ?>">

                <?php echo $this->formRow($form->get('Correo')); ?>
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
            </div>
            <div class="form-group has-feedback <?= $this->formElementErrors($form->get('Contrasenia')) ? 'has-error' : '' ?>">
                <?php echo $this->formRow($form->get('Contrasenia')); ?>
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox" name="recordarme"> Recordarme
                        </label>
                    </div>
                </div><!-- /.col -->
                <?php echo $this->formElement($form->get('csrf')) ?>
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Ingresar</button>
                </div><!-- /.col -->
            </div>
        <?php echo $this->form()->closeTag() ?>

        <a href="#">Recuperar mi contraseña</a><br>
    </div><!-- /.login-box-body -->
</div><!-- /.login-box -->