<div class="modal fade modal-vcenter" id="modalBienvenida" tabindex="-1" role="dialog" aria-labelledby="modalmessage">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close col-xs-1 close-flyout" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><img src="http://beneficios.pe/img/login.png" /></h4>
            </div>
            <div class="modal-body">
                <div class="fluid-list header-modal-c header-feli">
                    <h3>FELICITACIONES</h3>
                    <p>Tienes <strong><?= $this->identity()["puntos"] ?> puntos</strong>
                        disponibles para<br> Beneficios especiales y<br>
                        <strong><?= $this->identity()["premios"] ?> Premios</strong> esperando por tí</p>
                    <a href="<?= $this->url('premios') ?>" class="btn-premios-b">Elígelos aquí</a>
                </div>
            </div>
        </div>
    </div>
</div>