<?php $children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0]; ?>
<div class="modal fade modal-vcenter modal-active" id="elegirOpcion" tabindex="-1" role="dialog"
     aria-labelledby="elegirOpcion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><img src="http://beneficios.pe/img/login.png"/></h4>
            </div>
            <div class="modal-body">
                <h4>Elige tu Oferta</h4>
                <?php $count = 0; ?>
                <?php foreach ($child->atributosData as $item): ?>
                    <?php if ($item->Stock > 0): ?>
                        <div class="fluid-list list-opciones">
                            <a href="javascript:;" class="enviarPremios" data-value="<?= $item->id ?>">
                                <span><?= ++$count ?></span>
                                <h2><span><?= $item->NombreAtributo ?></span>
                                    <input type="hidden" id="nombreAtributo"
                                           value="<?= $item->NombreAtributo ?>">
                                    <?php if ($item->FechaVigencia != null) :
                                        $date = new DateTime($item->FechaVigencia);
                                        $mes = $date->format('m'); ?>
                                        Cupón válido hasta el <?= '' . $date->format('d') . ' de ' . $child->meses[$mes - 1] ?>
                                    <?php endif;?>
                                    <input type="hidden" id="precioAtributo"
                                               value="<?= $item->PrecioVentaPublico ?>">
                                </h2>
                            </a>
                        </div>
                    <?php else: ?>
                        <div class="fluid-list list-opciones">
                            <a href="javascript:;" class="enviarPremios a-locked" role="button">
                                <span><?= ++$count ?></span>
                                <h2><span><?= $item->NombreAtributo ?></span>
                                    <input type="hidden" id="nombreAtributo"
                                           value="<?= $item->NombreAtributo ?>">
                                    <?php if ($item->FechaVigencia != null) :
                                        $date = new DateTime($item->FechaVigencia);
                                        $mes = $date->format('m'); ?>
                                        Cupón válido hasta el <?= '' . $date->format('d') . ' de ' . $child->meses[$mes - 1] ?>
                                    <?php endif; ?>
                                </h2>
                            </a>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
                <div class="footer-m-e">
                    <p>Al dar clic en siguiente podrás descargar el cupón.</p>
                </div>
            </div>
        </div>
    </div>
</div>