<?php $ofertas = $this->ofertas_relacionadas; ?>
<div class="fluid-list flujo-cupones cupones_interes title-bloques">
    <h3 class="title-interna">Estos otros beneficios te pueden interesar</h3>
    <?php for ($i = 0; $i <= 2; $i++) {
        if (isset($ofertas[$i])) { ?>
            <div class="fluid-list margin-b">
                <div class="fluid-list cupon-two">
                    <a href="/<?= $this->category ?>/coupon-premios/<?= $ofertas[$i]->Slug ?>">
                        <figure>
                            <img src="<?php echo $this->rofertas . $ofertas[$i]->ImagenOferta ?>" title=""/>
                            <div class="premios-ico"></div>
                        </figure>
                    </a>
                    <div class="info-cupon-l">
            <?php if ($this->identity()['flagcheckboxLogo']) { ?>
                        <figure class="left">
                            <a>
                                <img src="<?php
                                $trozos = explode(".", $ofertas[$i]->LogoEmpresa);
                                $ext = end($trozos);
                                $ofertas[$i]->LogoEmpresa = str_replace('.' . $ext, '', $ofertas[$i]->LogoEmpresa) . '-small.' . $ext;
                                echo $this->rlogos . $ofertas[$i]->LogoEmpresa ?>"/>
                            </a>
                        </figure>
                <?php }?>
                        <div class="info-interna left">
                            <h2>
                                <a href="/<?= $this->category ?>/coupon-premios/<?= $ofertas[$i]->Slug ?>"
                                   class="title-short">
                                    <?php
                                    $tamaño = 58;
                                    if (strlen($ofertas[$i]->TituloCorto) >= $tamaño) {
                                        echo substr($ofertas[$i]->TituloCorto, 0, $tamaño) . "...";
                                    } else {
                                        echo $ofertas[$i]->TituloCorto;
                                    }
                                    ?>
                                </a>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>
        <?php }
    } ?>

    <?php for ($i = 3; $i <= 5; $i++) {
        if (isset($ofertas[$i])) { ?>
            <div class="fluid-list margin-b">
                <div class="fluid-list cupon-two">
                    <a href="/<?= $this->category ?>/coupon-premios/<?= $ofertas[$i]->Slug ?>">
                        <figure>
                            <img src="<?= $this->rofertas . $ofertas[$i]->ImagenOferta ?>" title=""/>
                            <div class="premios-ico"></div>
                        </figure>
                    </a>
                    <div class="info-cupon-l">
            <?php if ($this->identity()['flagcheckboxLogo']) { ?>
                        <figure class="left">
                            <a>
                                <img src="<?php
                                $trozos = explode(".", $ofertas[$i]->LogoEmpresa);
                                $ext = end($trozos);
                                $ofertas[$i]->LogoEmpresa = str_replace('.' . $ext, '', $ofertas[$i]->LogoEmpresa) . '-small.' . $ext;
                                echo $this->rlogos . $ofertas[$i]->LogoEmpresa ?>"/>
                            </a>
                        </figure>
                <?php }?>
                        <div class="info-interna left">
                            <h2>
                                <a href="/<?= $this->category ?>/coupon-premios/<?= $ofertas[$i]->Slug ?>"
                                   class="title-short">
                                    <?php
                                    $tamaño = 58;
                                    if (strlen($ofertas[$i]->TituloCorto) >= $tamaño) {
                                        echo substr($ofertas[$i]->TituloCorto, 0, $tamaño) . "...";
                                    } else {
                                        echo $ofertas[$i]->TituloCorto;
                                    }
                                    ?>
                                </a>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>
        <?php }
    } ?>
</div>