<div class="fluid-list cnt-cupon">
    <div class="row primary-info">
        <div class="col-md-12">
            <?php echo $contenido; ?>
        </div>
        <div class="col-md-12">
            <a class="btn btn-primary"
               href="<?= $this->url(
                   'lead',
                   array('action' => 'index', 'opt' => $slug)
               ); ?>">Volver</a>
        </div>
    </div>
</div>