<div class="fluid-list header-cupon" style="background: url(/img/bg-cupon.jpg) no-repeat;background-size: cover;background-position: center center;">
    <div class="container">
        <div class="item-cupon">
            <?php if ($this->identity()['flagcheckboxLogo']) { ?>
            <div class="fluid-list logo-cupon">
                <span><img src="<?= $this->rlogos . $cupon->LogoEmpresa ?>"></span> <?=$cupon->nombreEmpresa?>
            </div>
            <?php }?>
            <p>                    <?php if ($cupon->datoBeneficio != null) : ?>

                        <?php if ($cupon->idTipoBeneficio == 1) : ?>
                            <strong>-<?= $cupon->datoBeneficio ?>% Descuento</strong>
                        <?php elseif ($cupon->idTipoBeneficio == 2) : ?>
                            <strong>-S/.<?= $cupon->datoBeneficio ?> Descuento</strong>
                        <?php elseif ($cupon->idTipoBeneficio == 3) : ?>
                            <strong><?= $cupon->datoBeneficio ?> en</strong>
                        <?php else : ?>
                            <strong><?= $cupon->datoBeneficio ?></strong>
                        <?php endif; ?>

                    <?php endif; ?>
                    <?= $cupon->TituloOferta ?>

	    </p>
            <div class="fluid-list desc-ut">
                <!--<span class="left">50% dscto</span>-->
                <?php if ($cupon->EstadoOferta == 'Publicado' and $cupon->caducadoTiempo >= 0 and $cupon->Stock >= 1) : ?>
                    <?php if ($cupon->TipoAtributo == 'Split') : ?>
                        <a href="#" class="btn btn-cupon btn-full btn-belcorp right" data-toggle="modal"
                           data-target="#elegirOpcion">Elegir Cupón</a>
                    <?php else : ?>
                        <a href="#" class="btn btn-cupon btn-full btn-belcorp right" data-toggle="modal"
                           data-target="#enviarMail">Utilizar</a>
                    <?php endif; ?>
                <?php else : ?>
                    <a class="btn btn-cupon btn-full btn-belcorp right" style="cursor: default;background: #609EE8">Caducado</a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<div class="fluid-list">
<div class="container">
<style>
    .cnt-tarjetas {
        text-align: center;
        display: inline-block;
        width: 230px;
        vertical-align: middle;
    }

    .cnt-tarjetas img {
        width: 100px;
    }

    .left-info-c span {
        width: auto;
        margin-right: 10px;
    }
</style>
<?php $cupon = $this->cupon; ?>
<div class="fluid-list cnt-cupon">
    <div class="row primary-info" style="display: none;"><!--eliminar le puse display none para no mostrarlo en la vista-->
        <div class="col-md-8">
            <?php
            $imgCupon = $this->imgCupon;
            $count = count($imgCupon);
            if ($count == 1) :
                foreach ($imgCupon as $img) :
                    ?>
                    <div class="fluid-list img-cupon">
                        <figure>
                            <img src="<?php
                            $trozos = explode(".", $img->imagenOferta);
                            $ext = end($trozos);
                            $img->imagenOferta = str_replace('.' . $ext, '', $img->imagenOferta) . '-large.' . $ext;
                            echo $this->rofertas . $img->imagenOferta
                            ?>"/>
                        </figure>
                    </div>
                <?php endforeach;
            else :
                ?>
                <div class="fluid-list slider-home box-sombra">
                    <div class="fluid-list sombra-interna">
                        <div class="slider slider-promocion box-sombra-caja">
                            <?php foreach ($imgCupon as $img): ?>
                                <div class="info-cupon">
                                    <a href="#">
                                        <img src="<?php
                                        $partes = explode(".", $img->imagenOferta);
                                        $ext = end($partes);
                                        $img->imagenOferta = str_replace('.' . $ext, '', $img->imagenOferta) . '-large.' . $ext;
                                        echo $this->rofertas . $img->imagenOferta
                                        ?>"/>
                                    </a>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <div class="col-md-4">
            <div class="fluid-list info-cupon">
                <?php if ($this->identity()['flagcheckboxLogo']) { ?>
                <figure>
                    <img src="<?= $this->rlogos . $cupon->LogoEmpresa ?>"/>
                </figure>
                <?php }?>
                <h1>
                    <?php if ($cupon->datoBeneficio != null) : ?>

                        <?php if ($cupon->idTipoBeneficio == 1) : ?>
                            <strong>-<?= $cupon->datoBeneficio ?>% Descuento</strong>
                        <?php elseif ($cupon->idTipoBeneficio == 2) : ?>
                            <strong>-S/.<?= $cupon->datoBeneficio ?> Descuento</strong>
                        <?php elseif ($cupon->idTipoBeneficio == 3) : ?>
                            <strong><?= $cupon->datoBeneficio ?> en</strong>
                        <?php else : ?>
                            <strong><?= $cupon->datoBeneficio ?></strong>
                        <?php endif; ?>

                    <?php endif; ?>
                    <?= $cupon->TituloOferta ?>
                </h1>
                <?php if ($cupon->EstadoOferta == 'Publicado' and $cupon->caducadoTiempo >= 0 and $cupon->Stock >= 1) : ?>
                    <?php if ($cupon->TipoAtributo == 'Split') : ?>
                        <a href="#" class="btn btn-primary btn-cupon btn-full" data-toggle="modal"
                           data-target="#elegirOpcion">
                            <span>Elegir Cupón</span>
                        </a>
                    <?php else : ?>
                        <a href="#" class="btn btn-primary btn-cupon btn-full" data-toggle="modal"
                           data-target="#enviarMail">
                            <span>Descargar Cupón</span>
                        </a>
                    <?php endif; ?>
                <?php else : ?>
                    <a class="btn btn-primary btn-cupon btn-full" style="cursor: default;background: #609EE8">
                        <span>Beneficio Caducado</span></a>
                <?php endif; ?>

                <?php if ($cupon->vigencia != null) :
                    $date = new DateTime($cupon->vigencia);
                    $mes = $date->format('m');
                    ?>
                    <em>Cupón válido hasta
                        el <?php echo ' ' . $date->format('d') . ' de ' . $this->meses[$mes - 1] ?></em>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="fluid-list content-cupon">
        <div class="container">
            <div class="body-cupon">
                <h3>Condiciones de uso</h3>
                <?php echo $cupon->condicionesUso; ?>
                <h3>Sobre la empresa</h3>
                <p><?php echo $cupon->DescripcionEmpresa; ?></p>
                <h3>Locales</h3>
                <p>Dirección:  <?= $cupon->DireccionOferta ?><br>
                    Teléfono: <?= $cupon->TelefonoOferta ?><br>
                    <?php if ($cupon->webEmpresa != null) : ?>
                        Sitio Web: <?= $cupon->webEmpresa ?>
                    <?php endif; ?>
                </p>
                <?php if (count($this->tarjetas) > 0) : ?>
                <h3>Tarjetas TEBCA</h3>
                <?php foreach ($this->tarjetas as $data) : ?>
                    <div class="cnt-tarjetas">
                        <h4>
                            <img src="/img/<?= $data->Imagen ?>" alt="<?= $data->Descripcion ?>">
                        </h4>
                        <p><?= $data->Descripcion ?></p>
                    </div>
                <?php endforeach; ?>
                <?php endif; ?>
                <?php if (strlen(trim($cupon->CondicionesTebca)) > 0) : ?>
                    <h3>Legal</h3>
                    <p><?= $cupon->CondicionesTebca ?></p>
                <?php endif; ?>
                <h3>Legal</h3>
                <p><?= $this->conf['termcondiciones'] ?></p>
            </div>
        </div>
    </div>
</div>

<?php
    if ($cupon->TipoAtributo == 'Split') {
        echo $this->partial('application/index/renders/_modal_opcion');
    }
    echo $this->partial('application/index/renders/_ofertasrelacionadas');
    echo $this->partial('application/index/_domain'); ?>
</div>
</div>
