<div class="modal fade" tabindex="-1" role="dialog" id="flyoutMovil">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <div id="flyout" class="modal-body">
                <h4>¡Felicitaciones!</h4>
                <p>Tienes <?= $this->identity()["puntos"] ?> puntos disponibles para usarlos en Beneficios especiales.</p>
                <a href="<?= $this->url('puntos') ?>">¡Descúbrelos aquí!</a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->