<?php $ofertas = $this->ofertas_relacionadas; ?>
<div class="fluid-list flujo-cupones cupones_interes title-bloques">
    <h3 class="title-interna">Estos otros beneficios te pueden interesar</h3>
    <?php for ($i = 0; $i <= 2; $i++) {
        if (isset($ofertas[$i])) { ?>
            <div class="fluid-list margin-b">
                <div class="fluid-list cupon-two">
                    <a href="/<?= $category?>/coupon/<?= $ofertas[$i]->SlugOferta ?>">
                        <figure>
                            <img src="<?php
                            echo $this->rofertas . $ofertas[$i]->imagenOferta
                            ?>" title=""/>
                        </figure>
                    </a>
                    <div class="info-cupon-l">
            <?php if ($this->identity()['flagcheckboxLogo']) { ?>
                        <figure class="left">
                            <a href="/company/<?= $ofertas[$i]->SlugEmpresa ?>">
                                <img src="<?php
                                $trozos = explode(".", $ofertas[$i]->LogoEmpresa);
                                $ext = end($trozos);
                                $ofertas[$i]->LogoEmpresa = str_replace('.' . $ext, '', $ofertas[$i]->LogoEmpresa) . '-small.' . $ext;
                                echo $this->rlogos . $ofertas[$i]->LogoEmpresa ?>"/>
                            </a>
                        </figure>
                <?php } ?>
                        <div class="info-interna left">
                            <h2>
                                <a href="/<?= $category?>/coupon/<?= $ofertas[$i]->SlugOferta ?>" class="title-short">
                                    <?php
                                    $tamaño = 38;
                                    if ($ofertas[$i]->datoBeneficio != null) { ?>

                                        <?php if ($ofertas[$i]->idTipoBeneficio == 1) { ?>
                                            <strong>-<?= $ofertas[$i]->datoBeneficio ?>% Dscto. </strong>
                                        <?php } elseif ($ofertas[$i]->idTipoBeneficio == 2) { ?>
                                            <strong>-S/.<?= $ofertas[$i]->datoBeneficio ?> Dscto. </strong>
                                        <?php } elseif ($ofertas[$i]->idTipoBeneficio == 3) { ?>
                                            <strong><?= $ofertas[$i]->datoBeneficio ?> en</strong>
                                        <?php } else { ?>
                                            <strong><?= $ofertas[$i]->datoBeneficio ?></strong>
                                        <?php } ?>

                                        <?php
                                    } else {
                                        $tamaño = 58;
                                    }

                                    if (strlen($ofertas[$i]->TituloCortoOferta) >= $tamaño) {
                                        echo substr($ofertas[$i]->TituloCortoOferta, 0, $tamaño) . "...";
                                    } else {
                                        echo $ofertas[$i]->TituloCortoOferta;
                                    }
                                    ?>
                                </a>
                            </h2>
                        </div>
                    </div>
                </div>
                <div class="fluid-list desc-list">
                    <a href="/company/<?= $ofertas[$i]->SlugEmpresa ?>">Descubre más ofertas de la tienda ›</a>
                </div>
            </div>
        <?php }
    } ?>

    <?php for ($i = 3; $i <= 5; $i++) {
        if (isset($ofertas[$i])) { ?>
            <div class="fluid-list margin-b">
                <div class="fluid-list cupon-two">
                    <a href="/<?= $category?>/coupon/<?= $ofertas[$i]->SlugOferta ?>">
                        <figure>
                            <img src="<?= $this->rofertas . $ofertas[$i]->imagenOferta ?>" title=""/>
                        </figure>
                    </a>
                    <div class="info-cupon-l">
            <?php if ($this->identity()['flagcheckboxLogo']) { ?>
                        <figure class="left">
                            <a href="/company/<?= $ofertas[$i]->SlugEmpresa ?>">
                                <img src="<?php
                                $trozos = explode(".", $ofertas[$i]->LogoEmpresa);
                                $ext = end($trozos);
                                $ofertas[$i]->LogoEmpresa = str_replace('.' . $ext, '', $ofertas[$i]->LogoEmpresa) . '-small.' . $ext;
                                echo $this->rlogos . $ofertas[$i]->LogoEmpresa ?>"/>
                            </a>
                        </figure>
                <?php } ?>
                        <div class="info-interna left">
                            <h2>
                                <a href="/<?= $category?>/coupon/<?= $ofertas[$i]->SlugOferta ?>" class="title-short">
                                    <?php
                                    $tamaño = 38;
                                    if ($ofertas[$i]->datoBeneficio != null) { ?>

                                        <?php if ($ofertas[$i]->idTipoBeneficio == 1) { ?>
                                            <strong>-<?= $ofertas[$i]->datoBeneficio ?>% Dscto. </strong>
                                        <?php } elseif ($ofertas[$i]->idTipoBeneficio == 2) { ?>
                                            <strong>-S/.<?= $ofertas[$i]->datoBeneficio ?> Dscto. </strong>
                                        <?php } elseif ($ofertas[$i]->idTipoBeneficio == 3) { ?>
                                            <strong><?= $ofertas[$i]->datoBeneficio ?> en</strong>
                                        <?php } else { ?>
                                            <strong><?= $ofertas[$i]->datoBeneficio ?></strong>
                                        <?php } ?>

                                        <?php
                                    } else {
                                        $tamaño = 58;
                                    }

                                    if (strlen($ofertas[$i]->TituloCortoOferta) >= $tamaño) {
                                        echo substr($ofertas[$i]->TituloCortoOferta, 0, $tamaño) . "...";
                                    } else {
                                        echo $ofertas[$i]->TituloCortoOferta;
                                    }
                                    ?>
                                </a>
                            </h2>
                        </div>
                    </div>
                </div>
                <div class="fluid-list desc-list">
                    <a href="/company/<?= $ofertas[$i]->SlugEmpresa ?>">Descubre más ofertas de la tienda ›</a>
                </div>
            </div>
        <?php }
    } ?>
</div>