<?php
    if (empty($this->identity()))
    {
        $this->layout('error/404_logout');
    }
?>
		<!-- Content Header (Page header) -->
        <section class="content-header">
        	<br><br><br>
          <h1 class="box-title">
            404 Error Page
          </h1>
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">404 error</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="error-page">
            <h2 class="headline text-yellow"> 404</h2>
            <div class="error-content">
              <h3><i class="fa fa-warning text-yellow"></i> Oops! Page not found.</h3>
              <p>
                We could not find the page you were looking for.
                Meanwhile, you may <a href="/">return to dashboard</a> or try using the search form.
              </p>
            </div><!-- /.error-content -->
          </div><!-- /.error-page -->
        </section><!-- /.content -->