<!DOCTYPE html>
<html>
<head>
	<title>404 Page Not Found</title>
	<style type="text/css">
		body{
			background-color: #d2d6de;
			font-family: monospace;
			margin: 0px;
		}
		.page_404
		{
			margin: 0 auto;
  			text-align: center;
  			color: #444444;
  			margin-top: 100px;
		}
		.page_404 h1
		{
			font-size: 160px;
  			margin: 0px;
		}
		.page_404 h2
		{
			font-size: 60px;
  			margin: 0px;
		}
		footer{
			position: absolute;
			height: 150px;
			width: 100%;
			background-color: #4a5d63;
			bottom: 0;
			text-align: center;
		}
		footer section{
			height: 50px;
  			background-color: #334144;
  			margin-top: 70px;
  			padding-top: 30px;
		}
		footer section span{
			color: #fff;
			font-size: 16px;
		}

	</style>
</head>
<body>
	<section class="page_404">
		<h1>404</h1>
		<h2>NOT FOUND.</h2>
	</section>
	<footer>
		<section>
			<span>
				Beneficios - <?php echo date('Y') ?>
			</span>
		</section>
	</footer>
</body>
</html>