<?php
/**
 * Created by PhpStorm.
 * User: marlo
 * Date: 08/01/16
 * Time: 10:00 AM
 */
?>
    <section class="content-header ">
        <br><br><br>
        <h1 class="box-title">Reporte de Proveedor Campañas</h1>
        <br>

        <div style="clear:both;"></div>
        <?php
        if ($this->flashMessenger()->setNamespace('success')->hasMessages()) {
            echo '<div class="callout alert alert-success"><button class="close" data-dismiss="alert" type="button">×</button>';
            $messages = $this->flashMessenger()->getMessages();
            foreach ($messages as $message) {
                echo $message;
            }
            echo '</div>';
        } elseif ($this->flashMessenger()->setNamespace('error')->hasMessages()) {
            echo '<div class="callout alert alert-error"><button class="close" data-dismiss="alert" type="button">×</button>';
            $messages = $this->flashMessenger()->getMessages();
            foreach ($messages as $message) {
                echo $message;
            }
            echo '</div>';
        }
        ?>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                    </div>
                    <div class="box-body">
                        <div class="col-md-12">
                            <?php
                            $form->setAttribute('action', $this->url('proveedor-campanias', array('action' => 'export')));
                            $form->setAttribute('id', 'form-reporte2');
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            echo $this->formElement($form->get('csrf'));

                            ?>
                            <div class="row">
                                <fieldset>
                                    <div class="col-md-12">
                                        <div class="col-md-2"><label>Empresa :</label></div>

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <?php if ($this->type == "proveedor"):
                                                    echo "<label>$this->nombre</label>";
                                                endif; ?>
                                                <?= $this->formRow($form->get('empresa')); ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-2"><label>Campaña :</label></div>

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <?= $this->formRow($form->get('campania')); ?>
                                            </div>
                                        </div>
                                    </div>
                                    <br><br>
                                    <div class="form-group">
                                        <div class="col-md-offset-6 col-md-6 text-right">
                                            <?= $this->formSubmit($form->get('submit')); ?>
                                        </div>
                                    </div>
                                </fieldset>
                                <?php echo $this->form()->closeTag(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php
$this->inlineScript()->appendFile($this->basePath('js/puntos/reporte-proveedor-ofertas.js'));
