<!--/**
 * Created by PhpStorm.
 * User: luisvar
 * Date: 11/09/15
 * Time: 11:17 AM
 */-->

<section class="content-header ">
    <br><br><br>
    <h1 class="box-title">Registrar Categoria</h1>
    <br>
    <?php if (isset($msg)) {
        echo '<div class="callout alert alert-' . $alert . '"><button class="close" data-dismiss="alert" type="button">×</button>';
        foreach ($msg as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</div>';
    } ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form->setAttribute('action', $this->url('categoria', array('action' => 'add')));
                        $form->setAttribute('class', 'form-horizontal');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));

                        ?>
                        <div class="form-group">
                            <div class=" <?= $this->formElementErrors($form->get('NombrePais')) ? 'has-error' : ''?>">
                                <div class="col-md-2 col-md-offset-2"><label>País:</label></div>
                                <div class="col-md-4">
                                    <div class="row-fluid campo">
                                        <div class="col-md-11 null-padding input-2">
                                            <?php
                                            echo $this->formHidden($form->get('id'));
                                            echo $this->formRow($form->get('NombrePais'));
                                            ?>
                                        </div>
                                        <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="<?= (isset($errors['repeatc'])) ? $errors['repeatc'] : ''; ?> <?=$this->formElementErrors($form->get('Nombre')) ? 'has-error' : ''?>">
                                <div class="col-md-2 col-md-offset-2"><label>Nombre:</label></div>
                                <div class="col-md-7">
                                    <div class="row-fluid campo">
                                        <div class="col-md-11 null-padding input-2">
                                            <?php echo $this->formRow($form->get('Nombre')); ?>
                                            <?= (isset($errors['repeat'])) ? '<ul><li>' . $errors['repeat'] . '</li></ul>' : ''; ?>
                                        </div>
                                        <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-col-12 <?=$this->formElementErrors($form->get('Descripcion')) ? 'has-error' : ''?>">
                                <div class="col-md-2 col-md-offset-2"><label>Descripción:</label></div>
                                <div class="col-md-7">
                                    <div class="row-fluid campo">
                                        <div class="col-md-11 null-padding input-2">
                                            <?php echo $this->formRow($form->get('Descripcion')); ?>
                                        </div>
                                        <div class="col-md-1 null-padding text-center p"><p></p></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-10 col-md-2">
                                <p>(*) Campos Obligatorios</p>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="col-md-10">
                                <?= $this->formSubmit($form->get('submit')); ?>
                                <a href="/categoria" class="btn btn-default">Cancelar</a>
                            </div>
                        </div>
                        <hr>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php include('_scriptcategoria.phtml');?>