<section class="content-header ">
    <br><br><br>
    <h1 class="box-title">Lista de Categorías</h1>
    <br><br>
    <?php if ($this->flashMessenger()->hasMessages()) {
        echo '<div class="callout alert alert-success"><button class="close" data-dismiss="alert" type="button">×</button>';
        $messages = $this->flashMessenger()->getMessages();
        foreach($messages as $message) {
            echo $message;
        }
        echo '</div>';
    } ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form->setAttribute('action', $this->url('categoria', array('action' => 'index')));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));

                        ?>
                        <div class="row">
                            <fieldset>
                                <legend>Buscar por:</legend>
                                <div class="form-group">
                                    <label class="col-md-2">País:</label>
                                    <div class="col-md-5">
                                        <?php
                                        echo $this->formRow($form->get('Pais'));
                                        ?>
                                    </div>
                                    <div class="col-md-1"><label>Nombre:</label></div>
                                    <div class="col-md-4">
                                        <?php
                                        echo $this->formRow($form->get('Nombre'));
                                        ?>
                                    </div>
                                </div>
                                <div style="clear:both;"></div>
                                <br>
                                <div class="col-md-12 text-right">
                                    <?php
                                    echo $this->formSubmit($form->get('submit'));
                                    ?>
                                </div>
                            </fieldset>
                        </div>
                        <hr>
                        <?php
                        echo $this->form()->closeTag();
                        ?>
                    </div>

                    <div class="dataTables_wrapper form-inline dt-bootstrap" id="example1_wrapper">
                        <div class="row-fluid">
                            <div class="col-md-12 text-right">
                                <div id="example1_length" class="dataTables_length"><br>
                                    <a href="<?php echo $this->url('categoria',array('action'=>'export'));?>"
                                       class="btn btn-primary">Exportar</a>
                                </div>
                            </div>
                        </div>
                        <div style="clear:both;"></div>
                        <br>

                        <div class="row-fluid">
                            <div class="col-sm-12">
                                <table aria-describedby="example1_info" role="grid" id="example1" class="table table-bordered table-striped dataTable">
                                    <thead>
                                    <tr role="row">
                                        <th>
                                            <?php if ($order_by == 'Pais'): ?>
                                                <a href="<?= $this->url('categoria', array('order_by' => 'Pais', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">País</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('categoria', array('order_by' => 'Pais', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">País</a>
                                            <?php endif; ?>
                                        </th>
                                        <th>
                                            <?php if ($order_by == 'Nombre'): ?>
                                                <a href="<?= $this->url('categoria', array('order_by' => 'Nombre', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Nombres</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('categoria', array('order_by' => 'Nombre', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Nombre</a>
                                            <?php endif; ?>
                                        </th>
                                        <th>
                                            <?php if ($order_by == 'Descripcion'): ?>
                                                <a href="<?= $this->url('categoria', array('order_by' => 'Descripcion', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Descripción</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('categoria', array('order_by' => 'Descripcion', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Descripción</a>
                                            <?php endif; ?>
                                        </th>
                                        <th><a>Editar</a></th>
                                        <th>
                                            <?php if ($order_by == 'Activo'): ?>
                                                <a href="<?= $this->url('categoria', array('order_by' => 'Eliminado', 'order' => $order, 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Activo</a>
                                            <?php else: ?>
                                                <a href="<?= $this->url('categoria', array('order_by' => 'Eliminado', 'order' => 'asc', 'page' => $p, 'q1' => $q1, 'q2' => $q2)); ?>">Activo</a>
                                            <?php endif; ?>
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php if(count($categorias)>0){
                                        foreach ($categorias as $dato) : ?>
                                            <tr data-id="<?php echo $dato->id ?>">
                                                <td><?php echo $this->escapeHtml($dato->NombrePais);?></td>
                                                <td><?php echo $this->escapeHtml($dato->Nombre);?></td>
                                                <td><?php echo $this->escapeHtml($dato->Descripcion);?></td>
                                                <td>
                                                    <a href="<?php echo $this->url('categoria',array('action'=>'edit','id' => $dato->id));?>">
                                                        <i class="btn btn-warning fa fa-pencil-square-o"></i></a></td>
                                                </td>
                                                <td>
                                                    <?php if($dato->Eliminado==1): ?>
                                                        <input id="elim<?php echo $dato->id ?>" name="<?php echo $dato->Eliminado ?>"
                                                               class="elim" type="checkbox">
                                                    <?php else: ?>
                                                        <input id="elim<?php echo $dato->id ?>" name="<?php echo $dato->Eliminado ?>"
                                                               class="elim" type="checkbox" checked>
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach;
                                    }else{
                                        echo '<tr><td colspan="10">No hay Categorias Registradas</td></tr>';
                                    }?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div><!-- /.box-body -->
                <div class="col-md-4"><br>

                    <p>
                        <?= (($categorias->getCurrentPageNumber() * $categorias->getItemCountPerPage()) -
                            ($categorias->getItemCountPerPage() - 1)); ?>
                        -
                        <?= ($categorias->getCurrentPageNumber() * $categorias->getItemCountPerPage() <
                            $categorias->getTotalItemCount())
                            ? $categorias->getCurrentPageNumber() * $categorias->getItemCountPerPage()
                            : $categorias->getTotalItemCount() ?> de
                        <?= $categorias->getTotalItemCount(); ?> Registros
                    </p>
                </div>
                <?=$this->paginationControl($categorias, 'Sliding', 'paginator-categoria', array('order_by' => $order_by,'order' => ($order=='asc') ?$order='desc' : 'asc', 'q1' => $q1, 'q2' => $q2)); ?>
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section>
<?= $this->headScript()->prependFile($this->basePath('js/categoria/categoria_index.js?'.$this->configItem('version_script'))); ?>