<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <?php echo $this->partial('layout/renders/_head') ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

    <?php echo $this->partial('layout/renders/_header') ?>

    <!-- =============================================== -->

    <?php echo $this->partial('layout/renders/_siderbar') ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <br><br><br>
            <h1 class="box-title">
                500 Error Page
            </h1>
            <ol class="breadcrumb">
                <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">500 error</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="error-page">
                <h2 class="headline text-yellow"> 500</h2>
                <div class="error-content">
                    <h3><i class="fa fa-warning text-yellow"></i> Oops! Ocurrio un error.</h3>
                    <p>
                        Estamos trabajando para poder encontrar el error.
                    </p>
                </div><!-- /.error-content -->
            </div><!-- /.error-page -->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <?php echo $this->partial('layout/renders/_footer') ?>

    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div><!-- ./wrapper -->
</body>
</html>