<?php if ($this->pageCount): ?>
<div class="box-footer clearfix">
  	<ul class="pagination pagination-sm no-margin pull-right">
        <li class="<?=!isset($this->previous) ? 'disabled' : ''; ?>">
        	<a href="<?=$this->url('paquete', array('action' => 'list','page' => $this->first, 'order_by' => $order_by,'order' => ($order == 'asc') ? $order = 'desc' : 'asc', 'q1' => $q1, 'q2' => $q2, 'q3' => $q3, 'q4' => $q4)); ?>">«</a>
        </li>
        <?php foreach ($this->pagesInRange as $page): ?>
        <li class="<?=$page == $this->current ? 'active' : ''; ?>">
        	<a href="<?=$this->url('paquete', array('action' => 'list','page' => $page, 'order_by' => $order_by,'order' => ($order == 'asc') ? $order = 'desc' : 'asc', 'q1' => $q1, 'q2' => $q2, 'q3' => $q3, 'q4' => $q4)); ?>"><?=$page; ?></a>
        </li>
    	<?php endforeach; ?>
        <li class="<?=!isset($this->next) ? 'disabled' : ''; ?>">
        	<a href="<?=$this->url('paquete', array('action' => 'list','page' => $this->last, 'order_by' => $order_by,'order' => ($order == 'asc') ? $order = 'desc' : 'asc', 'q1' => $q1, 'q2' => $q2, 'q3' => $q3, 'q4' => $q4)); ?>">»</a>
        </li>
	</ul>
</div>
<?php endif; ?>