<?php
const TIPO_OFERTA_LEAD = 'Lead';
const TIPO_OFERTA_DESCARGA = 'Descarga';
const TIPO_OFERTA_PRESENCIA = 'Presencia';
?>
    <section class="content-header ">
        <br><br><br>

        <h1 class="box-title">Paquetes Comprados</h1>
        <br>

        <div style="clear:both;"></div>
        <?php if ($this->flashMessenger()->hasMessages()) {
            echo '<div class="callout alert alert-success">' .
                '<button class="close" data-dismiss="alert" type="button">×</button>';
            $messages = $this->flashMessenger()->getMessages();
            foreach ($messages as $message) {
                echo $message;
            }
            echo '</div>';
        } ?>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                    </div>
                    <div class="box-body">
                        <div class="col-md-12">
                            <?php
                            $form->setAttribute('action', $this->url('paquetes-comprados', array('action' => 'index')));
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            echo $this->formElement($form->get('csrf'));

                            ?>
                            <div class="row">
                                <fieldset>
                                    <legend>Buscar por:</legend>
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">Paquete:</label>

                                        <div class="col-md-4">
                                            <?= $this->formRow($form->get('Paquete')); ?>
                                        </div>
                                        <label class="col-md-2 control-label">Factura:</label>

                                        <div class="col-md-4">
                                            <?= $this->formRow($form->get('Factura')); ?>
                                        </div>
                                    </div>
                                    <br><br>

                                    <div class="form-group">
                                        <label class="col-md-2">Fecha de Compra:</label>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-calendar"></i>
                                                    </div>
                                                    <?= $this->formRow($form->get('FechaInicio')); ?>
                                                </div>
                                            </div>
                                        </div>
                                        <label class="col-md-2">Hasta :</label>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-calendar"></i>
                                                    </div>
                                                    <?= $this->formRow($form->get('FechaFin')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <br><br>

                                    <div class="form-group">
                                        <div class="col-md-offset-6 col-md-6 text-right">
                                            <?= $this->formSubmit($form->get('submit')); ?>
                                        </div>
                                    </div>

                                </fieldset>
                                <hr>
                                <?php
                                echo $this->form()->closeTag();
                                ?>
                            </div>

                            <div class="dataTables_wrapper form-inline dt-bootstrap" id="example1_wrapper">
                                <div class="row-fluid">
                                    <div class="col-md-12 text-right">
                                        <div id="example1_length" class="dataTables_length"><br>
                                            <a href="<?php echo $this->url('paquetes-comprados', array('action' => 'export',
                                                'q1' => $q1, 'q2' => $q2, 'q3' => $q3, 'q4' => $q4)); ?>"
                                               class="btn btn-primary">Exportar</a>
                                        </div>
                                    </div>
                                </div>
                                <div style="clear:both;"></div>
                                <br>

                                <div class="row-fluid">
                                    <div class="col-sm-12">
                                        <table aria-describedby="example1_info" role="grid" id="example1"
                                               class="table table-bordered table-striped dataTable">
                                            <thead>
                                            <tr role="row">
                                                <th><a>Fecha de Compra</a></th>
                                                <th><a>Tipo de Paquete</a></th>
                                                <th><a>Paquete</a></th>
                                                <th><a>Precio</a></th>
                                                <th><a>Cantidad</a></th>
                                                <th><a>Factura</a></th>
                                                <th><a>Descripción</a></th>
                                                <th><a>Asesor</a></th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <?php
                                            if (isset($paquetes) && count($paquetes)):
                                                foreach ($paquetes as $dato) : ?>
                                                    <tr data-id="<?php echo $dato->id ?>">
                                                        <td width="100"><?php echo $this->escapeHtml($dato->FechaCompra); ?></td>
                                                        <td width="100"><?php echo $this->escapeHtml($dato->TipoPaquete); ?></td>
                                                        <td width="100"><?php echo $this->escapeHtml($dato->NombrePaquete); ?></td>
                                                        <td width="100">
                                                            S/. <?php echo $this->escapeHtml($dato->Precio); ?>
                                                        </td>
                                                        <td width="100">
                                                            <?php if ($dato->TipoPaquete == TIPO_OFERTA_DESCARGA) { ?>
                                                                <?php echo $this->escapeHtml($dato->Cantidad) != 1
                                                                    ? $this->escapeHtml((int)$dato->Cantidad) . ' Descargas' : '1 Descarga'; ?>
                                                            <?php } elseif ($dato->TipoPaquete == TIPO_OFERTA_PRESENCIA) { ?>
                                                                <?php echo $this->escapeHtml($dato->Cantidad) != 1
                                                                    ? $this->escapeHtml((int)$dato->Cantidad) . ' Días' : '1 Día'; ?>
                                                            <?php } elseif ($dato->TipoPaquete == TIPO_OFERTA_LEAD) { ?>
                                                                <?php echo $this->escapeHtml($dato->Cantidad) != 1
                                                                    ? $this->escapeHtml((int)$dato->Cantidad) . ' Leads' : '1 Lead'; ?>
                                                            <?php } ?>
                                                        </td>
                                                        <td width="100"><?php echo $this->escapeHtml($dato->Factura); ?></td>
                                                        <td width="100">
                                                            <?php if ($dato->TipoPaquete != TIPO_OFERTA_LEAD) { ?>
                                                                <a class="popup">
                                                                    <i class="btn btn-info fa fa-eye">
                                                                    </i>
                                                                </a>
                                                            <?php } ?>
                                                        </td>
                                                        <td width="100"><?php echo $this->escapeHtml($dato->Apellidos . " " . $dato->Nombres); ?></td>
                                                    </tr>
                                                <?php endforeach;
                                            else: ?>
                                                <tr>
                                                    <td colspan="7">No hay Paquetes Asignados</td>
                                                </tr>
                                            <?php endif; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <p>
                                <?php if (isset($paquetes) && count($paquetes)): ?>
                                    <?= (($paquetes->getCurrentPageNumber() * $paquetes->getItemCountPerPage()) -
                                        ($paquetes->getItemCountPerPage() - 1)); ?>
                                    -
                                    <?= ($paquetes->getCurrentPageNumber() * $paquetes->getItemCountPerPage() <
                                        $paquetes->getTotalItemCount())
                                        ? $paquetes->getCurrentPageNumber() * $paquetes->getItemCountPerPage()
                                        : $paquetes->getTotalItemCount() ?> de
                                    <?= $paquetes->getTotalItemCount(); ?> Registros
                                <?php endif; ?>
                            </p>
                        </div>
                        <?php
                        if (isset($paquetes)):
                            echo $this->paginationControl($paquetes, 'Sliding', 'paginator-paqcomp', array('page' => $p,
                                'q1' => $q1, 'q2' => $q2, 'q3' => $q3, 'q4' => $q4));
                        endif;
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript" src="<?= $this->basePath('js/paquete/paquete_comprado.js?'.$this->configItem('version_script')); ?>"></script>
<?php include_once('_modaldetalle.phtml');