<!-- Modal Eliminar -->
<div class="modal fade" id="modalEliminar" tabindex="-1" role="dialog" aria-labelledby="modalEliminarLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalEliminarLabel">Eliminar Puntos</h4>
            </div>
            <div class="modal-body">
                <h4>¿está seguro de que quiere eliminar ?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" data-toggle="modal"
                        data-target="#modalComentario">Si
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Comentario -->
<div class="modal fade" id="modalComentario" tabindex="-1" role="dialog" aria-labelledby="modalComentarioLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalEliminarLabel">Eliminar Puntos</h4>
            </div>
            <div class="modal-body">
                <div class="row" style="text-align: center">
                    <div class="form-group">
                        <div class="col-md-12">
                            <h4>Puede dejarnos un comentario acerca de la eliminación:</h4>
                        </div>
                        <div class="col-md-12">
                            <textarea style="max-width: 560px; max-height: 120px; min-height: 75px; resize: none"
                                      class="form-control" title="comentario" id="razonEliminado" rows="8"></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="finalizarEliminado">Finalizar</button>
            </div>
        </div>
    </div>
</div>