<!-- botton action-->
<button type="button" class="btn btn-primary btn-lg hide" id="btn_modal" data-toggle="modal" data-target="#myModal">
</button>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button id="btn_close_modal" type="button" class="close" data-dismiss="modal"
                        aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Asignar</h4>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <input id="idempresa" class="form-control" type="hidden">

                        <div class="col-md-6">
                            <div class="col-md-4">
                                <label for="empresa">Empresa</label>
                            </div>
                            <div class="col-md-8">
                                <input id="empresa" class="form-control" type="text" disabled>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="col-md-6">
                                <label for="tipo">Tipo de Empresa</label>
                            </div>
                            <div class="col-md-6">
                                <input id="tipo" class="form-control" type="text" disabled>
                            </div>
                        </div>
                    </div>
                    <br><br>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-2">
                                <label>Subgrupo</label>
                            </div>
                            <div class="col-md-10" id="subgrupos">
                                <div class="col-md-5">
                                    <label>
                                        <input type="checkbox">Platino
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="enviar" type="button" class="assignSub btn btn-primary">Asignar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>