<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>WEEARE</title>
</head>
<style media="screen">
    body{
        background-color: #2b3036;
    }
    h2{
        width: 100%;
        text-align: center;
        color: #6A7582;
        position: absolute;
        top: 50%;
        margin-top: 50px;
        margin-left: 0;
        font-family: Arial, Helvetica;
        letter-spacing: 1px;
        font-size: 20px;
    }
    .logo{
        position: absolute;
        top: 50%;
        left: 50%;
        margin-left: -150px;
        margin-top: -50px;
    }
</style>

<body>

<!-- LOGO -->
<img src="<?=$this->basePath('img/login.png')?>" alt="" class="logo">

<h2>...estamos trabajando</h2>
</body>
</html>