<section>
    <div class="container">
        <div class="fluid-list cnt-content-user">
            <h3>Bienvenid@ <span><?= $this->identity()["Nombre"] . ' ' . $this->identity()["Apellido"] ?></span></h3>
            <div class="row">
                <?php echo $this->partial('perfil/perfil/_sidebar') ?>
                <div class="col-md-9">
                    <div class="fluid-list cnt-mis-datos">
                        <h3>Premios Utilizados</h3>
                        <div class="fluid-list cnt-puntos-o">
                            <p><a href="<?= $this->url('perfil-premios', array('action' => 'pdfUtilizados')); ?>"><span></span> Descargar Listado de Premios Utilizados (PDF)</a></p>
                        </div>
                        <div class="fluid-list cnt-table-user cnt-user-descargado">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Descripción</th>
                                    <th>Fecha de uso</th>
                                    <th>Premios Usados</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($this->utilizados as $value) { ?>
                                    <tr>
                                        <td>
                                            <?= $value->TituloCorto ?>
                                        </td>
                                        <td><?= date('d/m/Y', strtotime($value->FechaRedimido)) ?></td>
                                        <td class="p-saldo"><?= $value->PremiosUtilizados ?></td>
                                    </tr>
                                <?php } ?>
                                </tbody>
                            </table>
                            <?php
                            if (isset($this->utilizados)) {
                                echo $this->paginationControl(
                                    $this->utilizados,
                                    'Sliding',
                                    'paginator-utilizados-premios'
                                );
                            } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>