<div class="modal fade" id="modalColaborador" tabindex="-1" role="dialog" aria-labelledby="modalColaboradorLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title">Referidos del Cliente/Colaborador</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="form-group lista-referidos">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
