<section class="content-header ">
    <br><br><br>

    <h1>Asignar Paquete</h1>
    <br><br>
    <?php if (isset($msg)) {
        echo '<div class="callout alert alert-' . $alert . '"><button class="close" data-dismiss="alert" type="button">×</button>';
        foreach ($msg as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</div>';
    } ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form->setAttribute('action', $this->url('paquete', array('action' => 'assing')));
                        $form->setAttribute('id', 'form');
                        $form->setAttribute('class', 'form-horizontal');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));

                        ?>
                        <fieldset>
                            <legend>Seleccione Empresa:</legend>
                            <div class="form-group">
                                <div class
                                "<?php if (isset($errors['empresa'])) {
                                    echo $errors['empresa'];
                                } ?> <?= $this->formElementErrors($form->get('BNF_Empresa_id')) ? 'has-error' : '' ?>">
                                <div class="col-md-2"><label>Nombre Comercial o Razón Social o RUC:</label></div>
                                <div class="col-md-10">
                                    <div class="row-fluid campo">
                                        <div class="col-md-11 null-padding input">
                                            <?php
                                            echo $this->formHidden($form->get('id'));
                                            echo $this->formRow($form->get('BNF_Empresa_id'));
                                            ?>
                                        </div>
                                        <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <hr>
                        <fieldset>
                            <legend>Seleccione Paquete:</legend>
                            <div class="form-group">
                                <div
                                    class="">
                                    <div class="col-md-2"><label>País:</label></div>
                                    <div class="col-md-5">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?php echo $this->formElement($form->get('NombrePais')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p></p></div>
                                        </div>
                                    </div>
                                </div>
                                <div
                                    class="<?= $this->formElementErrors($form->get('BNF_TipoPaquete_id')) ? 'has-error' : '' ?>">
                                    <div class="col-md-1"><label>Tipo de Paquete:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input-2">
                                                <?php echo $this->formRow($form->get('BNF_TipoPaquete_id')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p></p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?php if (isset($errors['paquete'])) {
                                    echo $errors['paquete'];
                                } ?> <?= $this->formElementErrors($form->get('BNF_Paquete_id')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Nombre de Paquete:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?php echo $this->formRow($form->get('BNF_Paquete_id')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                        <div class="col-md-11 null-padding "><p id="detail" class="help-block"></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <hr>
                        <fieldset>
                            <legend>Datos Asignación:</legend>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('FechaCompra')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Fecha de Compra:</label></div>
                                    <div class="col-md-5">
                                        <div class="row-fluid">
                                            <div class="row-fluid campo">
                                                <div class="col-md-1 null-padding"><i class="fa fa-calendar"></i></div>
                                                <div class="col-md-10 null-padding">
                                                    <?php echo $this->formRow($form->get('FechaCompra')); ?>
                                                </div>
                                                <div class="col-md-1 null-padding text-center asterisco"><p>*</p></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="<?= $this->formElementErrors($form->get('Factura')) ? 'has-error' : '' ?>">
                                    <div class="col-md-1 text-right"><label>Factura:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input-2">
                                                <?php echo $this->formRow($form->get('Factura')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div
                                    class="<?= $this->formElementErrors($form->get('BNF_Usuario_id')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Asesor:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?php echo $this->formRow($form->get('BNF_Usuario_id')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group lead hidden">
                                <div
                                    class="<?= $this->formElementErrors($form->get('MaximoLeads')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Máximo de leads:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input-2">
                                                <?php echo $this->formRow($form->get('MaximoLeads')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                                <div
                                    class="<?= $this->formElementErrors($form->get('CostoPorLead')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Costo por lead:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input-2">
                                                <?php echo $this->formRow($form->get('CostoPorLead')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-10 col-md-2">
                                    <p>(*) Campos Obligatorios</p>
                                </div>
                            </div>
                            <div class="box-footer line">
                                <?php echo $this->formSubmit($form->get('submit')); ?>
                                <a href="/paquete" class="btn btn-default">Cancelar</a>
                            </div>
                        </fieldset>
                        <hr>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php include("_scriptasignar.php"); ?>
<script type="text/javascript" src="<?= $this->basePath('js/paquete/paquete_assing.js?'.$this->configItem('version_script')); ?>"></script>
