<?php $children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0]; ?>
<div class="modal fade modal-vcenter modal-active" id="elegirOpcion" tabindex="-1" role="dialog"
     aria-labelledby="elegirOpcion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><img src="http://beneficios.pe/img/login.png"/></h4>
            </div>
            <div class="modal-body">
                <h4>Elige tu Oferta</h4>
                <?php $count = 0; ?>
                <?php foreach ($child->atributosData as $item): ?>
                    <?php if ($item->Stock > 0): ?>
                        <div class="fluid-list list-opciones">
                            <a href="<?= $this->url('delivery', array('action' => 'index', 'slug' => $child->cupon->Slug, 'id' => $item->id)); ?>">
                                <span><?= ++$count ?></span>
                                <h2><?php if ($this->identity()['flagcheckboxMoney']) {?>
                                        <span><?= $item->PrecioVentaPublico . ' puntos por ' . $item->NombreAtributo ?></span>

                                    <?php  }else{?>
                                        <span>S/. <?= $item->PrecioVentaPublico . ' por ' . $item->NombreAtributo ?></span>

                                    <?php  }?>
                                    <?php if ($item->FechaVigencia != null) :
                                        $date = new DateTime($item->FechaVigencia);
                                        $mes = $date->format('m'); ?>
                                        Cupón válido hasta el <?= '' . $date->format('d') . ' de ' . $child->meses[$mes - 1] ?>
                                    <?php endif; ?>
                                </h2>
                            </a>
                        </div>
                    <?php else: ?>
                        <div class="fluid-list list-opciones">
                            <a href="#" class="a-locked" role="button">
                                <span><?= ++$count ?></span>
                                <h2>

                                   <?php if ($this->identity()['flagcheckboxMoney']) {?>
                                       <span><?= $item->PrecioVentaPublico . ' puntos por ' . $item->NombreAtributo ?></span>

                                   <?php  }else{?>
                                       <span>S/. <?= $item->PrecioVentaPublico . ' por ' . $item->NombreAtributo ?></span>

                                   <?php  }?>



                                    <?php if ($item->FechaVigencia != null) :
                                        $date = new DateTime($item->FechaVigencia);
                                        $mes = $date->format('m'); ?>
                                        Cupón válido hasta el <?= '' . $date->format('d') . ' de ' . $child->meses[$mes - 1] ?>
                                    <?php endif; ?>
                                </h2>
                            </a>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
                <div class="footer-m-e">
                    <?php if ($this->identity()['flagcheckboxMoney']) { ?>
                        <p>Al dar clic en siguiente podrás descargar el cupón con tus puntos</p>
                    <?php } else { ?>
                        <p>Al dar clic en siguiente podrás elegir la forma de pago: soles, puntos o soles más puntos.</p>

                    <?php } ?>



                </div>
            </div>
        </div>
    </div>
</div>