<?php $children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0];
?>
<style type="text/css">
    .title-puntos {
        font-size: 20px;
        font-weight: bold;
        color: #0a0d12;;
    }

    .line-li {
        border-bottom: 2px solid #666;
    }

    .text-puntos {
        font-size: 16px;
    }
</style>
<div class="modal fade modal-vcenter modal-active" id="enviarPuntos" tabindex="-1" role="dialog"
     aria-labelledby="enviarPuntos">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><img src="/img/login.png"/></h4>
            </div>
            <div class="modal-body">
                <div class="fluid-list header-modal-c">
                    <figure>
                        <img src="<?= $child->rlogos . $child->cupon->LogoEmpresa ?>"/>
                    </figure>
                    <h2 id="tituloCupon">

                        <?php if ($this->identity()['flagcheckboxMoney']) { ?>
                            <b><?= $child->cupon->PrecioVentaPublico ?>
                               punto  por</b> <?= $child->cupon->Titulo ?>
                        <?php } else { ?>
                            <b>S/. <?= $child->cupon->PrecioVentaPublico ?>
                                por</b> <?= $child->cupon->Titulo ?>
                        <?php }?>












                    </h2>
                </div>
                <form action="" class="form-login form-modal-c" id="emailCuponPuntos" novalidate="novalidate">
                    <div class="fluid-list cnt-num-puntos">
                      <!--  <p class="text-center title-puntos">Cada punto equivale a S/.1</p>-->
                        <p class="text-center text-puntos">
                            Puntos disponibles: <span
                                id="precio-beneficio"><?= $child->clienteData->TotalAsignados ?></span>
                        </p>
                        <ul>
                            <li>
                                <div class="left label-p">Precio del Cupón:</div>
                                <div id="precio-venta" class="right num-p">
                                    <?php if ($this->identity()['flagcheckboxMoney']) { ?>

                                        <?= $child->cupon->PrecioVentaPublico ?> puntos
                                    <?php } else { ?>
                                        S/ <?= $child->cupon->PrecioVentaPublico ?>
                                     <?php }?>


                                    </div>
                            </li>
                            <li>
                                <div class="cnt-form-error">
                                    <div class="left label-p">Puntos a utilizar:</div>
                                    <div class="right num-p">
                                        <input type="text" class="form-control" name="puntos" title="puntos"
                                               id="puntos"/>
                                    </div>
                                    <br>
                                    <br>
                                    <div class="error-check"></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="fluid-list cnt-num-puntos total-puntos-u">
                        <ul>
                            <li>
                                <div class="left label-p">A pagar en el Local:</div>
                                <div class="right num-p">
                                    <div id="precio-final" data-value="<?= $child->cupon->PrecioVentaPublico ?>">



                                        <?php if ($this->identity()['flagcheckboxMoney']) { ?>

                                            <?= $child->cupon->PrecioVentaPublico ?> puntos
                                        <?php } else { ?>
                                            S/ <?= $child->cupon->PrecioVentaPublico ?>
                                        <?php }?>



                                    </div>
                                </div>
                            </li>
                            <li class="line-li"></li>
                            <li>
                                <div class="left label-p">Saldo de puntos disponibles:</div>
                                <div class="right num-p">
                                    <div id="puntos-final" data-value="<?= $child->clienteData->TotalAsignados ?>">
                                        <?= $child->clienteData->TotalAsignados ?></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="fluid-list body-cnt-c">
                        <h4>Ingrese el email en donde desea recibir este cupón</h4>

                        <div class="form-group has-feedback has-feedback-left cnt-form-error">
                            <div class="form-control-feedback">
                                <i class="glyphicon glyphicon-envelope text-muted"></i>
                            </div>
                            <input type="email" name="email" class="form-control" placeholder="Ingresa tu email"
                                   id="email" value="<?= $child->email_user ?>">
                            <input type="hidden" value="<?= $child->cupon->idOferta ?>" id="idOferta" name="idoferta">
                            <input type="hidden" value="<?= $child->empresaID ?>" id="idEmpresa" name="idEmpresa">
                            <input type="hidden" value="<?= $child->clienteID ?>" id="idCliente" name="idCliente">
                            <input type="hidden" value="<?= $child->category ?>" id="slug_cat" name="slug_cat">
                            <input type="hidden" value="" id="atributo" name="atributo">
                            <div class="error-check"></div>
                        </div>
                        <div class="checkbox cnt-form-error">
                            <label>
                                <input type="checkbox" name="terminos" id="activeChek" checked> Acepto las Condiciones, Términos
                                y Políticas de uso
                            </label>
                            <div class="error-check"></div>
                            <div class="fluid-list cnt-terminos-info">
                                <ul>
                                    <li>
                                        <p>Los datos ingresados son legítimos y correctos.</p>
                                    </li>
                                    <li>
                                        <p>Conozco el uso que se le dará a los datos que he proporcionado a Belia.</p>
                                    </li>
                                    <li>
                                        <p>Entiendo que los Proveedores son los únicos responsables por cualquier
                                            inconveniente con los bienes y servicios ofrecidos a través de la Página
                                            Web.</p>
                                    </li>
                                    <li>
                                        <p>Sé cual es la información y datos personales requeridos para poder acceder a
                                            los bienes y servicios ofrecidos a través de la Página Web.</p>
                                    </li>
                                    <li>
                                        <p>He autorizado a mi Empleador a brindar o he brindado directamente a Belia mis
                                            datos personales para poder ingresar a la Pagina Web.</p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block text-center" id="send_coupon"><span>Recibir Cupón</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>