<section class="wrapper-main">
    <style>
        .left-info-c ul li{text-align: center;}
        .tarjetas-img{width: 100px;}
    </style>
    <div class="fluid-list cnt-content-user">
        <h3>Bienvenid@ <span><?= $this->identity()["Nombre"] . ' ' . $this->identity()["Apellido"] ?></span></h3>
        <div class="fluid-list cnt-mis-datos">
            <h3>Mis Datos</h3>
            <?php if ($this->message) {
                echo '<div class="alert alert-' . $this->type . '" role="alert">';
                echo $this->message;
                echo '</div>';
            }
            ?>
            <?php
            $this->form->setAttribute('action', $this->url('perfil', array('action' => 'index')));
            $this->form->setAttribute('class', 'form-horizontal');
            $this->form->prepare();
            echo $this->form()->openTag($this->form);
            echo $this->formElement($this->form->get('csrf'));
            ?>
                <div class="form-group">
                    <label for="nombres">Nombres</label>
                    <?= $this->formRow($this->form->get('Nombre')); ?>
                </div>
                <div class="form-group">
                    <label for="apellidos">Apellidos</label>
                    <?= $this->formRow($this->form->get('Apellido')); ?>
                </div>
                <div class="form-group">
                    <label for="email">Correo Electrónico</label>
                    <?= $this->formRow($this->form->get('Correo')); ?>
                </div>
                <div class="form-group">
                    <label for="telefono">Teléfono</label>
                    <?= $this->formRow($this->form->get('Telefono')); ?>
                </div>
                <div class="form-group">
                    <?= $this->formSubmit($this->form->get('submit')); ?>
                </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</section>