<?php if ($this->pageCount): ?>
    <div class="box-footer clearfix">
        <ul class="pagination pagination-sm no-margin pull-right">
            <li class="<?= !isset($this->previous) ? 'disabled' : ''; ?>">
                <a href="<?= $this->url('oferta', array('page' => $this->first, 'order_by' => $order_by, 'order' => $order, 'q1' => $q1, 'q2' => $q2, 'q3' => $q3, 'q4' => $q4,
                    'q5' => $q5, 'q6' => $q6)); ?>">«</a>
            </li>
            <?php foreach ($this->pagesInRange as $page): ?>
                <li class="<?= $page == $this->current ? 'active' : ''; ?>">
                    <a href="<?= $this->url('oferta', array('page' => $page, 'order_by' => $order_by, 'order' => $order, 'q1' => $q1, 'q2' => $q2, 'q3' => $q3, 'q4' => $q4,
                        'q5' => $q5, 'q6' => $q6)); ?>"><?= $page; ?></a>
                </li>
            <?php endforeach; ?>
            <li class="<?= !isset($this->next) ? 'disabled' : ''; ?>">
                <a href="<?= $this->url('oferta', array('page' => $this->last, 'order_by' => $order_by, 'order' => $order, 'q1' => $q1, 'q2' => $q2, 'q3' => $q3, 'q4' => $q4,
                    'q5' => $q5, 'q6' => $q6)); ?>">»</a>
            </li>
        </ul>
    </div>
<?php endif; ?>