<html>
<head>
    <meta charset="UTF-8">
</head>
<body>
<table>
    <tr>
        <th><h3 align="center">Asignación de Puntos</h3></th>
    </tr>
    <tr>
        <td>
            <p>Se le informa que, de la campaña <i>"<?= $this->contenido["nombre"] ?>"</i> del
                tipo <?= $this->contenido["tipo"] ?>
                se ha llegado a asignar un <strong><?= $this->contenido["total"] ?>%</strong> del total de su
                Presupuesto Negociado (<?= $this->contenido["presupuesto"] ?> puntos).
            </p>
        </td>
    </tr>
    <hr>
</table>
</body>
</html>