<html>
<head>
</head>
<body>
<table>
    <tr>
        <th><h3 align="center">Registro de Pedidos Demanda</h3></th>
    </tr>
    <tr>
        <td>Se ha registrado un nuevo formulario pedido para la empresa cliente
            <strong><?= $this->contenido["empresa"] ?></strong></td>
    </tr>
    <hr>
    <tr>
        <td><strong>Ruc: </strong><?= $this->contenido["ruc"] ?></td>
    </tr>
    <tr>
        <td><strong>Razón Social: </strong><?= $this->contenido["razon"] ?></td>
    </tr>
    <tr>
        <td><strong>Personal de Contacto: </strong><?= $this->contenido["contacto"] ?></td>
    </tr>
    <hr>
    <tr>
        <td><strong>Campaña: </strong><?= $this->contenido["campania"] ?></td>
    </tr>
    <tr>
        <td><strong>Segmento: </strong><?= $this->contenido["segmento"] ?></td>
    </tr>
    <tr>
        <td><strong>Fecha de Creacion: </strong><?= $this->contenido["fecha"] ?></td>
    </tr>
    <tr>
        <td><strong>Rubro: </strong><?= $this->contenido["rubros"] ?></td>
    </tr>
    <tr>
        <td><strong>Empresa Proveedoras: </strong><?= $this->contenido["proveedores"] ?></td>
    </tr>
    <tr>
        <td><strong>Empresa Proveedoras Adicionales: </strong><?= $this->contenido["adicionales"] ?></td>
    </tr>
    <tr>
        <td><strong>Departamentos: </strong><?= $this->contenido["departamentos"] ?></td>
    </tr>
    <hr>
    <tr>
        <td><strong>Precio Mínimo: </strong><?= $this->contenido["preciomin"] ?></td>
    </tr>
    <tr>
        <td><strong>Precio Máximo: </strong><?= $this->contenido["preciomax"] ?></td>
    </tr>
    <tr>
        <td><strong>Target: </strong><?= $this->contenido["target"] ?></td>
    </tr>
    <tr>
        <td><strong>Comentarios: </strong><?= $this->contenido["comentarios"] ?></td>
    </tr>
    <tr>
        <td><strong>Actualizaciones: </strong><?= $this->contenido["actualizaciones"] ?></td>
    </tr>
</table>

</body>
</html>