<?php
$this->inlineScript()->appendFile($this->basePath('js/puntos/asignacion_personalizado.js'));

$dataNumeroDocumento = (!empty($this->numeroDocumento)) ? $this->numeroDocumento : "[]";
$dataSumaPuntos = (!empty($this->sumaPuntos)) ? $this->sumaPuntos : "[]";
$dataRestaPuntos = (!empty($this->restaPuntos)) ? $this->restaPuntos : "[]";
$dataPuntosAsignados = (!empty($this->puntosAsignados)) ? $this->puntosAsignados : "[]";
$dataEstadoAsignacion = (!empty($this->estadoAsignacion)) ? $this->estadoAsignacion : "[]";

$dataNumeroDocumentoMessage = (!empty($this->numeroDocumentoMessage)) ? $this->numeroDocumentoMessage : "[]";
$dataSumaPuntosMessage = (!empty($this->sumaPuntosMessage)) ? $this->sumaPuntosMessage : "[]";
$dataRestaPuntosMessage = (!empty($this->restaPuntosMessage)) ? $this->restaPuntosMessage : "[]";

$this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function () {
    var total = '$this->totalDatos';
    if (total !== '0') {
        var documentos = $dataNumeroDocumento;
        var asignados = $dataPuntosAsignados;
        var estados = $dataEstadoAsignacion;
        var sumas = $dataSumaPuntos;
        var restas = $dataRestaPuntos;

        var documentosMessage = $dataNumeroDocumentoMessage;
        var sumasMessage = $dataSumaPuntosMessage;
        var restasMessage = $dataRestaPuntosMessage;

        for (var i = 0; i < total - 1; i++) {
            agregarCampos();
        }

        $("#data-content").find(".form-group").each(function (index, value) {
                $(value).find('input.estado_asignado').val(documentos[index]);

                $(value).find('input.documento-control').val(documentos[index]);
                $(value).find('div.numeroDocumento').html(documentosMessage[index]);
                $(value).find('input.documento-control').prop("disabled", true);

                $(value).find('input.sumaPuntos').val(sumas[index]);
                $(value).find('div.sumaPuntos').html(sumasMessage[index]);

                $(value).find('input.restaPuntos').val(restas[index]);
                $(value).find('div.restaPuntos').html(restasMessage[index]);

                $(value).find('label.asignados-control').html(asignados[index]);

                if (typeof estados[index] == "undefined" || estados[index] == "") {
                    $(value).find('input.documento-control').prop("disabled", false);
                    
                    $('<input>').attr({
                        type: 'hidden',
                        name: 'estado[]',
                        value: ''
                    }).appendTo(value);
                } else if (estados[index] == "Desactivado") {
                    $(value).find('input.sumaPuntos').prop("disabled", true);
                    $(value).find('input.restaPuntos').prop("disabled", true);
                } else {
                    var nombre = $(value).find('input.documento-control').attr('name');
                    $('<input>').attr({
                        type: 'hidden',
                        name: nombre,
                        value: documentos[index]
                    }).appendTo(value);

                    $('<input>').attr({
                        type: 'hidden',
                        name: 'estado[]',
                        value: estados[index]
                    }).appendTo(value);
                }
            }
        );
    }
});
JS;
$this->inlineScript()->captureEnd();
$this->inlineScript();