<section class="content-header">
    <br><br><br>

    <h1>Configuraciones</h1>
    <br><br>
    <?php if (!empty($message)) :
        echo '<div class="callout alert alert-' . $this->type . '"><button class="close" data-dismiss="alert" type="button">×</button>';
        echo $message;
        echo '</div>';
    endif; ?>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-offset-1 col-md-10">
                            <?php
                            $form = $this->form;
                            $form->setAttribute('class', 'form-horizontal');
                            $form->setAttribute('action', $this->url('referido-config', array('action' => 'index')))->prepare();
                            $form->setAttribute('id', 'add-config');
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            echo $this->formElement($form->get('csrf'));
                            ?>
                            <h4>Puntos por asignación</h4>
                            <br>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('repeticion_01')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2">
                                        <label for="repeticion_01">1 Repetición</label>
                                    </div>
                                    <div class="col-md-4">
                                        <?= $this->formRow($form->get('repeticion_01')); ?>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('repeticion_02')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2">
                                        <label for="repeticion_02">2 Repeticiones</label>
                                    </div>
                                    <div class="col-md-4">
                                        <?= $this->formRow($form->get('repeticion_02')); ?>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('repeticion_03')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2">
                                        <label for="repeticion_03">3 Repeticiones</label>
                                    </div>
                                    <div class="col-md-4">
                                        <?= $this->formRow($form->get('repeticion_03')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('repeticion_04')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2">
                                        <label for="repeticion_04">4 Repeticiones</label>
                                    </div>
                                    <div class="col-md-4">
                                        <?= $this->formRow($form->get('repeticion_04')); ?>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <h4>Banner Landing</h4>
                            <br>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('banner_ref')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2">
                                        <label for="banner_ref">Imagen banner</label>
                                    </div>
                                    <div class="col-md-6">
                                        <?= $this->formRow($form->get('banner_ref')); ?>
                                    </div>
                                </div>
                                <?php if (!empty($this->imagen_banner)) : ?>
                                    <div class="col-xs-2" style="padding-left:0;">
                                        <a class="single_image" href="/elements/banner_referidos/<?= $this->imagen_banner ?>">
                                            <img style="height: 50px;width: 50px;"
                                                 src="/elements/banner_referidos/<?= $this->imagen_banner ?>">
                                        </a>
                                    </div>
                                <?php endif; ?>

                                <p class="error">
                                    <?php echo $this->imagen_banner_error ?>
                                </p>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('banner_link_ref')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2">
                                        <label for="banner_link_ref">Link</label>
                                    </div>
                                    <div class="col-md-4">
                                        <?= $this->formRow($form->get('banner_link_ref')); ?>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <h4>Popup Landing</h4>
                            <br>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('popup_ref')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2">
                                        <label for="popup_ref">Imagen popup</label>
                                    </div>
                                    <div class="col-md-6">
                                        <?= $this->formRow($form->get('popup_ref')); ?>
                                    </div>
                                </div>
                                <?php if (!empty($this->imagen_popup)) : ?>
                                    <div class="col-xs-2" style="padding-left:0;">
                                        <a class="single_image" href="/elements/banner_referidos/<?= $this->imagen_popup ?>">
                                            <img style="height: 50px;width: 50px;"
                                                 src="/elements/banner_referidos/<?= $this->imagen_popup ?>">
                                        </a>
                                    </div>
                                <?php endif; ?>

                                <p class="error">
                                    <?php echo $this->imagen_popup_error ?>
                                </p>
                            </div>
                            <br>
                            <h4>Correo Administrador</h4>
                            <br>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('correo_ref')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2">
                                        <label for="correo_ref">Correo</label>
                                    </div>
                                    <div class="col-md-4">
                                        <?= $this->formRow($form->get('correo_ref')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="box-footer">
                                <div class="col-md-4 col-md-offset-4">
                                    <?php echo $this->formSubmit($form->get('submit')); ?>
                                </div>
                            </div>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
$this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function () {
    $('.single_image').fancybox();
});
JS;
$this->inlineScript()->captureEnd();
$this->inlineScript();