<?php
/**
 * Created by PhpStorm.
 * User: luisvar
 * Date: 23/11/15
 * Time: 05:13 PM
 */ ?>
<div class="modal fade" id="adminModal" tabindex="-1" role="dialog" aria-labelledby="adminModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button id="btn_close_modal" type="button" class="close" data-dismiss="modal"
                        aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" id="adminModalRedimir">Importante</h3>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <h4 id="message-redimir">¿Esta seguro de cambiar el estado del cupon?</h4>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="redimir-button" type="button" class="btn btn-primary">Si</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>