<section class="content-header ">
    <br><br><br>

    <h1 class="box-title">Redimir Cupones Premios</h1>
    <br><br>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $formS = $this->formS;
                            $formS->setAttribute('action', $this->url('cupon-premios', array('action' => 'edit', 'id' => $this->id)));
                            $formS->setAttribute('id', 'searchForm');
                            $formS->prepare();
                            echo $this->form()->openTag($formS);
                            echo $this->formElement($formS->get('csrf'));

                            ?>
                            <fieldset>
                                <legend>Buscar por:</legend>
                                <div class="form-group <?= (isset($mensaje)) ? 'has-error' : '' ?>">
                                    <div class="col-md-4 text-right"><label>Codigo Cupon:</label></div>
                                    <div class="col-md-4">
                                        <?= $this->formRow($formS->get('cupon')); ?>
                                        <?= (isset($mensaje)) ? '<label>' . $mensaje . '<label>' : ''; ?>
                                    </div>
                                    <div class="col-md-4 text-left">
                                        <?= $this->formSubmit($formS->get('submit')); ?>
                                    </div>
                                </div>
                            </fieldset>
                            <?= $this->form()->closeTag(); ?>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <?php
                            $form = $this->form;
                            $form->setAttribute('action', $this->url('cupon-premios', array('action' => $this->action)));
                            $form->setAttribute('class', 'form-horizontal');
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            echo $this->formElement($form->get('csrf'));
                            ?>
                            <fieldset>
                                <div class="form-group <?= $this->tipoUsuario == 'proveedor' ? "resaltar" : "" ?>">
                                    <div>
                                        <div class="col-md-3"><label>Codigo Cupon:</label></div>
                                        <div class="col-md-9">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <?= $this->formRow($form->get('id')); ?>
                                                    <?php echo $this->formRow($form->get('CodigoCupon')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div>
                                        <div class="col-md-3"><label>Titulo de la Oferta:</label></div>
                                        <div class="col-md-9">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <?php echo $this->formRow($form->get('Titulo')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?php if ($this->active): ?>
                                    <div class="form-group">
                                        <div>
                                            <div class="col-md-3">
                                                <label>Empresa Proveedora:</label><br>
                                            </div>
                                            <div class="col-md-9">
                                                <div class="row-fluid campo">
                                                    <div class="col-md-11 null-padding input">
                                                        <?php echo $this->formRow($form->get('EmpresaProv')); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <div class="form-group">
                                    <div>
                                        <div class="col-md-3"><label>Campaña:</label></div>
                                        <div class="col-md-9">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <?php echo $this->formRow($form->get('Campania')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div>
                                        <div class="col-md-3"><label>Estado Campaña:</label></div>
                                        <div class="col-md-9">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <?php echo $this->formRow($form->get('EstadoCampania')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div>
                                        <div class="col-md-3"><label>Estado Cupon:</label></div>
                                        <div class="col-md-9">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <?php echo $this->formRow($form->get('EstadoCupon')); ?>
                                                    <?php if ($this->tipoUsuario != 'proveedor'): ?>
                                                        <label>Estado Seleccionado: <span
                                                                id="span_helper"></span></label>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?php if ($this->active): ?>
                                    <div class="form-group">
                                        <div>
                                            <div class="col-md-3">
                                                <label>Precio Beneficio:</label><br>
                                            </div>
                                            <div class="col-md-9">
                                                <div class="row-fluid campo">
                                                    <div class="col-md-11 null-padding input">
                                                        <?php echo $this->formRow($form->get('PrecioBeneficio')); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <div class="form-group <?= $this->tipoUsuario == 'proveedor' ? "resaltar" : "" ?>">
                                    <div>
                                        <div class="col-md-3">
                                            <label>Precio Final del Cupón:</label><br>
                                            <label>(Importe a cobrar)</label>
                                        </div>
                                        <div class="col-md-9">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <input type="text" class="form-control form-cupon"
                                                           name="PrecioFinal" disabled="disabled" value="0 soles">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div>
                                        <div class="col-md-3"><label>Comentarios:</label></div>
                                        <div class="col-md-9">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <?php echo $this->formRow($form->get('Comentarios')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div>
                                        <div class="col-md-3"><label>Condiciones de Uso:</label></div>
                                        <div class="col-md-9">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <div class="box">
                                                        <div class="box-body pad">
                                                            <?= $this->formRow($form->get('CondicionesUso')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div>
                                        <div class="col-md-3"><label>Fecha Vigencia:</label></div>
                                        <div class="col-md-9">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <?php echo $this->formRow($form->get('FechaFinVigencia')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?php if (!empty($this->cupon)): ?>
                                    <div class="box-footer">
                                        <div class="col-md-4 col-md-offset-4">
                                            <a href="<?= $this->url('cupon-premios', array('action' => 'index')) ?>"
                                               class="btn btn-default" role="button">Cancelar</a>
                                            <?php echo $this->formSubmit($form->get('submit')); ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </fieldset>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
if ($this->tipoUsuario == 'proveedor') {
    $this->inlineScript()->appendFile($this->basePath('js/cupon/redimir-premios.js'));
    echo $this->render('_modal.phtml');
    echo $this->render('_redimir.phtml');
} else {
    $this->inlineScript()->appendFile($this->basePath('js/cupon/redimir-premios-admin.js'));
    echo $this->render('_modal.phtml');
    echo $this->render('_modal_comentario.phtml');
    echo $this->render('_redimir_admin.phtml');
}
