<section class="content-header ">
    <br><br><br>

    <h1 class="box-title">Redimir Cupones Premios</h1>
    <br><br>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $totalPagar = 0;
                            $asignaciones = $this->asignaciones;
                            $order_by = $this->order_by;
                            $order = $this->order;
                            $p = $this->p;
                            $q1 = $this->q1;
                            $q2 = $this->q2;
                            $q3 = $this->q3;
                            $q4 = $this->q4;
                            $q5 = $this->q5;
                            $q6 = $this->q6;
                            $q7 = $this->q7;

                            $formS = $this->formS;
                            $formS->setAttribute('action', $this->url('cupon-premios', array('action' => 'index')));
                            $formS->setAttribute('id', 'searchForm');
                            $formS->prepare();
                            echo $this->form()->openTag($formS);
                            echo $this->formElement($formS->get('csrf'));
                            ?>
                            <fieldset>
                                <legend>Buscar por:</legend>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-2 text-right"><label>Nombre Comercial o Razón
                                                    Social:</label></div>
                                            <div class="col-md-6">
                                                <?= (!empty($this->nombreEmpresa)) ? "<label>$this->nombreEmpresa</label>" : "" ?>
                                                <?= $this->formRow($formS->get('Empresa')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-2 text-right"><label>Campaña</label></div>
                                            <div class="col-md-6">
                                                <?= $this->formRow($formS->get('Campania')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-2 text-right"><label>Titulo Oferta</label></div>
                                            <div class="col-md-6">
                                                <?= $this->formRow($formS->get('Oferta')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group <?= (isset($mensaje)) ? 'has-error' : '' ?>">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-2 text-right"><label>Estado del cupón:</label></div>
                                            <div class="col-md-4">
                                                <?= $this->formRow($formS->get('EstadoCupon')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-2 text-right"><label>Desde:</label></div>
                                            <div class="col-md-4">
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-calendar"></i>
                                                    </div>
                                                    <?= $this->formRow($formS->get('FechaInicio')); ?>
                                                </div>
                                            </div>
                                            <div class="col-md-2 text-right"><label>Hasta:</label></div>
                                            <div class="col-md-4">
                                                <dipuv class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-calendar"></i>
                                                    </div>
                                                    <?= $this->formRow($formS->get('FechaFin')); ?>
                                                </dipuv>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group <?= (isset($mensaje)) ? 'has-error' : '' ?>">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-2 text-right"><label>Código del cupón:</label></div>
                                            <div class="col-md-4">
                                                <?= $this->formRow($formS->get('Cupon')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group <?= (isset($mensaje)) ? 'has-error' : '' ?>">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-4 text-left">
                                                <?= $this->formSubmit($formS->get('submit')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                            <?= $this->form()->closeTag(); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $formE = $this->formE;
                            $formE->setAttribute('action', $this->url('cupon-premios', array('action' => 'envioCupon')));
                            $formE->prepare();
                            echo $this->form()->openTag($formE);
                            echo $this->formElement($formE->get('csrf'));
                            ?>
                            <div class="dataTables_wrapper form-inline dt-bootstrap" id="example1_wrapper">
                                <div class="row-fluid">
                                    <div class="col-md-12 text-right">
                                        <div id="example1_length" class="dataTables_length"><br>
                                            <a href="<?php echo $this->url(
                                                'cupon-premios',
                                                array(
                                                    'action' => 'export',
                                                    'empresa' => (!empty($q1)) ? $q1 : 0,
                                                    'campania' => (!empty($q2)) ? $q2 : 0,
                                                    'oferta' => (!empty($q3)) ? $q3 : 0,
                                                    'estado' => (!empty($q4)) ? str_replace(" ", "-", $q4) : "Generado",
                                                    'desde' => $q5,
                                                    'hasta' => $q6,
                                                    'codigo' => (!empty($q7)) ? $q7 : null,
                                                )
                                            ); ?>"
                                               class="btn btn-primary">Exportar</a>
                                        </div>
                                    </div>
                                    <?php if (isset($this->opcion)): ?>
                                        <div class="col-md-12">
                                            <?php if ($q4 == "Por Pagar"): ?>
                                                <div class="col-md-2 text-right"><label>Total a pagar:</label></div>
                                                <div class="col-md-2">
                                                    <input type="text" title="total a pagar" id="total-pagar"
                                                           value="" disabled>
                                                </div>
                                                <div class="col-md-8 text-right">
                                                    <label for="allCheck">
                                                        Seleccionar todos <input type="checkbox" name="allCheck"
                                                                                 id="allCheck">
                                                    </label>
                                                </div>
                                            <?php else: ?>
                                                <div class="col-md-12 text-right">
                                                    <label for="allCheck">
                                                        Seleccionar todos <input type="checkbox" name="allCheck"
                                                                                 id="allCheck">
                                                    </label>
                                                </div>
                                            <?php endif; ?>

                                        </div>
                                    <?php endif; ?>
                                    <div class="col-sm-12">
                                        <table role="grid" id="asignados"
                                               class="table table-bordered table-striped dataTable">
                                            <thead>
                                            <tr role="row">
                                                <th>
                                                    <a href="<?= $this->url(
                                                        'cupon-premios',
                                                        array(
                                                            'order_by' => 'Empresa',
                                                            'order' => ($order_by == 'Empresa') ? $order : 'asc',
                                                            'page' => $p,
                                                            'q1' => $q1,
                                                            'q2' => $q2,
                                                            'q3' => $q3,
                                                            'q4' => $q4,
                                                            'q5' => $q5,
                                                            'q6' => $q6,
                                                            'q7' => $q7
                                                        )
                                                    ); ?>">Empresa Proveedora</a>
                                                </th>
                                                <th>
                                                    <a href="<?= $this->url(
                                                        'cupon-premios',
                                                        array(
                                                            'order_by' => 'Campania',
                                                            'order' => ($order_by == 'Campania') ? $order : 'asc',
                                                            'page' => $p,
                                                            'q1' => $q1,
                                                            'q2' => $q2,
                                                            'q3' => $q3,
                                                            'q4' => $q4,
                                                            'q5' => $q5,
                                                            'q6' => $q6,
                                                            'q7' => $q7
                                                        )
                                                    ); ?>">Campaña</a>
                                                </th>
                                                <th>
                                                    <a href="<?= $this->url(
                                                        'cupon-premios',
                                                        array(
                                                            'order_by' => 'Oferta',
                                                            'order' => ($order_by == 'Oferta') ? $order : 'asc',
                                                            'page' => $p,
                                                            'q1' => $q1,
                                                            'q2' => $q2,
                                                            'q3' => $q3,
                                                            'q4' => $q4,
                                                            'q5' => $q5,
                                                            'q6' => $q6,
                                                            'q7' => $q7
                                                        )
                                                    ); ?>">Oferta</a>
                                                </th>
                                                <th>
                                                    <a href="<?= $this->url(
                                                        'cupon-premios',
                                                        array(
                                                            'order_by' => 'Cupon',
                                                            'order' => ($order_by == 'Cupon') ? $order : 'asc',
                                                            'page' => $p,
                                                            'q1' => $q1,
                                                            'q2' => $q2,
                                                            'q3' => $q3,
                                                            'q4' => $q4,
                                                            'q5' => $q5,
                                                            'q6' => $q6,
                                                            'q7' => $q7
                                                        )
                                                    ); ?>">Código Cupon</a>
                                                </th>
                                                <th>
                                                    <a href="<?= $this->url(
                                                        'cupon-premios',
                                                        array(
                                                            'order_by' => 'PVP',
                                                            'order' => ($order_by == 'PVP') ? $order : 'asc',
                                                            'page' => $p,
                                                            'q1' => $q1,
                                                            'q2' => $q2,
                                                            'q3' => $q3,
                                                            'q4' => $q4,
                                                            'q5' => $q5,
                                                            'q6' => $q6,
                                                            'q7' => $q7
                                                        )
                                                    ); ?>">PVP</a>
                                                </th>
                                                <th>
                                                    <a href="<?= $this->url(
                                                        'cupon-premios',
                                                        array(
                                                            'order_by' => 'PB',
                                                            'order' => ($order_by == 'PB') ? $order : 'asc',
                                                            'page' => $p,
                                                            'q1' => $q1,
                                                            'q2' => $q2,
                                                            'q3' => $q3,
                                                            'q4' => $q4,
                                                            'q5' => $q5,
                                                            'q6' => $q6,
                                                            'q7' => $q7
                                                        )
                                                    ); ?>">PB</a>
                                                </th>
                                                <th>
                                                    <a href="<?= $this->url(
                                                        'cupon-premios',
                                                        array(
                                                            'order_by' => 'Estado',
                                                            'order' => ($order_by == 'Estado') ? $order : 'asc',
                                                            'page' => $p,
                                                            'q1' => $q1,
                                                            'q2' => $q2,
                                                            'q3' => $q3,
                                                            'q4' => $q4,
                                                            'q5' => $q5,
                                                            'q6' => $q6,
                                                            'q7' => $q7
                                                        )
                                                    ); ?>">Estado</a>
                                                </th>
                                                <th>
                                                    <a href="<?= $this->url(
                                                        'cupon-premios',
                                                        array(
                                                            'order_by' => 'UltimaActualizacion',
                                                            'order' => ($order_by == 'UltimaActualizacion') ? $order : 'asc',
                                                            'page' => $p,
                                                            'q1' => $q1,
                                                            'q2' => $q2,
                                                            'q3' => $q3,
                                                            'q4' => $q4,
                                                            'q5' => $q5,
                                                            'q6' => $q6,
                                                            'q7' => $q7
                                                        )
                                                    ); ?>">Ultima Actualización</a>
                                                </th>
                                                <?php if (isset($this->opcion)):
                                                    if ($this->opcion == "Redimido" or $this->opcion == "Pagado"):
                                                        echo '<th style="max-width: 50px">Por Pagar</th>';
                                                    elseif ($this->opcion == "Por Pagar"):
                                                        echo '<th style="max-width: 50px">Pagados</th>';
                                                    endif;
                                                endif; ?>
                                                <th style="max-width: 50px">Editar</th>
                                            </thead>
                                            <tbody>
                                            <?php if (count($asignaciones) > 0) :
                                                foreach ($asignaciones as $dato) :
                                                    $totalPagar = $totalPagar + $dato->PrecioBeneficio; ?>
                                                    <tr data-id="<?php echo $dato->id ?>">
                                                        <td><?= $this->escapeHtml($dato->Empresa); ?></td>
                                                        <td><?= $this->escapeHtml($dato->Campania); ?></td>
                                                        <td><?= $this->escapeHtml($dato->Oferta); ?></td>
                                                        <td><?= $this->escapeHtml($dato->CodigoCupon); ?></td>
                                                        <td><?= $this->escapeHtml($dato->PrecioVentaPublico); ?></td>
                                                        <td><?= $this->escapeHtml($dato->PrecioBeneficio); ?></td>
                                                        <td>
                                                            <?php if ($this->escapeHtml($dato->EstadoCupon) == "Generado"):
                                                                echo "Descargado";
                                                            elseif ($this->escapeHtml($dato->EstadoCupon) == "Stand By"):
                                                                echo "Reclamado";
                                                            else:
                                                                echo $this->escapeHtml($dato->EstadoCupon);
                                                            endif; ?>
                                                        </td>
                                                        <td><?= $this->escapeHtml($dato->UltimaActualizacion); ?></td>
                                                        <?php if (isset($this->opcion)):
                                                            if ($this->opcion == "Redimido" or $this->opcion == "Pagado"):
                                                                echo '<td><input type="checkbox" title="Por Pagar"
                                                                       class="por_pagar_check" name="por_pagar_check[]" 
                                                                       value="' . $dato->id . '"></td>';
                                                            elseif ($this->opcion == "Por Pagar"):
                                                                echo '<td><input type="checkbox" title="Pagados"
                                                                       class="pagado_check" name="pagado_check[]" 
                                                                       value="' . $dato->id . '"></td>';
                                                            endif;
                                                        endif; ?>
                                                        <td>
                                                            <a href="<?= $this->url('cupon-premios', array('action' => 'edit', 'id' => $dato->id)); ?>">
                                                                <i class="btn btn-warning fa fa-pencil-square-o"></i></a>
                                                        </td>
                                                    </tr>
                                                <?php endforeach;
                                            else :
                                                echo '<tr><td colspan="10">No hay Datos Seleccionados</td></tr>';
                                            endif; ?>
                                            </tbody>
                                        </table>
                                        <div class="col-md-4"><br>
                                            <p>
                                                <?php if (count($asignaciones) > 0): ?>
                                                    <?= (($asignaciones->getCurrentPageNumber() * $asignaciones->getItemCountPerPage()) -
                                                        ($asignaciones->getItemCountPerPage() - 1)); ?>
                                                    -
                                                    <?= ($asignaciones->getCurrentPageNumber() * $asignaciones->getItemCountPerPage() <
                                                        $asignaciones->getTotalItemCount())
                                                        ? $asignaciones->getCurrentPageNumber() * $asignaciones->getItemCountPerPage()
                                                        : $asignaciones->getTotalItemCount() ?> de
                                                    <?= $asignaciones->getTotalItemCount(); ?> Registros
                                                <?php endif; ?>
                                            </p>
                                        </div>
                                        <?php
                                        if (isset($asignaciones)) {
                                            echo $this->paginationControl(
                                                $asignaciones,
                                                'Sliding',
                                                'paginator-cupon-premios',
                                                array(
                                                    'order_by' => $order_by,
                                                    'order' => ($order == "desc") ? 'asc' : 'desc',
                                                    'q1' => (!empty($q1)) ? $q1 : 0,
                                                    'q2' => (!empty($q2)) ? $q2 : 0,
                                                    'q3' => (!empty($q3)) ? $q3 : 0,
                                                    'q4' => (!empty($q4)) ? str_replace(" ", "-", $q4) : "Generado",
                                                    'q5' => $q5,
                                                    'q6' => $q6,
                                                    'q7' => (!empty($q7)) ? $q7 : null,
                                                )
                                            );
                                        } ?>
                                    </div>
                                </div>
                            </div>
                            <?php if (count($asignaciones) > 0) : ?>
                                <div class="box-footer">
                                    <div class="col-md-10">
                                        <?php if (isset($this->opcion)):
                                            if ($this->opcion == "Redimido" or $this->opcion == "Pagado"):
                                                echo $this->formElement($formE->get('porPagarButton'));
                                            elseif ($this->opcion == "Por Pagar"):
                                                echo $this->formElement($formE->get('pagadoButton'));
                                            endif;
                                        endif; ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <?= $this->form()->closeTag(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
echo $this->partial('_scripts.phtml');
if ($q4 == "Por Pagar") {
    echo $this->partial('_functions.phtml', array('totalPagar' => $totalPagar));
}
