<?php
/**
 * Created by PhpStorm.
 * User: luisvar
 * Date: 23/11/15
 * Time: 05:13 PM
 */?>
<!-- botton action-->
<button type="button" class="btn btn-primary btn-lg hide" id="btn_modal" data-toggle="modal" data-target="#myModal-Alerta">
</button>
<!-- Modal -->
<div class="modal fade" id="myModal-Alerta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button id="btn_close_modal" type="button" class="close" data-dismiss="modal"
                        aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" id="myModalLabel"></h3>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <h4 id="message-modal"></h4>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Aceptar</button>
            </div>
        </div>
    </div>
</div>