<section class="content-header ">
    <br><br><br>

    <h1 class="box-title">Redimir Cupones</h1>
    <br><br>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $formS = $this->formS;
                            $formS->setAttribute('action', $this->url('cupon'));
                            $formS->setAttribute('id', 'searchform');
                            $formS->prepare();
                            echo $this->form()->openTag($formS);
                            echo $this->formElement($formS->get('csrf'));
                            ?>
                            <fieldset>
                                <legend>Buscar por:</legend>
                                <div class="form-group <?= (isset($mensaje)) ? 'has-error' : '' ?>">
                                    <div class="col-md-4 text-right"><label>Codigo Cupon:</label></div>
                                    <div class="col-md-4">
                                        <?= $this->formRow($formS->get('cupon')); ?>
                                        <?= (isset($mensaje)) ? '<label>' . $mensaje . '<label>' : ''; ?>
                                    </div>
                                    <div class="col-md-4 text-left">
                                        <?= $this->formSubmit($formS->get('submit')); ?>
                                    </div>
                                </div>
                            </fieldset>
                            <?= $this->form()->closeTag(); ?>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $form = $this->form;
                            $form->setAttribute('action', $this->url('cupon', array('action' => 'add')));
                            $form->setAttribute('class', 'form-horizontal');
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            echo $this->formElement($form->get('csrf'));
                            ?>
                            <div class="form-group">
                                <div>
                                    <div class="col-md-2 col-md-offset-2"><label>Codigo Cupon:</label></div>
                                    <div class="col-md-6">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('id')); ?>
                                                <?php echo $this->formRow($form->get('CodigoCupon')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div>
                                    <div class="col-md-2 col-md-offset-2"><label>Titulo de la Oferta:</label></div>
                                    <div class="col-md-6">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?php echo $this->formRow($form->get('Titulo')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div>
                                    <div class="col-md-2 col-md-offset-2"><label>Condiciones de Uso (Oferta):</label>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?php echo $this->formRow($form->get('CondicionesUso')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div>
                                    <div class="col-md-2 col-md-offset-2"><label>Fecha Vigencia:</label></div>
                                    <div class="col-md-6">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?php echo $this->formRow($form->get('FechaFinVigencia')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="box-footer">
                                <div class="col-md-4 col-md-offset-4">
                                    <button id="limpiar" type="button" class="btn btn-default">Cancelar</button>
                                    <?php echo $this->formSubmit($form->get('submit')); ?>
                                </div>
                            </div>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
$this->inlineScript()->appendFile($this->basePath('js/cupon/redimir.js'));
echo $this->render('_modal.phtml');
echo $this->render('_redimir.phtml');