<!--/**
 * Created by PhpStorm.
 * User: luisvar
 * Date: 11/09/15
 * Time: 11:17 AM
 */-->

<section class="content-header ">
    <br><br><br>

    <h1 class="box-title">Registrar Oferta</h1>
    <br><br>
    <?php if (isset($confirm) && $confirm != null) {
        echo '<div class="callout alert alert-' . $type . '">' .
            '<button class="close" data-dismiss="alert" type="button">×</button>';
        foreach ($confirm as $message) {
            echo '<li>' . $message . '</li>';
        }
        echo '</div>';
    }
    ?>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <?php
                        $form = $this->form;
                        $form->setAttribute('action', $this->url('oferta', array('action' => 'add')));
                        $form->setAttribute('class', 'form-horizontal form-oferta');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formElement($form->get('csrf'));
                        ?>
                        <fieldset>
                            <legend>Datos de Asignación</legend>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('Empresa')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Nombre Comercial o Razón Social o RUC:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input-2">
                                                <?= $this->formRow($form->get('Empresa')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row-fluid">
                                    <div class="col-md-2"></div>
                                    <div class="col-md-10 hid">
                                        <div class="col-md-4">
                                            <label class="col-md-12">Descarga:</label>
                                        </div>
                                        <div class="col-md-4">
                                            <label class="col-md-12">Presencia:</label>
                                        </div>
                                        <div class="col-md-4">
                                            <label class="col-md-12">Leads:</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="col-md-2">
                                        <label>Diponible en BOLSA:</label>
                                    </div>
                                    <div class="col-md-10 less-pad">
                                        <div class="col-md-4">
                                            <?= $this->formRow($form->get('Descarga')); ?>
                                        </div>
                                        <div class="col-md-4">
                                            <?= $this->formRow($form->get('Presencia')); ?>
                                        </div>
                                        <div class="col-md-4">
                                            <?= $this->formRow($form->get('Lead')); ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('Tipo')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Tipo de Oferta:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input-2">
                                                <?= $this->formRow($form->get('Tipo')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="<?= $this->formElementErrors($form->get('Stock'))
                                    ? 'has-error' : '' ?> stock-principal">
                                    <div class="col-md-1"><label>Stock:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input-2">
                                                <?= $this->formRow($form->get('Stock')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group" id="tipoOfertaContent">
                                <div class="<?= $this->formElementErrors($form->get('TipoAtributo'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Tipo Oferta:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <label>
                                                    <?= $this->formRow($form->get('TipoAtributo')); ?>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <br>
                        <fieldset id="form-config" class="hidden">
                            <legend>Configurar Formulario</legend>
                            <?php
                            foreach ($this->form_config as $dato) :
                                if ($dato->Descripcion == 'CorreoContacto') :
                                    ?>
                                    <div class="form-group">
                                        <div class="<?= $this->formElementErrors($form->get('CorreoContacto'))
                                            ? 'has-error' : '' ?>">
                                            <div class="col-md-2"><label>Correo de Contacto:</label></div>
                                            <div class="col-md-6">
                                                <div class="row-fluid campo">
                                                    <div class="col-md-11 null-padding input">
                                                        <?= $this->formRow($form->get('CorreoContacto')); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php elseif ($dato->Descripcion == 'banner') : ?>
                                    <div class="form-group">
                                        <div class="col-md-2"><label>Seleccione Banner y Agregar:</label></div>
                                        <div class="col-md-6">
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <input id="input-banner" type="file" data-show-preview="false">
                                                    <ul id="error-banner"></ul>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-2">
                                            <input type="button" class="btn btn-primary left" id="btn-banner"
                                                   value="Agregar">
                                            <div id="download-banner" class="loader left hidden">
                                                <img src="<?= $this->basepath('img/ajax_clock_small.gif') ?>">
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="col-xs-10 col-xs-offset-2">
                                        <table aria-describedby="example1_info" role="grid" id="list-banner"
                                               class="table table-bordered table-striped dataTable">
                                            <thead>
                                            <tr role="row">
                                                <th>Imagen</th>
                                                <th>Nombre de la Imagen</th>
                                                <th>Acción</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <?php
                                            if (isset($imagenebanner)) :
                                                $rand = rand(300, 500);
                                                ?>
                                                <tr id="<?= $rand ?>">
                                                    <td>
                                                        <a id="single_image"
                                                           href="/elements/banners/<?= $imagenebanner ?>">
                                                            <img style="height: 50px;width: 50px;"
                                                                 src="/elements/banners/<?= $imagenebanner ?>">
                                                        </a>
                                                    </td>
                                                    <td>
                                                        <?= $imagenebanner ?><input type="hidden" name="banner"
                                                                                    value="<?= $imagenebanner ?>">
                                                    </td>
                                                    <td>
                                                        <a onclick="deleteBanner(<?= $rand ?>,'<?= $imagenebanner ?>')"
                                                           class="btn btn-danger">Eliminar</a>
                                                    </td>
                                                </tr>
                                                <?php
                                            endif;
                                            ?>
                                            </tbody>
                                        </table>
                                    </div>
                                <?php elseif ($dato->Descripcion == 'textobanner') : ?>
                                    <br>
                                    <div class="form-group">
                                        <div class="<?= $this->formElementErrors($form->get('textobanner'))
                                            ? 'has-error' : '' ?>">
                                            <div class="col-md-2"><label>Mensaje del Formulario:</label></div>
                                            <div class="col-md-9">
                                                <div class="row-fluid campo">
                                                    <div class="col-md-11 null-padding input">
                                                        <?= $this->formRow($form->get('textobanner')); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php else : ?>
                                    <div class="col-md-6">
                                        <div class="col-md-6">
                                            <input name="form_imput[]" class="checkbox-inline" type="checkbox"
                                                   value="<?= $dato->id ?>" id="<?= $dato->Descripcion ?>"
                                                <?= (isset($camposXAsignar)) ?
                                                    (in_array($dato->id, $camposXAsignar) ? 'checked' : '') : 'checked' ?>>
                                            <label for="<?= $dato->Descripcion ?>"><?= $dato->Descripcion ?></label>
                                        </div>
                                        <div class="col-md-6">
                                            <label for="<?= $dato->Descripcion . "Req" ?>">Requerido</label>
                                            <input name="form_imput_req[]" class="checkbox-inline" type="checkbox"
                                                   value="<?= $dato->id ?>" id="<?= $dato->Descripcion . "Req" ?>"
                                                <?= (isset($camposXAsignarReq)) ?
                                                    (in_array($dato->id, $camposXAsignarReq) ? 'checked' : '') : 'checked' ?>>
                                        </div>
                                    </div>
                                    <?php
                                endif;
                            endforeach;
                            ?>
                        </fieldset>
                        <br>
                        <?php echo $this->partial('render/_tarjetas.phtml'); ?>
                        <br>
                        <fieldset>
                            <legend>Datos Generales</legend>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('Nombre')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Nombre:</label></div>
                                    <div class="col-md-10">
                                        <?= $this->formRow($form->get('Nombre')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('Titulo')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Título:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('Titulo')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('TituloCorto'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Título Corto:</label></div>
                                    <div class="col-md-10">
                                        <?= $this->formRow($form->get('TituloCorto')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('SubTitulo'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Subtítulo:</label></div>
                                    <div class="col-md-10">
                                        <?= $this->formRow($form->get('SubTitulo')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('BNF_TipoBeneficio_id'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Tipo de Beneficio:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input-2">
                                                <?= $this->formRow($form->get('BNF_TipoBeneficio_id')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('DatoBeneficio'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Dato Beneficio:</label></div>
                                    <div class="col-md-10">
                                        <?= $this->formRow($form->get('DatoBeneficio')); ?>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="precio-content">
                                <div class="form-group data-headers">
                                    <div class="col-md-3"><label>Atributos (*)</label></div>
                                    <div class="col-md-2"><label>Stock (*)</label></div>
                                    <div class="col-md-2"><label>Dato Beneficio (*)</label></div>
                                    <div class="col-md-2 label-vigencia-h"><label>Vigencia cupón (*)</label></div>
                                    <div class="col-md-2"></div>
                                </div>
                                <div class="form-group data-list">
                                    <div class="col-md-3">
                                        <textarea title="Atributo" class="form-control atributos"
                                                  name="atributos[]"></textarea>
                                        <span class="atributos"></span>
                                        <div class="atributos error"></div>
                                    </div>
                                    <div class="col-md-2">
                                        <input class="form-control stocks" name="stocks[]" type="text"
                                               title="Stock">
                                        <div class="stocks-error error"></div>
                                    </div>
                                    <div class="col-md-2">
                                        <input class="form-control dato_beneficio" name="beneficios[]" type="text"
                                               title="Dato Beneficio">
                                        <div class="beneficios-error error"></div>
                                    </div>
                                    <div class="col-md-2 input-vigencia-h">
                                        <input class="form-control vigencias datepicker" name="vigencias[]" type="text"
                                               title="vigencias">
                                        <div class="vigencias error"></div>
                                    </div>
                                    <div class="col-md-2">
                                        <button class="addfields btn btn-default" type="button">&#43;</button>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="form-group">
                                <div class="<?= (isset($menssage['imagec'])) ? '<ul><li>'
                                    . $menssage['imagec'] . '</li></ul>' : ''; ?> ">
                                    <div class="col-md-2"><label>Seleccione Imagen y Agregar:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <input id="input-file" type="file" class="file"
                                                       data-show-preview="false">
                                                <?= (isset($menssage['image'])) ? '<ul><li>'
                                                    . $menssage['image'] . '</li></ul>' : ''; ?>
                                                <ul id="error-image"></ul>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                        <div class="col-xs-2" style="padding-left:0px;">
                                            <input type="button" class="btn btn-primary left" id="btn-image"
                                                   value="Agregar">
                                            <div id="download" class="loader left hidden">
                                                <img src="<?= $this->basepath('img/ajax_clock_small.gif') ?>">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-10 col-xs-offset-2">
                                <table aria-describedby="example1_info" role="grid" id="list-image"
                                       class="table table-bordered table-striped dataTable">
                                    <thead>
                                    <tr role="row">
                                        <th>Imagen</th>
                                        <th>Nombre de la Imagen</th>
                                        <th>Principal</th>
                                        <th>Acción</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    if (isset($imagenesXAsignar)) {
                                        foreach ($imagenesXAsignar as $img) {
                                            $rand = rand(300, 500);
                                            ?>
                                            <tr id="<?= $rand ?>">
                                                <td>
                                                    <a id="single_image" href="/elements/oferta/<?= $img ?>">
                                                        <img style="height: 50px;width: 50px;"
                                                             src="/elements/oferta/<?= $img ?>">
                                                    </a>
                                                </td>
                                                <td>
                                                    <?= $img ?><input type="hidden" name="Imagen[<?= $rand ?>]"
                                                                      value="<?= $img ?>">
                                                </td>
                                                <td>
                                                    <label>
                                                        <input onclick="principalImage(<?= $rand ?>)" type="radio"
                                                               name="principal" checked>
                                                    </label>
                                                </td>
                                                <td>
                                                    <a onclick="deleteElement(<?= $rand ?>,'<?= $img ?>')"
                                                       class="btn btn-danger">Eliminar</a>
                                                </td>
                                            </tr>
                                            <?php
                                        }
                                    }
                                    ?>
                                    <tr></tr>
                                    </tbody>
                                </table>
                                <input type="hidden" name="principalimage" id="principalimage"
                                       value="<?= isset($rand) ? $rand : '' ?>">
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('Descripcion'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Descripción:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <div class="box">
                                                    <div class="box-body pad">
                                                        <?= $this->formRow($form->get('Descripcion')); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('CondicionesUso'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Condiciones de Uso:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <div class="box">
                                                    <div class="box-body pad">
                                                        <?= $this->formRow($form->get('CondicionesUso')); ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('Direccion'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Dirección:</label></div>
                                    <div class="col-md-10">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('Direccion')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-col-12 <?= $this->formElementErrors($form->get('Telefono'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Teléfono:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo input-telefono">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('Telefono')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="<?= $this->formElementErrors($form->get('Premium')) ? 'has-error' : '' ?>">
                                    <div class="col-md-4">
                                        <?= $this->formRow($form->get('Premium')); ?>
                                        <label>Premium</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('Correo')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Correo:</label></div>
                                    <div class="col-md-6">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('Correo')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('Rubro')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Rubro:</label></div>
                                    <div class="col-md-6">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('Rubro')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <br>
                        <fieldset>
                            <legend>Ubicación</legend>
                            <div class="form-group">
                                <div class="input-col-12 <?= $this->formElementErrors($form->get('Pais'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>País:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('Pais')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="<?= $this->formElementErrors($form->get('Distrito')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Distrito:</label></div>
                                    <div class="col-md-4">
                                        <?= $this->formRow($form->get('Distrito')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>
                                            <label>Departamento </label><label style="color:red"> * </label>
                                        </th>
                                        <th>
                                            <label>Categoría</label><label style="color:red"> *</label>
                                        </th>
                                        <th>
                                            <div class="col-md-3"><label>Campaña</label></div>
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <div class="checkbox-lista listdep">
                                                        <?= $this->formRow($form->get('Departamento')); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <div class="checkbox-lista listcat">
                                                        <?= $this->formRow($form->get('Categoria')); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="row-fluid campo">
                                                <div class="col-md-11 null-padding input">
                                                    <div class="checkbox-lista listcam">
                                                        <?= $this->formRow($form->get('Campania')); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </fieldset>
                        <br>
                        <fieldset>
                            <legend>Datos de Publicación</legend>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('Segmento')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Segmento:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('Segmento')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="<?= $this->formElementErrors($form->get('FechaFinVigencia'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Vigencia:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('FechaFinVigencia')); ?>
                                            </div>
                                            <div class="vigencia hidden col-md-1 null-padding text-center p">
                                                <p>*</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('FechaInicioPublicacion'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Periodo de Publicación de:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('FechaInicioPublicacion')); ?>
                                                <ul id="fecini_ul" style="color: red" hidden>
                                                    <li>La Fecha es menor a la actual</li>
                                                </ul>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="<?= $this->formElementErrors($form->get('FechaFinPublicacion'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Hasta:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('FechaFinPublicacion')); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="<?= $this->formElementErrors($form->get('DescargaMaximaDia'))
                                    ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Descarga Máxima:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('DescargaMaximaDia')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="<?= $this->formElementErrors($form->get('Estado')) ? 'has-error' : '' ?>">
                                    <div class="col-md-2"><label>Estado:</label></div>
                                    <div class="col-md-4">
                                        <div class="row-fluid campo">
                                            <div class="col-md-11 null-padding input">
                                                <?= $this->formRow($form->get('Estado')); ?>
                                            </div>
                                            <div class="col-md-1 null-padding text-center p"><p>*</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <div class="form-group">
                            <div class="col-md-offset-10 col-md-2">
                                <p>(*) Campos Obligatorios</p>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="col-md-10">
                                <?= $this->formSubmit($form->get('submit')); ?>
                                <a href="<?= $this->url('oferta', array('action' => 'index')) ?>"
                                   class="btn btn-default" role="button">Cancelar</a>
                            </div>
                        </div>
                        <br>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
$this->inlineScript()->appendFile($this->basePath('js/oferta/oferta.js?' . $this->configItem('version_script')));
$this->inlineScript()->appendFile($this->basePath('js/oferta/oferta_add.js?' . $this->configItem('version_script')));
echo $this->partial('_scriptoferta.phtml');
echo $this->partial('_script_atributos.phtml');